.TH "SIM-VICUS" 1 "January 23rd, 2022" "0.7.1" "SIM-VICUS Manual"
.SH NAME
.B SIM-VICUS\fR \- Building energy and district simulation modeling environment
.SH SYNOPSIS
.B SIM-VICUS\fR [flags] [options] [<project file>]
.SH DESCRIPTION
.B SIM-VICUS
is a graphical modeling environment for building energy models and district networks.
.SH FLAGS
.IP "\fB\-\-help\fR" 4
Prints the help page.
.IP "\fB\-\-man-page\fR" 4
Prints the man page (source version) to std output.
.IP "\fB\-\-cmd-line\fR" 4
Prints the command line as it was understood by the command line parser.
.IP "\fB\-\-options-left\fR" 4
Prints all options that are unknown to the command line parser.
.IP "\fB\-\-no-splash\fR" 4
Disables splash screen.

.SH OPTIONS
.IP "\fB\-\-lang=<en;de;it;...>\fR" 4
Specify the program language using a 2 character language ID.
.IP "\fB\-\-nandrad=<<target-name.nandrad>>\fR" 4
Generate NANDRAD simulation project from vicus-file.

