The NANDRAD CodeGenerator
=========================
Andreas Nicolai <andreas.nicolai@tu-dresden.de>
v1.0.0, June 2020
:Author Initials: AN
:toc: left
:toclevels: 3
:toc-title: Table of Contents
:icons: font
:imagesdir: ./images
:numbered:
:website: https://github.com/ghorwin/SIM-VICUS
:source-highlighter: rouge
:rouge-style: custom
:title-page:
:stylesdir: ../adoc_utils/css
:stylesheet: roboto_ubuntu.css


[[overview]]
## Overview

What is the NANDRAD-Code-Generator? Basically, it is a tool to parse NANDRAD header files, pick up lines with special comments and then generate code for:

- translating enumeration values into strings, descriptions, colors and units (very handy for physical parameter lists)
- reading and writing xml data structures (elements and attributes) for designated member variables
- comparing data structures with default instances (so that only modified members are written to file), and other utility functions

### How does it work? 

The code generator is called as part of the CMake build chain. It detects changes in header files, and then updates the respective generated files, including the file `NANDRAD_KeywordList.cpp`. It places the class-specific generated files into a subdirectory `ncg` (for **N**ANDRAD **C**ode **G**enerator files) where they are compiled just as any other cpp file of the project.

Since the generated code is plain C++ code, it can be parsed and debugged with any IDE just as regular code. Just remember:

[CAUTION]
====
Any changes made to generated code will be overwritten!
====

## Functionality Example

### Keyword support

You may have a class header, that looks as follows:
[source,c++]
----
class Interval {
public:
	/*! Parameters. */
	enum para_t {
		IP_START,		// Keyword: Start		[d] 'Start time point'
		IP_END,			// Keyword: End			[d] 'End time point'
		IP_STEPSIZE,	// Keyword: StepSize	[h] 'StepSize'
		NUM_IP
	};
	
	...
	
	/*! The parameters defining the interval. */
	IBK::Parameter   m_para[NUM_IP];
};
----

Here, you have a list of enumeration values. These are used to index one of the parameters in the member variable array `m_para`. In the code, you will use these enumerations like:

[source,c++]
----
double endtime = m_para[Interval::IP_END].value;
----

Sometimes, however, you need the keyword as a string, or need to get the unit written in the comment line. So, you write code like:

[source,c++]
----
// construct a parameter
m_para[Interval::IP_END].set(
        NANDRAD::KeywordList::Keyword("Interval::para_t", Interval::IP_END), // the keyword is used as name
        24, // value
        NANDRAD::KeywordList::Unit("Interval::para_t", Interval::IP_END) // the unit
    );
----

Normally, the unit is only meaningful for user interface representation, or when the value is printed to the user as default output/disply unit.

Also useful is the description, mostly in informative/error messages. Recommended would be:

[source,c++]
----
if (condition_failed) {
    IBK::IBK_Message(IBK::FormatString("Parameter %1 (%2) is required.")
        .arg(KeywordList::Keyword("Interval::para_t", Interval::IP_END))
        .arg(KeywordList::Description("Interval::para_t", Interval::IP_END)) );
}
----

Also, when parsing user data, for example from format:

[source,xml]
----
<IBK:Parameter name="Start" unit="d">36</IBK:Parameter>
<IBK:Parameter name="End" unit="d">72</IBK:Parameter>
----

You may need code like:

[source,c++]
----
nameAttrib = getAttributeText(xmlTag, "name"); // might be 'End'

// resolve enumeration value
Interval::para_t p = (Interval::para_t)KeywordList::Enumeration("Interval::para_t", nameAttrib);
----

The code generator will now create the implementation of the functions:

* `KeywordList::Enumeration`
* `KeywordList::Description`
* `KeywordList::Keyword`
* `KeywordList::Unit`
* `KeywordList::Color` - meaningful for coloring types in user interfaces
* `KeywordList::DefaultValue` - can be used as default value in user interfaces
* `KeywordList::Count` - returns number of enumeration values in this category
* `KeywordList::KeywordExists` - convenience function, same as comparing result of `Enumeration()` with -1


### Usage

The header file `NANDRAD_KeywordList.h` is always the same and can be included directory. The corresponding implementation file `NANDRAD_KeywordList.cpp` is generated in the same directory as the NANDRAD header files.

### CMake automation

The automatic update of the keyword list is triggered by a custom rule in the NANDRAD CMake project file:

[source,cmake]
----
# collect a list of all header files of the Nandrad library
file( GLOB Nandrad_HDRS ${PROJECT_SOURCE_DIR}/../../src/*.h )

# run the NandradCodeGenerator tool whenever the header files have changed
# to update the NANDRAD_KeywordList.h and NANDRAD_KeywordList.cpp file
add_custom_command (
	OUTPUT   ${PROJECT_SOURCE_DIR}/../../src/NANDRAD_KeywordList.cpp
	DEPENDS  ${Nandrad_HDRS} NandradCodeGenerator
	COMMAND  NandradCodeGenerator
	ARGS     NANDRAD ${PROJECT_SOURCE_DIR}/../../src
)
----

where `NandradCodeGenerator` is built as part of the tool chain as well. The rule has all header files as dependencies so that any change in any header file will result in a call to the code generator. The code generator will then create the file `NANDRAD_KeywordList.cpp`.


## Read/write to XML support, and utility macros

A second task for the code generator is to create functions for serialization of data structures to XML files. Hereby, the TinyXML-library is used.

### Read/write code

Since reading/writing XML code is pretty straight forward, much of this code writing can be generalized. Let's take a look at a simple example. 

.Class Sensor, with declarations of `readXML()` and `writeXML()` functions
[source,c++]
----
class Sensor {
public:
	// *** PUBLIC MEMBER FUNCTIONS ***

	void readXML(const TiXmlElement * element);
	TiXmlElement * writeXML(TiXmlElement * parent) const;

	// *** PUBLIC MEMBER VARIABLES ***

	/*! Unique ID-number of the sensor.*/
	unsigned int						m_id = NANDRAD::INVALID_ID;		// XML:A:required
	/*! Name of the measured quantity */
	std::string							m_quantity;						// XML:E
};
----
[TIP]
====
Since we use C++11 code, member variable initialization with the `=` assignment in header is ok and saves creating default constructors. Do this!
====

The two members are written into file as follows:

[source,xml]
----
<Sensor id="12">
    <Quantity>Temperature</Quantity>
</Sensor>
----

The implementation looks as follows:

[[generated_readXML]]
.Implementation of `Sensor::readXML()`
[source,c++]
----
void Sensor::readXML(const TiXmlElement * element) {
	FUNCID(Sensor::readXML);

	try {
		// search for mandatory attributes
		if (!TiXmlAttribute::attributeByName(element, "id"))
			throw IBK::Exception( IBK::FormatString(XML_READ_ERROR).arg(element->Row()).arg(
				IBK::FormatString("Missing required 'id' attribute.") ), FUNC_ID);

		// reading attributes
		const TiXmlAttribute * attrib = element->FirstAttribute();
		while (attrib) {
			const std::string & attribName = attrib->NameStr();
			if (attribName == "id")
				m_id = readPODAttributeValue<unsigned int>(element, attrib);
			else {
				IBK::IBK_Message(IBK::FormatString(XML_READ_UNKNOWN_ATTRIBUTE).arg(attribName).arg(element->Row()), IBK::MSG_WARNING, FUNC_ID, IBK::VL_STANDARD);
			}
			attrib = attrib->Next();
		}
		// search for mandatory elements
		// reading elements
		const TiXmlElement * c = element->FirstChildElement();
		while (c) {
			const std::string & cName = c->ValueStr();
			if (cName == "Quantity")
				m_quantity = c->GetText();
			else {
				IBK::IBK_Message(IBK::FormatString(XML_READ_UNKNOWN_ELEMENT).arg(cName).arg(element->Row()), IBK::MSG_WARNING, FUNC_ID, IBK::VL_STANDARD);
			}
			c = c->NextSiblingElement();
		}
	}
	catch (IBK::Exception & ex) {
		throw IBK::Exception( ex, IBK::FormatString("Error reading 'Sensor' element."), FUNC_ID);
	}
	catch (std::exception & ex2) {
		throw IBK::Exception( IBK::FormatString("%1\nError reading 'Sensor' element.").arg(ex2.what()), FUNC_ID);
	}
}
----

In this function there is a lot of code that is repeated nearly identical in all files of the data model. For example, reading of attributes, converting them to number values (including error checking), testing for known child elements (and error handling) and the outer exception catch clauses. Similarly, this looks for the `writeXML()` function.


.Implementation of `Sensor::writeXML()`
[source,c++]
----
TiXmlElement * Sensor::writeXML(TiXmlElement * parent, bool /*detailedOutput*/) const {
	TiXmlElement * e = new TiXmlElement("Sensor");
	parent->LinkEndChild(e);

	e->SetAttribute("id", IBK::val2string<unsigned int>(m_id));
	if (!m_quantity.empty())
		TiXmlElement::appendSingleAttributeElement(e, "Quantity", nullptr, std::string(), m_quantity);
	return e;
}
----

In order for the code generator to create these two functions, we need to add some _annotations_ to original class declaration:

.Class Sensor, with annotations for read/write code generation
[source,c++]
----
class Sensor {
public:
	// *** PUBLIC MEMBER FUNCTIONS ***

	void readXML(const TiXmlElement * element);
	TiXmlElement * writeXML(TiXmlElement * parent) const;

	// *** PUBLIC MEMBER VARIABLES ***

	/*! Unique ID-number of the sensor.*/
	unsigned int						m_id = NANDRAD::INVALID_ID;		// XML:A:required
	/*! Name of the measured quantity */
	std::string							m_quantity;						// XML:E
};
----

The `// XML:A` says: make this an attribute. The `// XML:E` says: make this a child-element. The additional `required` keyword means: this attribute (or element) must be provided, otherwise `readXML()` will throw an exception.

The annotations can be used for quite a few data types. Rules for these are given in section <<xml_serialization_rules>>.


### Utility Macros

Since the declaration for the `readXML()` and `writeXML()` functions are always the same, we can avoid typing errors by using a define:

.Global code generator helpers
[source,c++]
----
#define NANDRAD_READWRITE \
	void readXML(const TiXmlElement * element); \
	TiXmlElement * writeXML(TiXmlElement * parent) const;
----

The header is now very short:

.Class Sensor, using code generator
[source,c++]
----
class Sensor {
public:
	// *** PUBLIC MEMBER FUNCTIONS ***

	NANDRAD_READWRITE

	// *** PUBLIC MEMBER VARIABLES ***

	/*! Unique ID-number of the sensor.*/
	unsigned int						m_id = NANDRAD::INVALID_ID;		// XML:A:required
	/*! Name of the measured quantity */
	std::string							m_quantity;						// XML:E
};
----

The implementation file `NANDRAD_Sensor.cpp` is no longer needed and can be removed.

The code generator will create a file: `ncg_NANDRAD_Sensor.cpp` with the functions `Sensor::readXML()` and `Sensor::writeXML()`.

To avoid regenerating (and recompiling) all `ncg_*` files whenever _one_ header file is modified, the code generator inspects the file creation times of the `ncg_XXX.cpp` file with the latest modification/creation data of the respective `ncg_XXX.h` file. The code is only generated, if header file is newer than the generated file.

#### Comparison operator macro

When checking, if the content of an object is effectively the same as that of another (possibly freshly constructed) object, we need a comparison operator. Actually, we usually need both `operator==` and `operator!=`. The code for the class `Sensor` normally looks like that:

.Comparison operator (inequality)
[source,c++]
----
bool Sensor::operator!=(const Sensor & other) const {
	if (m_id != other.m_id)				return true;
	if (m_quantity != other.m_quantity)	return true;
	return false;
}
----

The other comparison operator is normally just implemented using the other:

.Comparison operator (inequality)
[source,c++]
----
bool operator==(const Sensor & other) const { return !operator!=(other); }
----

The declaration of the inequality 


Again, the declaration is pretty standard and can be replaced by a define:

.Global code generator helpers
[source,c++]
----
#define NANDRAD_COMP(X) \
	bool operator!=(const X & other) const;
----

So the class declaration becomes:

.Class Sensor, using code generator
[source,c++]
----
class Sensor {
public:
	/*! Default constructor. */
	Sensor() : m_id(NANDRAD::INVALID_ID) {}
	
	NANDRAD_READWRITE
	NANDRAD_COMP(Sensor)

	/*! Unique ID-number of the sensor.*/
	unsigned int						m_id;			// XML-A:
	/*! Name of the measured quantity */
	std::string							m_quantity;		// XML-E:not-empty
};
----

### Custom read/write functionality

Sometimes, the default read/write code is not enough, because something special needs to be written/read as well. Here, you can simply use an additional define:

.Global code generator helpers
[source,c++]
----
#define NANDRAD_READWRITE_PRIVATE \
	void readXMLPrivate(const TiXmlElement * element); \
	TiXmlElement * writeXMLPrivate(TiXmlElement * parent, bool detailedOutput) const;
----

and implement `readXML()` and `writeXML()` manually, hereby re-using the auto-generated functionality. The header then looks like:

.Class Sensor, using code generator with private read/write functions
[source,c++]
----
class Sensor {
	NANDRAD_READWRITE_PRIVATE
public:
	/*! Default constructor. */
	Sensor() : m_id(NANDRAD::INVALID_ID) {}
	
	NANDRAD_READWRITE
	NANDRAD_COMP(Sensor)

	/*! Unique ID-number of the sensor.*/
	unsigned int						m_id;			// XML-A:
	/*! Name of the measured quantity */
	std::string							m_quantity;		// XML-E:not-empty
};
----


.Implementation file `NANDRAD_Sensor.cpp`
[source,c++]
----
void Sensor::readXML(const TiXmlElement * element) {
	// simply reuse generated code
	readXMLPrivate(element);

	// ... read other data from element
}


TiXmlElement * Sensor::writeXML(TiXmlElement * parent, bool detailedOutput) const {
	TiXmlElement * e = writeXMLPrivate(parent, detailedOutput);

	// .... append other data to e
	return e;
}
----

[NOTE]
====
When the code generator creates `readXMLPrivate()` functions, the check for unknown elements is not generated (see <<generated_readXML, original readXML-function>>, since it can be expected that other (custom) elements are present inside the parsed XML-tag.
====

## Specifications

### Keyword List Support

The parse requires fairly consistent code to be recognized, with the following rules. Look at the following example:

[source,c++]
----
class MyClass {
public:


    enum parameterSet {
        PS_PARA1,      // Keyword: PARA1     'some lengthy description'
        PS_PARA2,      // Keyword: PARA2     [K] <#4512FF> {273.15} 'A temperature parameter'
        NUM_PS
    }
    
    enum otherPara_t {
        OP_P1,         // Keyword: P1
        OP_P2,         // Keyword: P2
        OP_P3,         // Keyword: P3
        NUM_OP
    }
...
}
----

Here are the rules/conventions (how the parser operates):

- a class scope is recognized by a string `class xxxx` (same line)
- an enum scope is recognized by a string `enum yyyy` (same line)
- a keyword specification is recognized by the string `// Keyword:` (with space between `//` and `Keyword:`!)
- either _all_ enumeration values (except the line with `NUM_XXX`) must have a keyword specification, or _none_  (the keyword spec is used to increment the enum counter)
- you *must not* assign a value to the enumeration like `MY_ENUM = 15,` - the parser does not support this format. With proper scoping, you won't need such assignments for parameter lists.


[CAUTION]
====
The parser isn't a c++ parser and does not know about comments. If the strings mentioned above are found inside a comment, the parser will not know the difference. As a consequence, the following code will confuse the parser and generate wrong keyword categories:

[source,c++]
----
class MyClass {
public:

    /* Inside this 
       class my stuff will work 
       perfectly!
    */

    enum para_t {
    ...
    }
...
}
----

This will generate the keyword category `my::para_t` because `class my` is recognized as class scope. So, **do not do this**! Same applies to enum documentation. 

Thankfully, documentation is to be placed above the class/enum declaration lines and should not interfere with the parsing.
====

When using class forward declarations, always put only the class declaration on a single line without comments afterwards:

[source,c++]
----
// forward declarations
class OtherClass;
class OtherParentClass;
class YetAnotherClass;
----

The parser will detect forward declarations when the line is ended with a `;` character. Again, this should normally not be an issue, unless someone uses a forward declaration of a class _inside_ a class scope.

### Keyword Parameters

A keyword specification line has the following format:

----
KW_ENUM_VALUE,  // Keyword:   Keyword-Name  [unit]  <color>  {default value} 'description'
----

The `Keyword-Name` can be actually a list of white-space separated keywords that are used to convert to the enumeration value: for example:

----
SP_HEATCONDCOEFF, // Keyword: HEATCONDCOEFF ALPHA [W/m2K] 'Heat conduction coefficient'
----

Allows to convert strings `HEATCONDCOEFF` and `ALPHA` to enum value `SP_HEATCONDCOEFF`, but conversion from `SP_HEATCONDCOEFF` to string always yields the first keyword `HEATCONDCOEFF` in the list.

The remaining parameters _unit_, _color_, _default value_ and _description_ are **optional**. But if present, they must appear in the order shown above. This is just to avoid nesting problems and is strictly only required from the description, since this may potentially contain the characters `<>[]{}`.

The _default value_ must be a floating point number in C locale format. Similarly as color and unit, this parameter is meaningful for user interfaces with somewhat generic parameter input handling.

[[xml_serialization_rules]]
### XML Serialization

In order for the CodeGenerator to work correct, we need a [line-through]##few## lots of rules:


. Let's start with the `writeXML()` function:

1. XML-Element name is always the same as the class name, so that's known to the code generator
2. `m_id` should be written as attribute to `Sensor`, we need to tell the code generator that this is an attribute. The conversion `unsigned int` to string is known from the type declaration.
3. `m_quantity` should be written as child-element to `Sensor`. We also need to tell the code generator, that this is to be an element. Also, we need to write the code to check that the attribute must not be empty before writing it. We should tell the code generator somehow, that the value must not appear as empty string `""` in the xml file.

This leads to some annotation comments in the header file:
