:imagesdir: ./images
[[object_lists]]
# Objektlisten und Ergebnisreferenzen

Wann immer es notwendig ist, ein Berechnungsergebnis (eines Modellobjekts) zu referenzieren, geschieht dies über die __ObjectLists__. 

:xrefstyle: short

In NANDRAD werden physikalische Gleichungen in Form von Modellobjekten organisiert, zum Beispiel Zonen oder Konstruktionen. Diese Modellobjekte können durch einen Modelltyp und eine ID-Nummer eindeutig identifiziert werden. Zum Beispiel werden alle für einen Raum/eine Zone berechneten Größen durch den Modelltyp _Zone_ und die ID-Nummer der jeweiligen Zone identifiziert. <<tab_modelRefTypes>> listet die verfügbaren Referenztyp-Schlüsselwörter auf.

[[tab_modelRefTypes]]
.Modell-Referenztypen
[options="header",cols="20%,80%",width="100%"]
|====================
| Schlüsselwort | Beschreibung
| `Zone` | Variablen bezogen auf den Raum (thermische Zonen)
| `ConstructionInstance` | Variablen, die sich auf Konstruktionen beziehen
| `Schedule` | Geplante Parameter
| `Location` | Variablen aus dem Klimaberechnungsmodell, einschließlich Strahlungssensorwerte
| `Model` | Modellspezifische Variablen/Ergebnisse
|====================

<<ex_objectLists>> zeigt mehrere Beispiele für Definitionen der Objektliste.

[[ex_objectLists]]
.Definition von mehreren Objektlisten
====
[[Quelle,xml]]
----
<ObjectLists>
	<ObjectList name="All zones">
		<FilterID>*</FilterID>
		<ReferenzTyp>Zone</ReferenzTyp>
	</ObjectList>
	<ObjectList name="Zone Var01">
		<FilterID>1</FilterID>
		<ReferenceType>Zone</ReferenceType>
	</ObjectList>
	<ObjectList name="Wall_1_and_2">
		<FilterID>1,2</FilterID>
		<ReferenceType>ConstructionInstance</ReferenceType>
	</ObjectList>
	<ObjectList name="InfiltrationModel">
		<FilterID>501</FilterID>
		<ReferenceType>Model</ReferenceType>
	</ObjectList>
	...
</ObjectLists>
----
====

## Objektlisten-Definitionen

Alle Objektlisten werden innerhalb des übergeordneten tags `ObjectLists` definiert. Jede Objektlistendefinition beginnt mit dem XML-tag `ObjectList` mit dem obligatorischen Attribut `name`, das die Objektliste eindeutig identifiziert.

Das XML-tag `ObjectList` hat die folgenden untergeordneten tags.


.Modell-Referenztypen
[options="header",cols="20%,80%",width="100%"]
|====================
| Schlüsselwort | Beschreibung
| `FilterID` | ID-Filtermuster (siehe Beschreibung unten)
| `ReferenceType` | Modellobjekt-Referenztyp (siehe <<tab_modelRefTypes>>)
|====================

## ID-Filter-Muster

Objekte (mit gleichem Referenztyp) werden durch ihre ID-Nummer eindeutig identifiziert.

[HINWEIS]
====
ID-Nummern müssen nur für Objekte mit gleichem Referenztyp eindeutig sein. Daher ist es möglich, Zone #1 und ConstructionInstance #1 gleichzeitig zu definieren.
====

Ein Filtermuster kann aus mehreren Teilen bestehen, die durch , (Komma) getrennt sind, zum Beispiel: `1,4,13-20`. Jeder Teil kann das folgende Format haben:

- eine einzelne ID-Nummer, z. B. _12_
- ein Bereich von ID-Nummern, z. B. _1-100_
- _*_ (wählt alle IDs aus)

Wenn IDs mehrmals angeben werden, z.B. in "3, 1-10", enthält die resultierende ID-Menge jede ID nur einmal.


:xrefstyle: basic
