# Tutorials

ToDo Andreas Name NANDRAD oder SIM-VICUS ??? 

[NOTE]
====

ghfxxghxhgff

====

[[SingleRoomModel]]
## Einfaches Ein-Raum-Modell

### Einleitung

In diesem Beispiel wird nur eine thermische Zone modelliert. Das Hauptaugenmerk wird auf die Geometrie-, Material- und Konstruktionserstellung gelegt. Als Ergebnisgröße wird die Temperatur des frei schwingenden Raumes ausgegeben. Die Abmessungen des Raumes betragen `l = 2.0 m` Länge, `b = 5.0 m` Breite und `h = 3.0 m` Höhe. Daraus ergibt sich ein Luftvolumen von `V = 30.0 m³`. Alle weiteren Kennwerte werden im Tutorial spezifiziert.

BILD

### Ablauf

Als erstes werden die Materialien `Materials` und die verwendeten Konstruktionen `ConstructionTypes` definiert, die für die zu modellierende Zone in `Zones` spezifiziert werden. Anschließend werden die Hüllflächen sogenannte `ConstructionInstances` parametrisiert und die Ausgabeparameter `Outputs` gesetzt. Als letztes wird das Klima mit `Location` und weitere Einstellungen `SimulationParameter` ausgeführt.

### Materialien und Konstruktionen

Das Gebäude besteht aus einer Bodenplatten-, einer Wand- und einer Dachkonstruktion. Die Aufbauten sind in folgender Abbildung dargestellt.

.Material und Konstruktionsdaten
[width="100%", cols="<.^,^,^,^,^,^",options="header"]
|====================
| Name | Id | Dicke [m] | &lambda; [W/mK]  | &rho; [kg/m³] | ce [J/kgK] 
| *Bodenplatte* |103 4+|
| Beton | 1001 | 0.20 | 2.3 | 2000 | 1000 
| Dämmung | 1004 | 0.05 | 0.04 | 50 | 1500
6+|
| *Dach* | 102 4+|
| Dämmung | 1004 | 0.20 | 0.04 | 50 | 1500
| Holz | 1002 | 0.05 | 0.17 | 500 | 2100 
|  |  |  |  |  |
| *Wand* | 101 4+|
| Beton | 1001 | 0.20 | 2.3 | 2000 | 1000 
| Dämmung | 1004 | 0.10 | 0.04 | 50 | 1500
|====================

#### Materialien

Für die Materialien sind die thermischen Parameter `Wärmeleitfähigkeit` `&lambda;`, `Dichte` `&rho;` und  `Wärmekapazität` `ce` wichtig. Weiterhin wird eine unique-Id und Name benötigt. Beispielhaft wird die Beschreibung für Beton und Dämmung vorgenommen. Die detaillierte Dokumentation ist <<NANDRAD-Databases.adoc#MaterialsDocumentation,Materials>> beschrieben

.Materialbeschreibung
====
[source,xml]
----
<Materials>
	<Material id="1001" displayName="Concrete">
		<IBK:Parameter name="Density" unit="kg/m3">2000</IBK:Parameter>
		<IBK:Parameter name="HeatCapacity" unit="J/kgK">1000</IBK:Parameter>
		<IBK:Parameter name="Conductivity" unit="W/mK">2.3</IBK:Parameter>
	</Material>
	<Material id="1004" displayName="Insulation">
		<IBK:Parameter name="Density" unit="kg/m3">50</IBK:Parameter>
		<IBK:Parameter name="HeatCapacity" unit="J/kgK">1500</IBK:Parameter>
		<IBK:Parameter name="Conductivity" unit="W/mK">0.04</IBK:Parameter>
	</Material>
</Materials>
----
====

[TIP]
====
ToDo hygrische Parameter ausführen
====


#### Konstruktionen

Anschließend werden die <<NANDRAD-Databases.adoc#ConstructionTypesDocumentation,Konstruktionen>> in `ConstructionTypes` aus den Materialien über die Ids und der Schichtdicken `d` zusammengesetzt. Wie auch bei den Materialien wird einer Konstruktion immer eine eindeutige Id und optional ein Name zugewiesen. Übergangseigenschaften und weitere Parameter sind nicht Bestandteil der Konstruktion und werden in den `ConstructionInstances` definiert. Für die spätere Verwendung in der `ConstructionInstance` wird die erste Materialschicht mit dem `InterfaceA` und die letzte Materialschicht mit dem `InterfaceB` verknüpft. Dadurch kann die Innen- bzw. Außenseite der Konstruktion individuell festgelegt werden.

Beispielhaft wird die Wandkonstruktion dargestellt. 

.Konstruktionsbeschreibung
====
[source,xml]
----
<ConstructionTypes>
	<ConstructionType id="101" displayName="Wall Construction">
		<MaterialLayers>
			<MaterialLayer thickness="0.2" matId="1001" /> <!-- Linked to InterfaceA -->
			<MaterialLayer thickness="0.1" matId="1004" /> <!-- Linked to InterfaceB -->
		</MaterialLayers>
	</ConstructionType>
</ConstructionTypes>
----
====

### Zone

In diesem Bereich werden die Zone und deren Eigenschaften definiert. Geometrisch bildet die Zone das Raumluftvolumen ab. Alle weiteren geometrischen Eigenschaften werden in den `ConstructionInstances` definiert. Neben dem Volumen `Volume` wird eine Fläche `Area` angegeben, die zur Umrechnung der Flächenlasten auf spezifische Raumlasten benötigt wird. Diese Raumlasten werden in diesem Tutorial nicht beschrieben. 
Die Eindeutigkeit der Zone wird über eine Id `id` gewährleistet. Optional kann wieder ein Name `displayName` vergeben werden. Der Typ `type` der Zone stellt den Berechnungsmodus für die Zone ein. Dabei werden drei Typen unterschieden:

* `Active` Die Zone wird vom Solver über die Energiebilanzgleichungen gelöst und es stellt sich eine Raumlufttemperatur aus den Gewinnen und Verlusten aller Energieströme ein.
* `Constant` Die Zone wird durch eine vorgegebene Temperatur definiert. Dabei kann die Definition über einen Zeitplan erfolgen, welcher nicht konstant sein muss.
* `Ground` Die Bodentemperaturen aus der Vorgabeklimadatei werden für die Raumlufttemperatur angesetzt. Die Zone repräsentiert damit das anliegende Erdreich.

Das Volumen und die Fläche werden über sogenannte <<NANDRAD-Misc.adoc#IBK_ParameterDocumentation,`IBK:Parameter`>> definiert. 
Das Zonenvolumen ist im Beispielraum mit `V = 30 m³` vorgeben. Die Grundfläche wird mit `A = 10 m²` beschrieben. 

Example:
[source,xml]
----
<Zones>
	<Zone id="1" displayName="Single room model" type="Active">
		<IBK:Parameter name="Area" unit="m2">10</IBK:Parameter>
		<IBK:Parameter name="Volume" unit="m3">30</IBK:Parameter>
	</Zone>
</Zones>
----

Weitere Einstellungsmöglichkeiten finden sich in der <<NANDRAD-Geometry.adoc#ZoneDocumentation,detaillierte Zonendokumentation>>.

### Hüllflächen

Die Hüllflächen werden in die `ConstructionInstances` beschrieben. Jede Hüllfläche `ConstructionInstance` wird über eine Id `id`, optional einen Namen `displayName`, eine Fläche, eine Konstruktion, eine Ausrichtung sowie Übergangsbedingungen, die durch verschiedene Modelle repräsentiert werden, abgebildet.
Die Fläche und Ausrichtung, die nur bei Außenhüllflächen benötigt wird, werden über `IBK:Parameter` mit den Attributen `Area`, `Inclination` und `Orientation` beschrieben. Die Konstruktion wird über die `ConstructionTypeId` mit der Konstruktion aus `ConstructionTypes` verlinkt. 
Die Randbedingungen werden über die Interfaces `InterfaceA` und `InterfaceB` definiert. Als Randbedingungen werden Übergangskoeffizienten und solare oder thermische Absorptionskennwerte definiert. Diese sind jeweils durch ein eigenes Modell beschrieben.

Im Beispiel wird die Wandhüllfläche dargestellt. Die ausgewählte Wand wird durch eine Fläche `A = 15 m²`, einer Wandkonstruktion mit der `id = 101` und einer Innen- und Außenrandbedingung definiert. Die Außenrandbedingung wird mit einem konstanten Übergangskoeffizienten von `h = 15 W/(m²K)`, einer solaren Absorptanz von `a = 0.6` sowie einer langwelligen Absorption/Emission von `&epsilon; = 0.9` beschrieben. Auf der Innenseite wird nur ein Übergangskoeffizient `h = 10 W/(m²K)` beschrieben. Die Ausrichtung beträgt `90°` (senkrechte Wand) Neigung und `270°` (orientiert nach Westen) Orientierung. 


Weitere Einstellungsmöglichkeiten finden sich in der detaillierten<<NANDRAD-Geometry.adoc#ZoneDocumentation, ConstructionInstance documentation>>.

Example:
[source,xml]
----
<ConstructionInstances>
	<ConstructionInstance id="1" displayName="West Wall">
		<ConstructionTypeId>101</ConstructionTypeId>
		<IBK:Parameter name="Area" unit="m2">15</IBK:Parameter>
		<IBK:Parameter name="Orientation" unit="Deg">270</IBK:Parameter>
		<IBK:Parameter name="Inclination" unit="Deg">90</IBK:Parameter>
		<InterfaceA id="10" zoneId="1">
			<!--Interface to zone 'Single room model' -->
			<InterfaceHeatConduction modelType="Constant">
				<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">10</IBK:Parameter>
			</InterfaceHeatConduction>
		</InterfaceA>
		<InterfaceB id="11" zoneId="0">
			<!--Interface to outside-->
			<InterfaceHeatConduction modelType="Constant">
				<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">15</IBK:Parameter>
			</InterfaceHeatConduction>
			<InterfaceSolarAbsorption modelType="Constant">
				<IBK:Parameter name="AbsorptionCoefficient" unit="---">0.6</IBK:Parameter>
			</InterfaceHeatConduction>
			<InterfaceLongWaveEmission modelType="Constant">
				<IBK:Parameter name="Emissivity" unit="---">0.9</IBK:Parameter>
			</InterfaceHeatConduction>
		</InterfaceB>
	</ConstructionInstance>
</ConstructionInstances>
---- 

### Ausgaben

Die gewünschten Ausgaben müssen definiert werden, anderenfalls wird eine Simulation gestartet ohne ausgegebene Ergebnisgrößen zu erhalten. Die Ausgaben `Outputs` gliedern sich in `Definitions` und `Grids`. In den `Grids` werden die Intervalgrößen und optional die Zeitpunkte für die Ausgabe festgelegt. Die `Definitions` bestehen aus einzelnen Ausgaben `OutputDefinition` mit einem Name einer Objektliste `ObjectListName`, einem Ausgaberasternamen `GridName` und einer Ergebnisgröße `Quantity`. Zusätzlich kann die Intervalbehandlung `timeType` und der Ausgabedateiname `Filename` angegeben werden. In der Intervalbehandlung werden entweder Momentanwerte zum Intervalende, Mittel- oder Integralwerte des Intervals ausgegeben. In einer separaten Diskussion werden die <<Intervalbehandlungen>> genauer beschrieben.

Die Objektliste gruppiert alle Objekt-Ids, über welche auf die Objekte wie Zonen, Modelle, etc. selbst zugegriffen werden kann. Die Objektliste `ÒbjectList` besteht aus einer `FilterId`, einem `ReferenceType` und einem Namen `name`. Über einen `*` können alle vorhanden Ids einer Referenztyps adressiert werden.
Im vorliegende Beispiel wird gezeigt, wie die Ausgaben der Modelle über die Objektliste referenziert werden.

Example:
[source,xml]
----
<ObjectLists>
	<ObjectList name="Zone">
		<FilterID>*</FilterID>
		<ReferenceType>Zone</ReferenceType>
	</ObjectList>
</ObjectLists>
----

Im nachfolgenden Beispiel wird die Lufttemperatur abgefragt und in die <<Standardausgabedatei>> geschrieben. Als Interval wurde ein Stundenzeitraster gewählt. Die Ausgabe erfolgt über die gesamte <<SimulationPeriod, Simulationsdauer>>.

Example:
[source,xml]
----
<Outputs>
	<OutputDefinitions>
		<OutputDefinition>
			<Quantity>AirTemperature</Quantity>
			<ObjectListName>Zone</ObjectListName>
			<GridName>hourly</GridName>
		</OutputDefinition>
	</OutputDefinitions>
	<Grids>
		<OutputGrid name="hourly">
			<Intervals>
				<Interval>
					<IBK:Parameter name="StepSize" unit="h">1</IBK:Parameter>
				</Interval>
			</Intervals>
		</OutputGrid>
	</Grids>
</Outputs>
----

### Location

Der Standort und das Klima werden im Tag `Location` beschrieben. Pflichtparameter sind der Albedo als `IBK:Parameter` und entweder eine Klimadatei `ClimateFileName` oder eine Standortbeschreibung mit den `IBK:Parameter` nördliche Breite `Latitude`, östlicher Länge `Longitude` sowie der Höhe über Normalnull `Elevation`.

[NOTE]
====
*TODO* beschreiben was bei fehlender Klimadatei angesetzt wird.
====


[[SimulationPeriod]]
### Simulationsparameter

In den Simulationsparameter werden allgemeine Einstellungen für die Projektdatei gesetzt. Darunter das Startjahr `StartYear` für die Simulation als auch die Initialtemperature `InitialTemperature` aller Modelle. Ein Liste der vollständigen Elemente von Simulationsparameter und deren Datentypen wird unter <<SimulationParameter>> beschrieben. Im Beispiel wird nur die Initialtemperatur und das Startjahr dargestellt.

Example:
[source,xml]
----
<SimulationParameter>
	<IBK:Parameter name="InitialTemperature" unit="C">5</IBK:Parameter>
	<IBK:IntPara name="StartYear">2021</IBK:IntPara>
</SimulationParameter>
----

### Vollständiges Beispiel

Nachfolgende wird die komplette Projektdatei für das einfache Ein-Raum-Modell dargestellt:

Example:
[source,xml]
----
<?xml version="1.0" encoding="UTF-8" ?>
<NandradProject fileVersion="2">
	<Project>
		<ProjectInfo>
			<Comment>Simple Single Zone Model</Comment>
		</ProjectInfo>
		<Location>
			<IBK:Parameter name="Albedo" unit="---">0.2</IBK:Parameter>
			<ClimateFileName>${Project Directory}/../climate/TF05_PotsdamWithStartPhase.c6b</ClimateFileName>
		</Location>
		<SimulationParameter>
			<IBK:Parameter name="InitialTemperature" unit="C">5</IBK:Parameter>
		</SimulationParameter>
		<SolverParameter/>
		<Zones>
			<Zone id="1" displayName="Single Room" type="Active">
				<IBK:Parameter name="Area" unit="m2">10</IBK:Parameter>
				<IBK:Parameter name="Volume" unit="m3">30</IBK:Parameter>
			</Zone>
		</Zones>
		<ConstructionInstances>
        	<ConstructionInstance id="1" displayName="West Wall">
        		<ConstructionTypeId>101</ConstructionTypeId>
        		<IBK:Parameter name="Area" unit="m2">15</IBK:Parameter>
        		<IBK:Parameter name="Orientation" unit="Deg">270</IBK:Parameter>
        		<IBK:Parameter name="Inclination" unit="Deg">90</IBK:Parameter>
        		<InterfaceA id="10" zoneId="1">
        			<!--Interface to zone 'Single room model' -->
        			<InterfaceHeatConduction modelType="Constant">
        				<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">10</IBK:Parameter>
        			</InterfaceHeatConduction>
        		</InterfaceA>
        		<InterfaceB id="11" zoneId="0">
        			<!--Interface to outside-->
        			<InterfaceHeatConduction modelType="Constant">
        				<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">15</IBK:Parameter>
        			</InterfaceHeatConduction>
        			<InterfaceSolarAbsorption modelType="Constant">
        				<IBK:Parameter name="AbsorptionCoefficient" unit="---">0.6</IBK:Parameter>
        			</InterfaceHeatConduction>
        			<InterfaceLongWaveEmission modelType="Constant">
        				<IBK:Parameter name="Emissivity" unit="---">0.9</IBK:Parameter>
        			</InterfaceHeatConduction>
        		</InterfaceB>
        	</ConstructionInstance>
        	<ConstructionInstance id="2" displayName="North Wall">
        		<ConstructionTypeId>101</ConstructionTypeId>
        		<IBK:Parameter name="Area" unit="m2">6</IBK:Parameter>
        		<IBK:Parameter name="Orientation" unit="Deg">0</IBK:Parameter>
        		<IBK:Parameter name="Inclination" unit="Deg">90</IBK:Parameter>
        		<InterfaceA id="20" zoneId="1">
        			<!--Interface to zone 'Single room model' -->
        			<InterfaceHeatConduction modelType="Constant">
        				<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">10</IBK:Parameter>
        			</InterfaceHeatConduction>
        		</InterfaceA>
        		<InterfaceB id="21" zoneId="0">
        			<!--Interface to outside-->
        			<InterfaceHeatConduction modelType="Constant">
        				<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">15</IBK:Parameter>
        			</InterfaceHeatConduction>
        			<InterfaceSolarAbsorption modelType="Constant">
        				<IBK:Parameter name="AbsorptionCoefficient" unit="---">0.6</IBK:Parameter>
        			</InterfaceHeatConduction>
        			<InterfaceLongWaveEmission modelType="Constant">
        				<IBK:Parameter name="Emissivity" unit="---">0.9</IBK:Parameter>
        			</InterfaceHeatConduction>
        		</InterfaceB>
        	</ConstructionInstance>
        	<ConstructionInstance id="3" displayName="East Wall">
        		<ConstructionTypeId>101</ConstructionTypeId>
        		<IBK:Parameter name="Area" unit="m2">15</IBK:Parameter>
        		<IBK:Parameter name="Orientation" unit="Deg">270</IBK:Parameter>
        		<IBK:Parameter name="Inclination" unit="Deg">90</IBK:Parameter>
        		<InterfaceA id="30" zoneId="1">
        			<!--Interface to zone 'Single room model' -->
        			<InterfaceHeatConduction modelType="Constant">
        				<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">10</IBK:Parameter>
        			</InterfaceHeatConduction>
        		</InterfaceA>
        		<InterfaceB id="31" zoneId="0">
        			<!--Interface to outside-->
        			<InterfaceHeatConduction modelType="Constant">
        				<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">15</IBK:Parameter>
        			</InterfaceHeatConduction>
        			<InterfaceSolarAbsorption modelType="Constant">
        				<IBK:Parameter name="AbsorptionCoefficient" unit="---">0.6</IBK:Parameter>
        			</InterfaceHeatConduction>
        			<InterfaceLongWaveEmission modelType="Constant">
        				<IBK:Parameter name="Emissivity" unit="---">0.9</IBK:Parameter>
        			</InterfaceHeatConduction>
        		</InterfaceB>
        	</ConstructionInstance>
        	<ConstructionInstance id="4" displayName="South Wall">
        		<ConstructionTypeId>101</ConstructionTypeId>
        		<IBK:Parameter name="Area" unit="m2">6</IBK:Parameter>
        		<IBK:Parameter name="Orientation" unit="Deg">180</IBK:Parameter>
        		<IBK:Parameter name="Inclination" unit="Deg">90</IBK:Parameter>
        		<InterfaceA id="40" zoneId="1">
        			<!--Interface to zone 'Single room model' -->
        			<InterfaceHeatConduction modelType="Constant">
        				<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">10</IBK:Parameter>
        			</InterfaceHeatConduction>
        		</InterfaceA>
        		<InterfaceB id="41" zoneId="0">
        			<!--Interface to outside-->
        			<InterfaceHeatConduction modelType="Constant">
        				<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">15</IBK:Parameter>
        			</InterfaceHeatConduction>
        			<InterfaceSolarAbsorption modelType="Constant">
        				<IBK:Parameter name="AbsorptionCoefficient" unit="---">0.6</IBK:Parameter>
        			</InterfaceHeatConduction>
        			<InterfaceLongWaveEmission modelType="Constant">
        				<IBK:Parameter name="Emissivity" unit="---">0.9</IBK:Parameter>
        			</InterfaceHeatConduction>
        		</InterfaceB>
        	</ConstructionInstance>
        	<ConstructionInstance id="5" displayName="Roof">
        		<ConstructionTypeId>102</ConstructionTypeId>
        		<IBK:Parameter name="Area" unit="m2">10</IBK:Parameter>
        		<IBK:Parameter name="Orientation" unit="Deg">0</IBK:Parameter>
        		<IBK:Parameter name="Inclination" unit="Deg">0</IBK:Parameter>
        		<InterfaceA id="50" zoneId="1">
        			<!--Interface to zone 'Single room model' -->
        			<InterfaceHeatConduction modelType="Constant">
        				<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">10</IBK:Parameter>
        			</InterfaceHeatConduction>
        		</InterfaceA>
        		<InterfaceB id="51" zoneId="0">
        			<!--Interface to outside-->
        			<InterfaceHeatConduction modelType="Constant">
        				<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">15</IBK:Parameter>
        			</InterfaceHeatConduction>
        			<InterfaceSolarAbsorption modelType="Constant">
        				<IBK:Parameter name="AbsorptionCoefficient" unit="---">0.6</IBK:Parameter>
        			</InterfaceHeatConduction>
        			<InterfaceLongWaveEmission modelType="Constant">
        				<IBK:Parameter name="Emissivity" unit="---">0.9</IBK:Parameter>
        			</InterfaceHeatConduction>
        		</InterfaceB>
        	</ConstructionInstance>
        	<ConstructionInstance id="6" displayName="Ground Floor">
        		<ConstructionTypeId>103</ConstructionTypeId>
        		<IBK:Parameter name="Area" unit="m2">10</IBK:Parameter>
        		<IBK:Parameter name="Orientation" unit="Deg">0</IBK:Parameter>
        		<IBK:Parameter name="Inclination" unit="Deg">180</IBK:Parameter>
        		<InterfaceA id="60" zoneId="1">
        			<!--Interface to zone 'Single room model' -->
        			<InterfaceHeatConduction modelType="Constant">
        				<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">10</IBK:Parameter>
        			</InterfaceHeatConduction>
        		</InterfaceA>
        		<InterfaceB id="61" zoneId="0">
        			<!--Interface to outside-->
        			<InterfaceHeatConduction modelType="Constant">
        				<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">15</IBK:Parameter>
        			</InterfaceHeatConduction>
        			<InterfaceSolarAbsorption modelType="Constant">
        				<IBK:Parameter name="AbsorptionCoefficient" unit="---">0.6</IBK:Parameter>
        			</InterfaceHeatConduction>
        			<InterfaceLongWaveEmission modelType="Constant">
        				<IBK:Parameter name="Emissivity" unit="---">0.9</IBK:Parameter>
        			</InterfaceHeatConduction>
        		</InterfaceB>
        	</ConstructionInstance>
		</ConstructionInstances>
		<ConstructionTypes>
        	<ConstructionType id="101" displayName="Wall Construction">
        		<MaterialLayers>
        			<MaterialLayer thickness="0.2" matId="1001" /> <!-- Linked to InterfaceA -->
        			<MaterialLayer thickness="0.1" matId="1004" /> <!-- Linked to InterfaceB -->
        		</MaterialLayers>
        	</ConstructionType>
        	<ConstructionType id="102" displayName="Roof Construction">
        		<MaterialLayers>
        			<MaterialLayer thickness="0.2" matId="1004" /> <!-- Linked to InterfaceA -->
        			<MaterialLayer thickness="0.05" matId="1002" /> <!-- Linked to InterfaceB -->
        		</MaterialLayers>
        	</ConstructionType>
        	<ConstructionType id="103" displayName="Ground Floor Construction">
        		<MaterialLayers>
        			<MaterialLayer thickness="0.2" matId="1001" /> <!-- Linked to InterfaceA -->
        			<MaterialLayer thickness="0.05" matId="1004" /> <!-- Linked to InterfaceB -->
        		</MaterialLayers>
        	</ConstructionType>
		</ConstructionTypes>
		<Materials>
			<Material id="1001" displayName="Concrete">
				<IBK:Parameter name="Density" unit="kg/m3">2000</IBK:Parameter>
				<IBK:Parameter name="HeatCapacity" unit="J/kgK">1000</IBK:Parameter>
				<IBK:Parameter name="Conductivity" unit="W/mK">1.2</IBK:Parameter>
			</Material>
			<Material id="1002" displayName="Spruce">
				<IBK:Parameter name="Density" unit="kg/m3">500</IBK:Parameter>
				<IBK:Parameter name="HeatCapacity" unit="J/kgK">2100</IBK:Parameter>
				<IBK:Parameter name="Conductivity" unit="W/mK">500</IBK:Parameter>
			</Material>
			<Material id="1004" displayName="Insulation">
				<IBK:Parameter name="Density" unit="kg/m3">50</IBK:Parameter>
				<IBK:Parameter name="HeatCapacity" unit="J/kgK">1000</IBK:Parameter>
				<IBK:Parameter name="Conductivity" unit="W/mK">0.02</IBK:Parameter>
			</Material>
		</Materials>
		<Outputs>
			<OutputDefinitions>
				<OutputDefinition>
					<Quantity>AirTemperature</Quantity>
					<ObjectListName>Zone</ObjectListName>
					<GridName>hourly</GridName>
				</OutputDefinition>
			</OutputDefinitions>
			<Grids>
				<OutputGrid name="hourly">
					<Intervals>
						<Interval>
							<IBK:Parameter name="StepSize" unit="h">1</IBK:Parameter>
						</Interval>
					</Intervals>
				</OutputGrid>
			</Grids>
		</Outputs>
		<ObjectLists>
			<ObjectList name="Zone">
				<FilterID>*</FilterID>
				<ReferenceType>Zone</ReferenceType>
			</ObjectList>
		</ObjectLists>
	</Project>
</NandradProject>
----

## Zwei-Raum-Modell

### Einleitung

Nachdem den Grundlagen vom <<SingleRoomModel,Ein-Raum-Modell>> werden jetzt folgende Schwerpunkte angesetzt:

* Multizonen-Modell bestehend aus zwei Räumen
* Integration eines einfachen Fenster in opake Oberfläche
* Erstellung und Funktionsweise von Zeitplänen anhand eines Lüftungsmodells

### Ablauf

Als erstes wird der im <<SingleRoomModel,Ein-Raum-Modell>> beschriebene Raum um einen gleichengroßen Raum erweitert. Dabei wird die Westwand in eine Innenwand umgewandelt. Anschließend wird dem ersten Raum in der Südwand ein Fenster integriert. Zuletzt werden Lüftungsmodelle mit verschiedenen Zeitstrategien den beiden Räumen zugewiesen.

### Erweiterung zweiter Raum

Der neu zu erstellende Raum hat die gleichen Abmessungen wie im <<SingleRoomModel,Ein-Raum-Modell>>. Dabei wird die Westwand des bestehenden Raumes als Innenwand verbaut. Dadurch ändern sich die Randbedingungen (Übergangskoeffizienten). Die Material und Konstruktionsaufbauen bleiben gleich zum bestehenden Raum. Es werden als fünf weitere Hüllflächen (Wand: Süd, Ost, Nord; sowie Dach und Boden) hinzukommen. Hinzugefügt wird in der Projektdatei eine weitere Zone `zone` sowie die fünf `ConstructionInstance`. 

PICTURE

Im folgenden Beispiel sieht man die zweite Zone mit der Id `id="2"`. Der Name `displayName` des bestehenden wurde in "Room A" abgeändert

Example:
[source,xml]
----
<Zones>
	<Zone id="1" displayName="Room A" type="Active">
		<IBK:Parameter name="Area" unit="m2">10</IBK:Parameter>
		<IBK:Parameter name="Volume" unit="m3">30</IBK:Parameter>
	</Zone>
	<Zone id="2" displayName="Room B" type="Active">
		<IBK:Parameter name="Area" unit="m2">10</IBK:Parameter>
		<IBK:Parameter name="Volume" unit="m3">30</IBK:Parameter>
	</Zone>
</Zones>
----

Folgende `ConstructionInstance` kommen hinzu:

Example:
[source,xml]
----
<ConstructionInstance id="7" displayName="North Wall">
	<ConstructionTypeId>101</ConstructionTypeId>
	<IBK:Parameter name="Area" unit="m2">6</IBK:Parameter>
	<IBK:Parameter name="Orientation" unit="Deg">0</IBK:Parameter>
	<IBK:Parameter name="Inclination" unit="Deg">90</IBK:Parameter>
	<InterfaceA id="70" zoneId="2">
		<!--Interface to zone 'Single room model' -->
		<InterfaceHeatConduction modelType="Constant">
			<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">10</IBK:Parameter>
		</InterfaceHeatConduction>
	</InterfaceA>
	<InterfaceB id="71" zoneId="0">
		<!--Interface to outside-->
		<InterfaceHeatConduction modelType="Constant">
			<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">15</IBK:Parameter>
		</InterfaceHeatConduction>
		<InterfaceSolarAbsorption modelType="Constant">
			<IBK:Parameter name="AbsorptionCoefficient" unit="---">0.6</IBK:Parameter>
		</InterfaceHeatConduction>
		<InterfaceLongWaveEmission modelType="Constant">
			<IBK:Parameter name="Emissivity" unit="---">0.9</IBK:Parameter>
		</InterfaceHeatConduction>
	</InterfaceB>
</ConstructionInstance>
<ConstructionInstance id="8" displayName="East Wall">
	<ConstructionTypeId>101</ConstructionTypeId>
	<IBK:Parameter name="Area" unit="m2">15</IBK:Parameter>
	<IBK:Parameter name="Orientation" unit="Deg">270</IBK:Parameter>
	<IBK:Parameter name="Inclination" unit="Deg">90</IBK:Parameter>
	<InterfaceA id="80" zoneId="2">
		<!--Interface to zone 'Single room model' -->
		<InterfaceHeatConduction modelType="Constant">
			<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">10</IBK:Parameter>
		</InterfaceHeatConduction>
	</InterfaceA>
	<InterfaceB id="81" zoneId="0">
		<!--Interface to outside-->
		<InterfaceHeatConduction modelType="Constant">
			<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">15</IBK:Parameter>
		</InterfaceHeatConduction>
		<InterfaceSolarAbsorption modelType="Constant">
			<IBK:Parameter name="AbsorptionCoefficient" unit="---">0.6</IBK:Parameter>
		</InterfaceHeatConduction>
		<InterfaceLongWaveEmission modelType="Constant">
			<IBK:Parameter name="Emissivity" unit="---">0.9</IBK:Parameter>
		</InterfaceHeatConduction>
	</InterfaceB>
</ConstructionInstance>
<ConstructionInstance id="9" displayName="South Wall">
	<ConstructionTypeId>101</ConstructionTypeId>
	<IBK:Parameter name="Area" unit="m2">6</IBK:Parameter>
	<IBK:Parameter name="Orientation" unit="Deg">180</IBK:Parameter>
	<IBK:Parameter name="Inclination" unit="Deg">90</IBK:Parameter>
	<InterfaceA id="90" zoneId="2">
		<!--Interface to zone 'Single room model' -->
		<InterfaceHeatConduction modelType="Constant">
			<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">10</IBK:Parameter>
		</InterfaceHeatConduction>
	</InterfaceA>
	<InterfaceB id="91" zoneId="0">
		<!--Interface to outside-->
		<InterfaceHeatConduction modelType="Constant">
			<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">15</IBK:Parameter>
		</InterfaceHeatConduction>
		<InterfaceSolarAbsorption modelType="Constant">
			<IBK:Parameter name="AbsorptionCoefficient" unit="---">0.6</IBK:Parameter>
		</InterfaceHeatConduction>
		<InterfaceLongWaveEmission modelType="Constant">
			<IBK:Parameter name="Emissivity" unit="---">0.9</IBK:Parameter>
		</InterfaceHeatConduction>
	</InterfaceB>
</ConstructionInstance>
<ConstructionInstance id="10" displayName="Roof">
	<ConstructionTypeId>102</ConstructionTypeId>
	<IBK:Parameter name="Area" unit="m2">10</IBK:Parameter>
	<IBK:Parameter name="Orientation" unit="Deg">0</IBK:Parameter>
	<IBK:Parameter name="Inclination" unit="Deg">0</IBK:Parameter>
	<InterfaceA id="100" zoneId="2">
		<!--Interface to zone 'Single room model' -->
		<InterfaceHeatConduction modelType="Constant">
			<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">10</IBK:Parameter>
		</InterfaceHeatConduction>
	</InterfaceA>
	<InterfaceB id="101" zoneId="0">
		<!--Interface to outside-->
		<InterfaceHeatConduction modelType="Constant">
			<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">15</IBK:Parameter>
		</InterfaceHeatConduction>
		<InterfaceSolarAbsorption modelType="Constant">
			<IBK:Parameter name="AbsorptionCoefficient" unit="---">0.6</IBK:Parameter>
		</InterfaceHeatConduction>
		<InterfaceLongWaveEmission modelType="Constant">
			<IBK:Parameter name="Emissivity" unit="---">0.9</IBK:Parameter>
		</InterfaceHeatConduction>
	</InterfaceB>
</ConstructionInstance>
<ConstructionInstance id="11" displayName="Ground Floor">
	<ConstructionTypeId>103</ConstructionTypeId>
	<IBK:Parameter name="Area" unit="m2">10</IBK:Parameter>
	<IBK:Parameter name="Orientation" unit="Deg">0</IBK:Parameter>
	<IBK:Parameter name="Inclination" unit="Deg">180</IBK:Parameter>
	<InterfaceA id="110" zoneId="2">
		<!--Interface to zone 'Single room model' -->
		<InterfaceHeatConduction modelType="Constant">
			<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">10</IBK:Parameter>
		</InterfaceHeatConduction>
	</InterfaceA>
	<InterfaceB id="111" zoneId="0">
		<!--Interface to outside-->
		<InterfaceHeatConduction modelType="Constant">
			<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">15</IBK:Parameter>
		</InterfaceHeatConduction>
		<InterfaceSolarAbsorption modelType="Constant">
			<IBK:Parameter name="AbsorptionCoefficient" unit="---">0.6</IBK:Parameter>
		</InterfaceHeatConduction>
		<InterfaceLongWaveEmission modelType="Constant">
			<IBK:Parameter name="Emissivity" unit="---">0.9</IBK:Parameter>
		</InterfaceHeatConduction>
	</InterfaceB>
</ConstructionInstance>
----

Die Westwand von "Room A" wird von einer Außenwand in eine Innenwand umgewandelt. Die so erhaltene Innenwand soll nicht mit einer  Außenwandkonstruktion modelliert werden sondern mit einer neue eingeführten Innenwandkonstruktion. Diese besteht aus dem Material `Beton` und hat eine Dicke von `d = 20 cm`. Zudem wird die `ConstructionTypeId` 104 vergeben. Zu Beachten ist die Zuordnung bei den Interfaces über das Attribut `zoneId`. Dabei werden die Ids `zoneId="1"` für "Room A" und `zoneId="2"` für "Room B" vergeben. Der Übergangswiderstand wird auf beiden Seiten der Konstruktion zu `h = 10 W(m²K)` gewählt. Alle weitere Randbedingungsmodelle werden nicht benötigt und daher entfernt.

Example:
[source,xml]
----
<ConstructionInstance id="1" displayName="West Wall">
	<ConstructionTypeId>104</ConstructionTypeId>
	<IBK:Parameter name="Area" unit="m2">15</IBK:Parameter>
	<IBK:Parameter name="Orientation" unit="Deg">270</IBK:Parameter>
	<IBK:Parameter name="Inclination" unit="Deg">90</IBK:Parameter>
	<InterfaceA id="10" zoneId="1">
		<!--Interface to zone 'Single room model' -->
		<InterfaceHeatConduction modelType="Constant">
			<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">10</IBK:Parameter>
		</InterfaceHeatConduction>
	</InterfaceA>
	<InterfaceB id="11" zoneId="2">
		<!--Interface to outside-->
		<InterfaceHeatConduction modelType="Constant">
			<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">10</IBK:Parameter>
		</InterfaceHeatConduction>
	</InterfaceB>
</ConstructionInstance>
----

### Fenster Integration

In die bestehende Südwand von "Raum A" wird ein Fenster integriert. Einfache Fenstermodelle besitzen neben der Fläche `Area` zwei wichtige physikalische Parameter. Zum einen der U-Wert der Fensterverbundkonstruktion, bestehend aus Rahmen- und Glasanteil sowie den g-Wert `SHGC` (Solar Heat Gain Coefficient). Der g-Wert kann konstant über einen skalaren Wert beschrieben werden oder in Abhängigkeit des Winkels zwischen Sonnenstrahl und Fensternormale. Wenn möglich sollte der winkelabhängige g-Wert verwendet werden. Zum Einbetten in die Projektdatei wird die `ConstructionInstance` um das Objekt `EmbeddedWindow` erweitert.

[NOTE]
====
Prüfen ob die NAMEN stimmen!
====

### Zeitpläne

Für verschiedenste Modelle werden Zeitpläne verwendet. Diese haben die Aufgabe Sollwerte vorzugeben. Die Verwendung findet beispielsweise in folgenden Modellen statt:

* Belegungsraten, Wärmeabgaben, Bekleidungsfaktoren beim Personenlastmodell.
* Heiz-/Kühlsolltemperaturen für Thermostatsteuerungen
* Massestrom oder Temperaturbedingungen für Anlagenkomponenten
* elektrische Leistungsraten bei Licht- und elektrischen Gerätemodellen

Innerhalb der Projektdatei gibt es zwei mögliche Varianten einen Zeitplan zu beschreiben, entweder über die `ScheduleGroups` oder `AnnualSchedules`. Die beiden Möglichkeiten werden nachfolgend im Detail erörtert. Wichtig dabei ist das beide Methoden immer ein Jahr mit allen Tagen definieren müssen.

Example:
[source,xml]
----
<Schedules>
	<ScheduleGroups>
	    ...
	</ScheduleGroups>
	<AnnualSchedules>
	    ...
	</AnnualSchedules>
</Schedules>
----

#### ScheduleGroups

Für zyklische Simulationen werden in aller Regel wiederholende Zeitabschnitte verwendet. Beispielsweise wird ein Büroarbeitstag von Mo-Fr innerhalb einer Öffnungszeit von 7:00 bis 18:00 definiert. Außerhalb dieser Zeiten ist das Büro geschlossen. Dieser Zyklus wiederholt sich wöchtenlich und wird übers Jahr gesehen nur durch Feiertage bzw. besondere Schließtage unterbrochen. 

Ein Zeitplangruppe wird immer einer `objectList` zugeordnet. Über diese ist später eine Verlinkung bzw. Referenzierung möglich und die Zeitpläne können gemeinsam von mehrere Modellen genutzt werden.

Eine genauere Beschreibung der Funktionsweise wird am Beispiel der Heizsolltemperatur für das Büro mit den oben beschriebenen Öffnungszeiten definiert. Dabei wird innerhalb der Öffnungszeit eine Heizsolltemperatur von 21 °C gefordert und außerhalb wird eine Absenktemperatur von 17 °C eingestellt.

Example:
[source,xml]
----
<ScheduleGroups>
	<ScheduleGroup objectList="Office">
		<Schedule type="AllDays">
			<DailyCycles>
				<DailyCycle interpolation="Constant">
					<TimePoints>0</TimePoints>
					<Values>HeatSetpointTemperature [C]:17</Values>
				</DailyCycle>
			</DailyCycles>
		</Schedule>
		<Schedule type="WeekDay">
			<DailyCycles>
				<DailyCycle interpolation="Constant">
					<TimePoints>0 7 18</TimePoints>
					<Values>HeatSetpointTemperature [C]:17 21 17</Values>
				</DailyCycle>
			</DailyCycles>
		</Schedule>
	</ScheduleGroup>
</ScheduleGroups>
----

Da immer alle Tage des Jahres definiert sein müssen wird zuerst ein Zeitplan für alle Tage erstellt. Dieser `Schedule` wird durch den `type="AllDays"` (<<ScheduleTypes, siehe Referenz>>) gekennzeichnet. Innerhalb eines Zeitplan kann es einen oder mehrere `DailyCycle` geben. Diese Tageszyklen definieren die 24 Stunden eines Tages. Dabei werden zwei verschiedene Methode zu Interpolation angeboten `Constant` oder `Linear`. Der Unterschied zwischen konstanter oder linearer Interpolation ist in folgender <<InterpolationMethode, Abbildung>> dargestellt. Weiterhin werden Daten- und Zeitpunkte paarweise zugeordnet. Dazu werden die beiden Objekte `TimePoints` und  `Values` genutzt. Die Daten- als auch Zeitpunkte werden mit einem Leerzeichen getrennt. Die Einleitung bei den `Values` erfolgt durch ein Keyword mit zugehöriger Einheit. Für die Einheiten sind SI-Einheiten zugelassen. Bei verschiedenen Tageszyklen müssen die Einheiten eines Keywords konsistent bleiben. Die Einheit wird immer in eckige Klammer `[Unit]` eingebunden. Anschließend folgt ein Doppelpunkt `:` gefolgt von den Datenpunkten.

[[ScheduleTypes]]
.Beschreibung von Schedule `type`
[options="header"]
[cols=" ^, ^ "]
[width="40%"]
|====================
| Name of type | Priority
| AllDays | 0
| WeekEnd | 1
| WeekDay | 1
| Monday | 2
| Tuesday | 2
| Wednesday | 2
| Thursday | 2
| Friday | 2
| Saturday | 2
| Sunday | 2
| Holiday | 3
|====================

[NOTE]
====
Null bezeicht die niedrigste Priorität und drei die höchste.
====

Der zweite Zeitplan, oben im Beispiel, überschreibt aufgrund seines `type` mit `WeekDay` den oberen durchgehenden Zeitplan von constant 17 °C. Dadurch wird ein neuer Tageszyklus mit der Heizsolltemperatur 21 °C während der Zeit von 7:00 bis 18:00 Uhr dargestellt.

Bei verschiedenen Perioden im Jahr kann eine weiterer  `Schedule` hinzugefügt werden. Dabei ist müssen entweder `StartDayOfTheYear` oder/und `EndDayOfTheYear` angegeben werden. Tag `0` beschreibt dabei den 1.1. eines Jahres und Tag `364` den 31.12. des Jahres. `Schedule` mit Start- oder Endtagen überschreiben immer die eine `Schedule` ohne Start- und Endtag. 

[NOTE]
====
Ein `Schedule` darf nur den einen Zeitplan ohne Start- und Endtage überschreiben. Weiter Interaktionen von Zeitplänen-Objekten sind nicht erlaubt.
====

Als Beispiel wird nun eine Luftwechselrate für ein Jahr mit folgenden Eigenschaften definiert.

* Vom 1.10. bis zum 31.3. wird eine konstante Luftwechselrate von `ach = 0.5 1/h` definiert
* Vom 1.4. bis zum 30.9. wird tagesüber (6:00 bis 20:00) eine konstante Luftwechselrate von `ach = 0.5 1/h` und nachts eine konstante Luftwechselrate von `ach = 0.5 1/h` definiert.

Der Zeitplan referenziert die `objectList` "AirChangeRate".

.Luftwechselrate zeitlich dynamisch mit unterschiedlichen Perioden
====
[source,xml]
----
<ScheduleGroups>
	<ScheduleGroup objectList="AirChangeRate">
		<Schedule type="AllDays">
			<DailyCycles>
				<DailyCycle interpolation="Constant">
					<TimePoints>0</TimePoints>
					<Values>InfiltrationRateSchedule [1/h]:0.5</Values>
				</DailyCycle>
			</DailyCycles>
		</Schedule>
		<Schedule type="AllDays">
		    <StartDayOfTheYear>89</StartDayOfTheYear>
		    <EndDayOfTheYear>272</EndDayOfTheYear>
			<DailyCycles>
				<DailyCycle interpolation="Constant">
					<TimePoints>0 6 20</TimePoints>
					<Values>InfiltrationRateSchedule [1/h]:2 0.5 2</Values>
				</DailyCycle>
			</DailyCycles>
		</Schedule>
	</ScheduleGroup>
</ScheduleGroups>
----
====

[CAUTION]
====
ToDo ist das richtig Trennung Leerzeichen?
====

#### AnnualSchedules

Falls keine periodischen Beschreibung möglich sind können individuelle Zeitpunkte festgelegt werden. Dabei wird beschrieben wann sich welcher Wert einstellt.



Aufgrund der unterschiedlichen Aufgaben werden zu jeden Zeitplan individuelle Einheiten benötigt. Diese Werten beim Zeitplan nach dem Keyword angegeben.
