Entwicklungsroadmap IBK
=======================
Dirk Weiß <dirk.weiss@tu-dresden.de>, Stephan Hirth <stephan.hirth@tu-dresden.de>
v0.7 (09.01.2022)
// v0.7 date_on_line_above
:Author Initials: DW
:toc: left
:toclevels: 3
:toc-title: Inhaltsverzeichnis
:icons: font
:imagesdir: ./images
:numbered:
:website: https://wwww.tu-dresden.de/bauklimatik
:source-highlighter: rouge
:rouge-style: custom
:title-page:
:stylesdir: ../adoc_utils/css
:stylesheet: roboto_ubuntu.css
:tabsize: 2
:title-page:

:caution-caption: Achtung
:example-caption: Beispiel
:figure-caption: Abbildung
:table-caption: Tabelle
:section-refsig: Abschnitt


## Einleitung


Das Institut für Bauklimatik (IBK) entwickelt seit Jahrzehnten erfolgreich Softwareprodukte. Schwerpunkt bilden hierbei Programme für die (hygro-)thermische Berechnung & Analyse von Bauteilen, -konstruktionen sowie die energetische Bewertung von Räumen, Gebäuden und Quartieren. Im Laufe der Jahren sind verschiedenste Rechenkerne als auch Programme mit anwenderfreundlichen Oberflächen für Architekten und Ingenieure entstanden.

*Rechenkerne:*

* [underline]#DelphinSolver#
* [underline]#TheraklesSolver#
* [underline]#NandradSolver#

*Ingenieursprogramme:*

* [underline]#CCM-Editor# - Klimadatenauswertung und Modifikation
* [underline]#COND# - Analyse (Feuchteschutz) und Auslegung von Bauteilen mit Innen- und Außendämmung
* [underline]#DELPHIN# - Analyse und Auslegung von Bauteilen und 2D/3D Konstruktionsdetails. Hierbei können verschiedenste Szenarien wie beispielsweise Schlagregenbelastungen, Schimmelpilzwachstum, Wärmebrückenberechnung betrachtet werden. Zusätzlich kann DELPHIN das Erdreich abbbilden und damit Erdwärmekollektoren analysieren und auslegen.
* [underline]#THERAKLES# - Analyse und Bewertung von Raumklimabetrachtungen. Ermittlung von Heiz- bzw. Kühlbedarf, Raumluft- und Oberflächentemperaturen, Raumluftfeuchten, Behaglichkeitskennwerten.
* [underline]#POSTPROC 2# - Auswertungswerkzeug für die Be- und Verarbeitung von Ergebnisdaten aus DELPHIN, THERAKLES und NANDRAD.
* [underline]#MASTERSIM# - Werkzeug zur Kopplung und gemeinsamen Berechnung von verschiedenen Solversystemen. Anwendung findet hier die FMI-Technologie (CoSimulation).
* [underline]#SIM-VICUS# - 3D-Eingabemaske für den NANDRAD-Solver. (derzeit in Entwicklung)

Weiterhin sind Programme wie [underline]#PV-Tool# als auch der [underline]#Erdkollektordesigner# in letzter Zeit entstanden.

## Strategische Planung für das IBK

### Prioritäten

Für eine Wichtung der Aufgaben werden die Aufgabenpunkte mit einer Priorisierung versehen. Dabei steht 10 für die höchste Priorität und 1 für die niedrigste. Die Priorisierung wird direkt hinter dem jeweiligen Arbeitspunkt in Klammern notiert.

### Datenbanken

Die Datenbanken aller Programme müssen sukzessive erweitert werden. Speziell bei der Materialdatenbank muss mehr Austausch zwischen Labor und der Softwareentwicklungsabteilung erfolgen. Davon profitieren alle Programme.

> AN: differenzieren zwischen Materialdatenbank (COND, THERAKLES, DELPHIN, SIM-VICUS); Konstruktionsdatenbank (COND?, THERAKLES, SIM-VICUS); Verglasungen/Fenster (THERAKLES, SIM-VICUS); und den restlichen SIM-VICUS DBs

### Bauteilsimulation

Für die Ingenieure ist es für eine wirtschaftliche Bearbeitung essentiell, schnell und effektiv Aufgaben abzuarbeiten. Daher ist das effiziente Aufsetzen/Erstellen von Projekten als auch das schnelle Auswerten der Ergebnissdaten und letztlich die Erstellung von Berichten höchste Priorität.

*COND*

Keine Bedarfe in der Entwicklung.

*DELPHIN*

Das Aufsetzen von 3D-Simulationsdateien ist derzeit nicht mittels einer grafischen Nutzeroberfläche möglich. Das automatisierte Erstellen von Berichten ist ebenfalls wenig oder gar nicht möglich. Um Verbesserungen zu erzielen, müssten die Typszenarien aus der Ingenieurpraxis erstellt werden und in automatisierbare Berichte abgeleitet werden. Ebenso sind automatisierbare Templates, die über einen Wizard bestimmte Standardszenarien abbilden und parametrisierbar sind, notwendig.


Zusammenfassung:



* 3D Nutzeroberfläche DELPHIN (1)
* Automatisierte Berichterstellung (8)
* Wizard zur Erstellung von typischen Ingenierprojekten (8)
* Erweiterung der Innenklimamodelle (10)
* Schlagregen bei hinterlüfteten Fassaden (10)
* Tutorials und Nutzerhandbuch (9)

### Raum-, Gebäude und Quertiersimulationsprogramme

*THERAKLES*

Für THERAKLES müssen die Berichte vervollständigt werden.

* Berichterstellung vervollständigen (10)


*NANDRAD2-Solver*

Für die Abschätzung der Behaglichkeit in Räumen muss die Raumluftfeuchte und deren Speichereffekte in Bauteilen berechnet werden. Die Ansätze von NANDRAD 1.8 können dabei wahrscheinlich direkt portiert werden. Die Integration von Steuerungssystemen, wie die dynamische Verschattungssteuerung, müssen entwickelt und ausprogrammiert werden. Für die Abbildung von TGA-Systemen in Gebäuden müssen Luft- als auch hydraulische Netzwerke abbildbar sein.

Zusammenfassung:

* Abbildung der Raumluftfeuchte (2)
* Steuerungsmodelle 
+ 
> AN: **!Differenzieren!**, Regelungen wofür? Trennen nach thermischen Modellen/TGA und nach Regelungen, welche eine hygrothermische Luftbetrachtung verlangen.

*SIM-VICUS*

SIM-VICUS hat unter allen Programmen den größten Entwicklungsbedarf. Dies sollte für die zukünftige Abarbeitung von Projekten im Gebäude- als auch Quartierskontext unbedingt erweitert werden. Bei der Eingabe müssen der Import der IFC-Schnittstelle als auch der Import von Grundrissen im dwg und/oder dxf-Format implementiert werden. Da für zweiteres einige Open-Source-Bibliotheken exisitieren, sollte der Entwicklungsaufwand abschätzbar sein. Weiterhin wird die Erstellung und Bearbeitung von Geometriemodellen direkt in SIM-VICUS für Praxisprojekte benötigt. Dazu zählen die Funktionen Transformieren, Skalieren und Rotation (viele bugfixes durchgeführt, aber lokale Skalierung muss erweitert werden), sowie die Verschneidung von Flächen. Für die thermische Simulation mittels NANDRAD müssen die Partneroberflächen möglichst automatisiert gefunden, verschnitten und gekoppelt werden. Anschließend wird ein manuelles als auch automatisches Verlinken von Oberflächen zu einer sogenannten _Component_ benötigt. Um keine kaputten Polygone zu erzeugen, müssen Polygone zuerst von der derzeitigen 3D Datenstruktur in eine 2D Datenstruktur (VICUS-Format) überführt werden, die allerdings eine kompatible Rückwärtskonvertierung behält.

Ebenfalls müssen Wizards und Reports wie beispielsweise für die Kühllastberechnung nach VDI 2078 bzw. die Heizlastberechnung nach DIN EN ISO 12831 oder der sommerliche Wärmeschutz nach DIN 4108-2 erstellt werden. Zusätzlich müssen in einem Bericht alle Eingabedaten zusammengefasst werden.

Die Wizards und Berichte werden dabei nicht Open-Source veröffentlicht. Dafür ist eine Plugin-Struktur herzustellen. Durch Plugins kann zu einem späteren Zeitpunkt eine Vermarktung von SIM-VICUS erfolgen.

* IFC-Import (7)
* DXF/DWG-Import (3)
* Polygone auf 2D Abstraktion umbauen (10)
* Verschneidung (9)
* Verlinkung von Flächen (9)
* Geometrieoperationen erweitern (7)
* Infrastruktur für Datenbank-Plugins (5)
* Export-Funcktionen anpassen (5)
* Diverse Bugfixes (6)
* Wizard/Bericht DIN EN ISO 12831 - Heizlastberechnung (5)
* Wizard Bericht VDI 2078 - Kühllastberechnung (5)
* Wizard/Bericht DIN 4108-2 - sommerlicher Wärmeschutz (5)
* Bericht der Eingabedaten (5)



### Weitere Programme

*CCM-Editor*

Die Anbindung von Wetterdatenbanken ist für Ingenieure wichtig. Die Anbindung der Datenbanken one-building.org als auch die des DWD müssen dabei im Zentrum stehen. Diese Datenbanken können von allen Softwareprodukten SIM-VICUS/NANDRAD/Therakles/Delphin genutzt werden und zur Berechnung verwendet werden.

* One-Building Datenbakimport
* DWD-Importer


*POSTPROC 2*

Einige Anpassungen für die Auswertungen für Gebäude und Quartiersprojekte müssen umgesetzt werden. (1)

* Erstellung von Balkendiagrammen (2)
* Erstellung von Polardiagrammen (2)

> AN: hier wäre zu klären, inwieweit POSTPROC hier primär die Zielanwendung ist. Solange es datenseitig bei (t,x,v) und (t,x,y,v) bleibt, geht das alles. Bei Balkendiagrammen besteht noch die Frage nach einer automatischen Aggegrierung von Zeitreihendaten (Summenbildung/Integration, Interval-/Monatsbilanzen, Differenzen) und wie dieses mittels Manipulatoren umgesetzt werden kann. Daher noch zwei weitere Bausteine:

* Verbesserung der (nachträglichen) Konfiguration von Manipulatoren (4)
* Integration von Manipulatoren für übliche Datenaggregation (4)

*MASTERSIM*

* Einbau der Unterstützung für Ausgabe- / Eingabeinterpolation; wichtig für Kopplung von FMI-Regelmodellen mit SIM-VICUS/NANDRAD (Performancesteigerung von FMI-Co-Sim) (3)


*PV-Tool*

Keine Bedarfe


*Erdkollektordesigner*

Ausprogrammieren der 1D-Szenarien. Erstellen eines Auslegungsmodells für Bohrungen.


## Roadmap

Zeitlicher Horizont: Jetzt (Q1 2022) - Mitte 2023

Aufgaben bis jeweils Ende des Quartals:

### Q2/2022

-

### Q3/2022

-

### Q4/2022

-

### Q1/2023

-

### Q2/2023

-


