Entwicklungsroadmap IBK
=======================
Dirk Weiß <dirk.weiss@tu-dresden.de>
v0.7 (09.01.2022)
// v0.7 date_on_line_above
:Author Initials: DW
:toc: left
:toclevels: 3
:toc-title: Inhaltsverzeichnis
:icons: font
:imagesdir: ./images
:numbered:
:website: https://wwww.tu-dresden.de/bauklimatik
:source-highlighter: rouge
:rouge-style: custom
:title-page:
:stylesdir: ../adoc_utils/css
:stylesheet: roboto_ubuntu.css
:tabsize: 2
:title-page:

:caution-caption: Achtung
:example-caption: Beispiel
:figure-caption: Abbildung
:table-caption: Tabelle
:section-refsig: Abschnitt


## Einleitung


Das Institut für Bauklimatik (IBK) entwickelt seit Jahrzehnten Softwareprodukte. Schwerpunkt bilden Produkte für die (hygro-)thermische Analyse von Baustoffen, Baukonstruktionen sowie Räume, Gebäude und Quartiere. Im Laufe der Zeit sind verschiedenste Gleichungslöser als auch direkte Anwendungsprogramme für Ingenieure entstanden.

*Gleichungslöser:*

* DelphinSolver
* TheraklesSolver
* NANDRAD-Solver

*Ingenieursanwendungen:*

* CCM-Editor - Klimadatenauswertung und Modifikation
* COND - Analyse und Auslegung von Bauteilen mit Innen- und Außendämmung
* Delphin - Analyse und Auslegung von Bauteilen. Hierbei können verschiedenste Szenarien wie beispielsweise Schlagregenbelastungen, Schimmelpilzwachstum, Wärmebrückenberechnung betrachtet werden. Zusätzlich kann Delphin das Erdreich abbbilden und damit Erdwärmekollektoren analysieren und auslegen.
* Therakles - Analyse und Bewertung von Raumklimabetrachtungen. Ermittlung von Heiz- bzw. Kühlbedarf, Raumluft- und Oberflächentemperaturen, Raumluftfeuchten, Behaglichkeitskennwerten.
* PostProc2 - Auswertungswerkzeug für die Be- und Verarbeitung von Ergebnisdaten aus Delphin, Therakles und NANDRAD.
* MasterSim - Werkzeug zur Kopplung und gemeinsamen Berechnung von verschiedenen Solversystemen. Anwendung findet hier die FMI-Technologie (CoSimulation).
* SIM-VICUS - 3D-Eingabemaske für den NANDRAD-Solver. (derzeit in Entwicklung)

Weiter kleine Programmlösungen sind PV-Tool als auch der Erdkollektordesigner

## Roadmap

### Prioritäten

Für ein Ranking werden die Arbeitspunkte mit einer Priorität versehen. Dabei steht 10 für die höchste Priorität und 1 für die niedrigste. Diese werden in der Zusammenfassung in Klammern hinter dem Text angegeben. 

### Datenbanken

Die Datenbanken aller Programme müssen erweitert werden. Speziell bei der Materialdatenbank muss mehr Input vom Labor an die Softwareentwicklungsabteilung hergestellt werden.

### Bauteilsimulation

Für die Ingenieure ist es essentiell schnell und effektive die an Sie gestellte Aufgaben abzuarbeiten. Daher ist das Aufsetzen von Projekten zu betrachten 
als auch das Auswerten der Ergebnisse und die Produktion von Berichten.

*COND*

Keine Bedarfe

*Delphin*

Das Aufsetzen von 3D-Projekten ist noch nicht mit einer grafischen Nutzeroberfläche möglich. Das automatisierte Erstellen von Berichten ist ebenfalls wenig ausgebaut. Auch hier könnten Verbesserungen erzielt werden. Dazu müssten die Szenarien aufgestellt werden die in der Ingenieurpraxis auftreten und anschließen ein Bericht programmiert werden. Zusätzlich können ähnlich wie die Berichte auch Vorgabeprojekte über einen Wizard erstellt werden. Dabei wir im Vorfeld eine Analyse/Berechnung ausgewählt und man wird anschließend durch ein Dialogmenü geführt und trägt gewisse Kennwerte ein oder bestätigt diese.

Zusammenfassung:

* 3D Nutzeroberfläche Delphin (1)
* Berichterstellung (8)
* Wizard (8)
* Erweiterung der Innenklimamodelle (10)
* Schlagregen bei hinterlüfteten Fasssad (10)
* Tutorials und Nutzerhandbuch (9)

### Raum-, Gebäude und Quartiersimulationsprogramme

*Therakles*

Für Therakles müssen die Berichte vervollständigt werden.

* Berichterstllung vervollständigen (10)


*NANDRAD2-Solver*

Für die Berechnung von Behaglichkeiten sollte die Raumluftfeuchte mit berechnet werden. Die Ansätze vom NANDRAD 1 können dabei direkt portiert werden. Die Integration von Steuerungssystemen wie Verschattungssteuerung muss entwickelt und umgesetzt werden. Sind später Anlagensysteme zu betrachten müssen Luftnetzwerke ebenso wie die Wassernetzwerke die derzeit von Hauke umgesetzt werden zu entwickeln.

Zusammenfassung:

* Raumluftfeuchte
* Modelle zur Steuerung von Systeme

*SIM-VICUS*

SIM-VICUS hat den größten Entwicklungsbedarf. Dies sollte für die zukünftige Abarbeitung von Projekten im Gebäude- als auch Quartiersbereich unbedingt erweitert werden. Bei der Eingabe müssen der Import der IFC als auch der 2D Import von dwg und/oder dxf angegangen werden. Weiterhin wird die Erstellung und Bearbeitung von Geometriemodellen direkt in SIM-VICUS für Praxisprojekte benötigt. Dazu zählen die Funktionen Transformieren, Skalieren und Rotation, sowie die Verschneidung von Flächen. Für die Anschließende thermische Simulation müssen die Partneroberflächen möglichst automatisiert gefunden und verschnitten werden. Anschließend wird ein manuelles als auch automatisches Verlinken von Oberflächen zu einer _Component_ benötigt. Um diesen Aufbau zu gewährleisten müssen die Polygon zuerst von der derzeitigen 3D Datenstruktur in eine 2D Datenstruktur (VICUS-Format) überführt werden. 

Weiterhin sind die Modelle zu komplementieren. Hierbei können ebenfalls Wizards und Reports wie beispielsweise Kühllastberechnung nach VDI 2078 bzw Heizlast nach DIN EN ISO 12831 oder der sommerliche Wärmeschutz nach DIN 4108-2 zum Einsatz. Zusätzlich müssen in einem Report alle Eingabedaten zusammengefasst werden.

Die Wizards und Reports werden nicht Open-Source gestellt. Dafür ist eine Plugin-Struktur herzustellen. Durch Plugins kann zu einem späteren Zeitpunkt eine Vermarktung von SIM-VICUS erfolgen.

* Import IFC (7)
* Import dxf/dwg(3)
* Polygone auf 2D Abstraktion umbauen (10)
* Verschneidung (9)
* Verlinkung von Flächen (9)
* Geometrieoperationen (7)
* Infrastruktur für Datenbankplugins (5)
* Export anpassen (5)
* Bugfixes (6)
* Wizard/Report DIN EN ISO 12831 - Heizlastberechnung (5)
* Wizard Report VDI 2078 - Kühllastberechnung (5)
* Wizard/Report DIN 4108-2 - sommerlicher Wärmeschutz (5)
* Report der Eingabedaten (5)



### Weitere Programme

*CCM*

Die Anbindung von Datenbanken ist für Ingenieure essentiell. Durch die Anbindung der Datenbanken one-building.org als auch des DWD bekommen Ingenieure sehr leicht zugriff auf verschiedenste Klimata. Diese können von allen Softwareprodukten SIM-VICUS/NANDRAD/Therakles/Delphin genutzt werden und zur Berechnung herangezogen werden.

* One-Building Datenbakimport
* DWD-Importer


*PostProc2*

Einige Anpassungen für die Auswertungen für Gebäude und Quartiersprojekte sollen noch umgesetzt werden. (1)

* Erstellung von Balkendiagramm (2)
* Erstellung von Polardiagramm (2)

*Master-Sim*

Keine Bedarfe

*PV-Tool*

Keine Bedarfe

*Erdkollektordesigner*

Ausprogrammieren der 1D Szenarien. Erstellen eines Auslegungsmodells für Bohrungen.
