= Zeitpläne

== Einleitung

Einleitung

== Wofür werden Zeitpläne verwendet?

== Aufbau

* zyklische und nicht zyklische Zeitpläne

=== Zyklische Zeitpläne

Diese Zeitpläne lassen sich in Perioden abbilden. Eine Periode ist durch ein Start- und Enddatum definiert. Innerhalb einer Periode gibt es einen oder mehrere Tageszyklen die insgesamt alle möglichen Tage eine Woche definieren. 

.Mögliche Tage der Woche
[options="header", cols="10%,^ 20%",width="100%"]
|===
|Name| Anmerkung 
| Montag |
| Dienstag |
| Mittwoch |
| Donnerstag |
| Freitag |
| Samstag |
| Sonntag |
| Feiertag | bspw. Ferien, Feiertag, Urlaub
|===

==== Periode

Eine Periode wird durch ein Start- und Enddatum definiert. Innerhalb einer Periode werden Tageszeitpläne aus den oben genannten Tagen definiert. Diese enthalten eine vollständige Definition eines Tagesganges mit 24 h.

==== Tagesgang

Ein Tagesgang enthält eine Reihe an Zeitpunkten und einen oder mehrere Werte für bestimmte Vorgabewerte wie bespielsweise Personenaktivität oder Heizsollwerte.

=== Nicht zyklische Zeitpläne

Diese Zeitpläne werden durch eine bestimmte Anzahl an individuelle Wertepaarvorgabe für Zeitpunkt und Wert definiert. Somit sind Messreihen oder spezielle Vorgaben möglich.