:imagesdir: ./images

[[models]]
# Modellparametrisierung

In diesem Abschnitt werden die verschiedenen Modellparametrisierungsblöcke beschrieben. Modelle werden verwendet, um gleichartige Funktionalität für mehrere Objekte (meist Zonen) zu definieren. Die in den Modellblöcken abgelegten Parameter gelten dann für alle (via Objektlisten) ausgewählten Objekte. Allerdings können objektspezifische Eigenschaften (bspw. Nutzfläche bei Zonen) in die Modell einfließen.

## Natürliches Lüftungsmodell

Das Modell für natürliche Lüftung definiert den Luftaustausch mit der Außenluft und beinhaltet Nutzerlüftung wie ungewollte Lüftung durch Leckagen (Fugenlüftung/Infiltration). Die natürliche Lüftung wird für bestimmte Zonen aktiviert, indem ein Modellparametersatz `NaturalVentilationModel` definiert wird. Über die Objektliste werden die Zonen ausgewählt.

====
[source,xml]
----
<!-- Lüftungsmodell mit durchgängig konstanter Infiltration/Grundluftwechsel -->
<NaturalVentilationModel id="501" displayName="Zone vent" modelType="Constant">
	<ZoneObjectList>Office zones</ZoneObjectList>
	<IBK:Parameter name="VentilationRate" unit="1/h">0.5</IBK:Parameter>
</NaturalVentilationModel>
<!-- Lüftungsmodell mit zeitabhängig geregelter Luftwechselrate -->
<NaturalVentilationModel id="502" displayName="Zone vent" modelType="Scheduled">
	<ZoneObjectList>Other zones</ZoneObjectList>
</NaturalVentilationModel>
<!-- Lüftungsmodell mit zeitabhängig geregelter, erhöhter Luftwechselrate und Grundluftwechsel -->
<NaturalVentilationModel id="503" displayName="Zone vent" modelType="ScheduledWithBaseACR">
	<IBK:Parameter name="VentilationRate" unit="1/h">0.5</IBK:Parameter>
	<!-- Erhöhte Lüftungsrate verwenden, wenn Raumtemperature 23°C überschreitet -->
	<IBK:Parameter name="MinimumRoomAirTemperatureACRLimit" unit="C">23</IBK:Parameter>
	<!-- Keine Begrenzung der erhöhten Lüftung bei hohen Raumtemperaturen  -->
	<IBK:Parameter name="MaximumRoomAirTemperatureACRLimit" unit="C">100</IBK:Parameter>
	<!-- Parameter muss gegeben sein, um Regelung auszuschalten, sehr hohe Grenzwerte verwenden -->
	<IBK:Parameter name="MaximumEnviromentAirTemperatureACRLimit" unit="C">100</IBK:Parameter>
	<IBK:Parameter name="MinimumEnviromentAirTemperatureACRLimit" unit="C">-100</IBK:Parameter>
	<IBK:Parameter name="DeltaTemperatureACRLimit" unit="K">0</IBK:Parameter>
	<IBK:Parameter name="WindSpeedACRLimit" unit="m/s">10</IBK:Parameter>
	<ZoneObjectList>Special zones</ZoneObjectList>
</NaturalVentilationModel>

<!-- Lüftungsmodell mit zeitabhängig geregelter, erhöhter Luftwechselrate und Grundluftwechsel,
     Regelparameter werden über Schedules geliefert.
-->
<NaturalVentilationModel id="504" displayName="Zone vent" modelType="ScheduledWithBaseACR">
	<IBK:Parameter name="VentilationRate" unit="1/h">0.5</IBK:Parameter>
	<ZoneObjectList>Special zones</ZoneObjectList>
</NaturalVentilationModel>

<!-- Lüftungsmodell mit realistischer Berechnung der Luftwechselrate basierend auf 
     Windgeschwindigkeit und Temperaturgradienten -->
<NaturalVentilationModel id="505" displayName="Zone vent" modelType="Realistic">
	<IBK:Parameter name="VentilationRate" unit="1/h">0.5</IBK:Parameter>
	<IBK:Parameter name="ConstantCoefficient" unit="-">0.6</IBK:Parameter>
	<IBK:Parameter name="TemperaturCoefficient" unit="1/K">0.04</IBK:Parameter>
	<IBK:Parameter name="WindCoefficient" unit="s/m">0.04</IBK:Parameter>
	<IBK:Parameter name="SquaredWindCoefficient" unit="s2/m2">0.0</IBK:Parameter>
	<ZoneObjectList>Special other zones</ZoneObjectList>
</NaturalVentilationModel>
----
====


[IMPORTANT]
====
Es darf nur ein Lüftungsmodellblock für eine Zone definiert werden. Es dürfen also nicht zwei Lüftungsmodellblöcke mit Objektlisten definiert werden, die beide die gleiche(n) Zone(n) enthalten.
====

Das `NaturalVentilationModel` muss mit den folgenden XML-Attributen definiert werden:

.Attribute
[.indent-me]
[options="header",cols="20%,60%,^ 10%,^ 10%",width="100%"]
|====================
| Attribut | Beschreibung | Format | Verwendung 
| `id` | Kennung des natürlichen Lüftungsmodells | {nbsp}>{nbsp}0{nbsp} | _erforderlich_

| `modelType` 
a| Setzt den Typ des Lüftungsmodells 

* `Constant` - Konstante Luftwechselrate
* `Scheduled` - Luftwechselrate ändert sich nach einem definierten Zeitplan. Zusätzlich kann durch Steuerungsmodelle der Luftwechsel auf null gesetzt werden.

* `ScheduledWithBaseACR` - Es wird ein konstanter Luftwechsel und ein zeitabhängiger Luftwechsel - Scheduled with base air change rate -  integriert. Dabei kann der zeitabhängige Luftwechsel zusätzlich durch Steuerungsmodelle auf null gesetzt werden.

* `Realistic`- TODO 

| key | _erforderlich_
|====================


Gleitkommazahlen-Parameter (siehe Abschnitt <<IBK_Parameter>> für eine Beschreibung des Tags `IBK:Parameter`):

[options="header",cols="20%,^ 15%,35%,^ 20%,^ 10%",width="100%"]
|====================
|Name|Vorgabeeinheit|Beschreibung|Wertebereich |Verwendung
| `VentilationRate` | 1/h | Konstante Luftwechselrate | {nbsp}>={nbsp}0.0{nbsp} | _erforderlich für Modelltyp_ `Constant` oder `ScheduledWithBaseACR`
| *`ConstantCoefficient` | - | Modifikationsfaktor C1 für die Luftwechselrate (Standardwert 1) | {nbsp}>={nbsp}0.0{nbsp} | _optional_
| *`TemperatureCoefficient` | 1/K | Modifikationsfaktor C2 für die Luftwechselrate (Standardwert 0) | {nbsp}>={nbsp}0.0{nbsp} | _optional_
| *`WindCoefficient` | s/m | Modifikationsfaktor C3 für die Luftwechselrate (Standardwert 0) | {nbsp}>={nbsp}0.0{nbsp} | _optional_
| *`SquaredWindCoefficient` | s2/m2 | Modifikationsfaktor C4 für die Luftwechselrate (Standardwert 0) | {nbsp}>={nbsp}0.0{nbsp} | _optional_
|====================

(*) noch nicht implementiert


Beim Modelltyp `Constant` wird durchweg eine konstante Luftwechselrate (Parameter `VentilationRate`) verwendet.

Beim Modelltyp `Scheduled` wird die Luftwechselrate aus einem Zeitplan (Parameter `VentilationRateSchedule`, siehe <<schedules>>) entnommen. Weitere Parameter sind nicht notwendig.

Nachfolgend finden Sie ein Beispiel für einen Zeitplan, der den Parameter `VentilationRateSchedule` für ein solches Modell der geplanten natürlichen Lüftung bereitstellt:

.Zeitplan, der den Parameter _VentilationRateSchedule_ bereitstellt
====
[source,xml]
----
<ScheduleGroup objectList="All zones">
	<!-- jeden Tag zwischen 8-10 -->
	<Schedule type="AllDays">
		<DailyCycles>
			<DailyCycle interpolation="Constant">
				<TimePoints>0 6 10</TimePoints>
				<Values>VentilationRateSchedule [1/h]:0 0.4 0</Values>
			</DailyCycle>
		</DailyCycles>
	</Schedule>
	<!-- Dienstag keine Lüftung -->
	<Schedule type="Tuesday">
		<DailyCycles>
			<DailyCycle interpolation="Constant">
				<TimePoints>0</TimePoints>
				<Values>VentilationRateSchedule [1/h]:0</Values>
			</DailyCycle>
		</DailyCycles>
	</Schedule>
	<!-- Wochenende nur am Nachmittag -->
	<Schedule type="WeekEnd">
		<DailyCycles>
			<DailyCycle interpolation="Constant">
				<TimePoints>0 14 16</TimePoints>
				<Values>VentilationRateSchedule [1/h]:0 0.1 0</Values>
			</DailyCycle>
		</DailyCycles>
	</Schedule>
</ScheduleGroup>
----
====


Beim Modelltyp `ScheduledWithBaseACR` wird ein konstanter Grundluftwechsel (Parameter `VentilationRate`) verwendet und unter bestimmten Bedingungen wird ein zusätzlicher Luftwechsel `VentilationRateSchedule` verwendet.

Die Luftwechselrate wird berechnet:

```
n = n_Grundluftwechsel                          // wenn Bedingungen nicht erfüllt
n = n_Grundluftwechsel + n_erhöhterLuftwechsel  // wenn Bedingungen erfüllt
```

#### Regelbedingungen

Folgende Bedingungen müssen _alle_ erfüllt sein, damit der erhöhte Luftwechsel addiert wird.

- Raumluftzustand: `MinimumRoomAirTemperatureACRLimit` < T_Raum < `MaximumRoomAirTemperatureACRLimit`
- Außentemperatur: `MinimumEnviromentAirTemperatureACRLimit`< T_Außenluft < `MaximumEnviromentAirTemperatureACRLimit`
- Temperaturdifferenz: T_Raum - T_Außenluft < `DeltaTemperatureACRLimit`, dabei kann `DeltaTemperatureACRLimit` auch negativ sein. Damit können auch Heizeffekte (Raum kalt, Außenluft warm) berücksichtigt werden. 
- Windgeschwindigkeit: akt. Wingeschwindigkeit < `WindSpeedACRLimit`




Damit das Modell mit der Ausprägung `ScheduledWithBaseACR` verwendbar ist, müssen beide Parameter _VentilationRate_ und _VentilationRateSchedule_ spezifiziert werden.

Gleitkommazahlen-Parameter (siehe Abschnitt <<IBK_Parameter>> für eine Beschreibung des Tags `IBK:Parameter`):

[options="header",cols="20%,^ 15%,35%,^ 20%,^ 10%",width="100%"]
|====================
|Name|Vorgabeeinheit|Beschreibung|Wertebereich |Verwendung
| `MaximumRoomAirTemperatureACRLimit` | C | Maximale Raumlufttemperatur für aktive Lüftung. | -100 ... 100  | _xxx_
| `MinimumRoomAirTemperatureACRLimit` | C | Minimale Raumlufttemperatur für aktive Lüftung. | -100 ... 100  | _xxx_
| `MaximumEnviromentAirTemperatureACRLimit` | C | Maximale Außenlufttemperatur für aktive Lüftung. | -100 ... 100  | _xxx_
| `MinimumEnviromentAirTemperatureACRLimit` | C | Minimale Außenlufttemperatur für aktive Lüftung. | -100 ... 100  | _xxx_
| `DeltaTemperatureACRLimit` | K | Minimale Differenz von Raumlufttemperatur minus Außenlufttemperatur (Tzone - Tout) für aktive Lüftung. | -100 ... 100  | _xxx_
| `WindSpeedACRLimit` | m/s | Maximale Windgeschwindigkeit für aktive Lüftung. | 0 ... 40  | _xxx_
|====================

Die dazugehörigen zeitabhängigen Schedule-Parameter sind gleichartig benannt, jedoch jeweils mit dem Suffix `Schedule`.



[NOTE]
====
Eine allgemeine Abhängigkeit von Wind- und/oder Temperaturpotentialen ist möglich, wenn man für einen odere mehrere Koeffizienten Abweichungen von dem/den Standardwert(en) setzt. Die allgemeine Formel zur modifizierten Luftwechselrate lautet:

n = n * (C1 + C2 * (Tzone - Tout) + C3 * windSpeed + C4 * windSpeed²)

Die Modifikation der Luftwechselrate wird immer auf beide Luftwechselraten (konstant und zeitgesteuert) angewendet.

TODO : Spezifizieren

====


#### Ausgabegrößen

Die berechneten Lüftungswärmeverlust/-gewinnen können als zonenspezifische Größen über die Ergebnisgröße
`Zone.VentilationHeatLoad` in [W] abgerufen werden.


## Steuerungsmodell für Verschattung

Ein Verschattungregelungsmodell ist eine spezielle Art von Regelungsmodell, das einen Signalwert zwischen 0 (keine Verschattung) und 1 (volle Verschattung) zurückgibt. Das tatsächliche Ausmaß der Verschattung bzw. die Reduzierung der solaren Gewinne wird durch den Verschattungs-Parameterblock (`Shading`, siehe <<window_shading>>) bestimmt. Somit kann das gleiche Regelmodell für verschiedene Verschattungseinrichtungen verwendet werden.

.Parameterdefinition für Verschattungsregelungsmodell
[source,xml, indent=0]
====
----
<Models>
    <ShadingControlModels>
    	<!-- ShadingControlModel liefert einen Wert zwischen 0 und 1 
    		0 = keine Reduktion (Verschattung offen)
    		1 = volle Reduktion (Verschattung geschlossen)
    	-->
    	<ShadingControlModel id="2000" displayName="Global horizontal sensor controller" sensorID="50000">
    		<IBK:Parameter name="MaxIntensity" unit="W/m2">300</IBK:Parameter>
    		<IBK:Parameter name="MinIntensity" unit="W/m2">150</IBK:Parameter>
    	</ShadingControlModel> 
    </ShadingControlModels>
</Models>
----
====

Das Verschattungskontrollmodell verlangt 2 Parameter `MaxIntensity` und `MinIntensity` und implementiert eine digitale Regelung mit Hysterese. Zunächst muss die Globalstrahlungsintensität auf den Sensor den oberen Grenzwert überschreiten `MaxIntensity`, wonach die Verschattung geschlossen wird (Kontrollmodell liefert 1). Danach muss die Strahlungsintensität zunächst unter die untere Grenze sinken (`MinIntensity`), bevor die Verschattung wieder geöffnet wird (Kontrollmodell liefert 0).

Für die Auswertung wird eine Horizontalstrahlung benötigt. Dafür muss eine Oberfläche ausgewählt werden und als `sensorID` angegeben werden. Möglich sind hier 3 Optionen:

- allgemeiner Sensor auf einer Fläche (siehe <<location_sensors>>)
- ID eines Fensters (eigentlich ID des _embedded object_, welches das Fenster enthält); hier wird die Globalstrahlung durch das Fenster als Eingangsgröße verwendet, einschließlich eventueller externer Verschattung bzw. Eigenverschattung 
- ID einer opaquen Fläche; hier wird die Globalstrahlung auf eine opaque Fläche als Eingangsgröße verwendet, einschließlich eventueller externer Verschattung bzw. Eigenverschattung 

Damit diese IDs eindeutig auflösbar sind, müssen Sensoren, Fenster und Konstruktionen global eindeutige IDs tragen.

### Ausgabegrößen

Das Verschattungssteuerungsmodell liefert als Ergebnisgrößen:

- `ShadingControlValue` - Steuerungssignal für Verschattung: 0 - komplett offen, 1 - komplett geschlossen, Zwischenwerte sind möglich
- `SolarIntensityOnShadingSensor` - Solarstrahlungsintensität auf ausgewählten Sensor, der für die Regelung verwendet wird


## Modell für interne Lasten

Das interne Lastenmodell wird verwendet, um die Wärmelasten von Geräten, Personen und Beleuchtung für Zonen zu definieren. Interne Lasten werden genauso definiert wie natürliche Lüftungsmodelle. Der Objektlisten-tag `ZoneObjectList` identifiziert die Zonen, in denen interne Lasten berücksichtigt werden sollen.
Es dürfen nicht zwei interne Lastmodelle existieren, die sich auf dieselben Zonen beziehen (nur eine interne Last pro Zone).

.Definitionsblock für interne Lasten
====
[source,xml]
----
<InternalLoadsModel id="200" modelType="Scheduled">
	<ZoneObjectList>Office zones</ZoneObjectList>
	<IBK:Parameter name="RadiantFraction" unit="---">0.5</IBK:Parameter>
</InternalLoadsModel>
----
====


Das `InternalLoadsModel` muss mit den folgenden XML-Attributen definiert werden:

.Attribute
[.indent-me]
[options="header",cols="20%,60%,^ 10%,^ 10%",width="100%"]
|====================
| Attribut | Beschreibung | Format | Verwendung 
| `id` | Kennung des Modells | {nbsp}>{nbsp}0{nbsp} | _erforderlich_

| `modelType` 
a| Gibt an, wie die internen Lasten angesetzt werden sollen

* `Constant` - Konstante Geräte-, Personen- und Beleuchtungsenergielasten
* `Scheduled` - Lasten werden über Zeitplanparameter bereitgestellt.

| key | _erforderlich_
|====================


Fließkommaparameter (siehe Abschnitt <<IBK_Parameter>> für eine Beschreibung des Tags `IBK:Parameter`):

[options="header",cols="20%,^ 15%,35%,^ 20%,^ 10%",width="100%"]
|====================
|Name|Vorgabeeinheit|Beschreibung|Wertebereich |Verwendung
| `EquipmentHeatLoadPerArea` | W/m2 | Komplette Gerätebelastung pro Zonennutzfläche | {nbsp}>={nbsp}0.0{nbsp} | _erforderlich für Konstantes Modell_
| `PersonHeatLoadPerArea` | W/m2 | Komplette Personenwärmelast pro Zonennutzfläche | {nbsp}>={nbsp}0.0{nbsp} | _erforderlich für Konstantes Modell_
| `LightingHeatLoadPerArea` | W/m2 | Komplette Wärmelast aus Beleuchtung pro Zonennutzfläche | {nbsp}>={nbsp}0.0{nbsp} | _erforderlich für Konstantes Modell_
| `EquipmentRadiationFraction` | --- | Prozentualer Anteil der Wärme der Geräte, der durch Strahlung emittiert wird | {nbsp}>={nbsp}0.0{nbsp} | _erforderlich_
| `PersonRadiationFraction` | --- | Prozentualer Anteil der Wärme der Personen, der durch Strahlung emittiert wird | {nbsp}>={nbsp}0.0{nbsp} | _erforderlich_
| `LightingRadiationFraction` | --- | Prozentualer Anteil der Wärme der Beleuchtung, der durch Strahlung emittiert wird | {nbsp}>={nbsp}0,0{nbsp} | _erforderlich_
|====================

[NOTE]
====
Die Zonennutzfläche ist nicht zwingend die Grundfläche einer Zone sondern wird aus dem Parameter _Area_ der Zonendefinition gewählt. Dadurch ist es möglich, z.B. im Dachgeschoss mit Schrägen die tatsächlich nutzbare Fläche zu definieren verwenden. Deshalb wird der _Area_ Parameter in allen Zonen benötigt, für die ein `InternalLoadsModel` angewendet werden soll.
====

Der Modelltyp `Constant` übernimmt die internen Lasten aus den Parametern (siehe oben).
Wenn der Modelltyp `Scheduled` verwendet wird, werden die tatsächlichen Lasten aus dem Zeitplan entnommen.

Die folgenden Zeitplanparameter sind erforderlich:

- `EquipmentHeatLoadPerAreaSchedule [W/m2]`
- `PersonHeatLoadPerAreaSchedule [W/m2]`
- `LightingHeatLoadPerAreaSchedule [W/m2]`

Die zonenspezifischen Ausgangsgrößen heißen: 

- `ConvectiveEquipmentHeatLoad [W]`
- `ConvectivePersonHeatLoad [W]`
- `ConvectiveLightingHeatLoad [W]`
- `RadiantEquipmentHeatLoad [W]`
- `RadiantPersonHeatLoad [W]`
- `RadiantLightingHeatLoad [W]`

Dies sind vektoriell dargestellte Größen, die in Ausgangsdefinitionen referenziert werden müssen, z. B. mit: `ConvectiveEquipmentHeatLoad[id=3]` für die konvektive Gerätelast in Zone #3.


Die Parameter `xxxRadiationFraction` geben an, welcher Prozentsatz der berechneten internen Lasten als Strahlungsfluss flächengewichtet auf opake Oberflächen, die die Zone umschließen, aufgebracht werden soll. 


[[ZoneControlThermostat]]
## Modell für Thermostate

Das Thermostatmodell beschreibt, auf welche Raumsollwerte konditioniert werden soll. Angegeben werden können Heiz- und/oder Kühlsolltemperaturen für die Raumluft oder operative Raumluft.
Der Objektlisten-tag `ZoneObjectList` identifiziert die Zonen, in denen Thermostate berücksichtigt werden sollen. Es darf nur ein Modell pro Zone existieren.

.Definitionsblock für Thermostate
====
[source,xml]
----
<ZoneControlThermostat id="200" modelType="Constant">
	<ZoneObjectList>Office zones</ZoneObjectList>
	<IBK:Parameter name="HeatingSetpoint" unit="C">20</IBK:Parameter>
	<IBK:Parameter name="CoolingSetpoint" unit="C">21</IBK:Parameter>
	<TemperatureType>AirTemperature</TemperatureType>
</ZoneControlThermostat>
----
====


Das `ZoneControlThermostat` muss mit den folgenden XML-Attributen definiert werden:

.Attribute
[.indent-me]
[options="header",cols="20%,60%,^ 10%,^ 10%",width="100%"]
|====================
| Attribut | Beschreibung | Format | Verwendung 
| `id` | Kennung des Modells | {nbsp}>{nbsp}0{nbsp} | _erforderlich_

| `modelType` 
a| Gibt an, wie die Thermostat-Parameter angesetzt werden sollen

* `Constant` - Konstante Sollwerte
* `Scheduled` - Sollwerte werden über Zeitplanparameter bereitgestellt.

| key | _erforderlich_
|====================


Fließkommaparameter (siehe Abschnitt <<IBK_Parameter>> für eine Beschreibung des Tags `IBK:Parameter`):

[options="header",cols="20%,^ 15%,35%,^ 20%,^ 10%",width="100%"]
|====================
|Name|Vorgabeeinheit|Beschreibung|Wertebereich |Verwendung
| `HeatingSetpoint` | C | konstanter Heizsollwert | < `CoolingSetpoint` | _erforderlich für Modelltyp_ `Constant`
| `CoolingSetpoint` | C | konstanter Kühlsollwert | > `HeatingSetpoint` | _erforderlich für Modelltyp_ `Constant`
|====================

### TemperatureType

Der XML-tag `TemperatureType` enthält eine Zeichenkette zur Auswahl eines bestimmten Typs (`AirTemperature` wird standardmäßig verwendet, wenn das tag fehlt).

.verfügbare TemperatureTypes
[options="header", cols="20%, 80%", width="100%"]
|====================
|Name|Beschreibung
|`AirTemperature`| Als Referenztemperatur wird die Raumlufttempatur verwendet.
|`OperativeTemperature`| Als Referenztemperatur wird die operative Raumlufttempatur verwendet. Diese setzt sich aus der mittleren Oberflächentemperatur aller Innenoberflächen und aus der Raumlufttemperatur zusammen. Die Anteile betragen jeweils 50%.
|====================

[NOTE]
====
Ein Thermostat hält nur die Sollwerte für die Zone. Eine Konditionierung der Zone erfolgt erst wenn zusätzlich eine Heizungs- und/oder Kühlmodell für die Zone integriert ist. Auch bei den Zeitplänen ist immer darauf zu achten, dass der Heizsollwert < Kühlsollwert ist.
====

Der Modelltyp `Constant` übernimmt die Sollwerte aus den Parametern (siehe oben).
Wenn der Modelltyp `Scheduled` verwendet wird, werden die tatsächlichen Sollwerte aus dem Zeitplan entnommen.

Die folgenden Zeitplanparameter sind erforderlich:

- `HeatingSetpointSchedule [C]`
- `CoolingSetpointSchedule [C]`

Die zonenspezifischen Ausgangsgrößen heißen: 

- `HeatingSetpoint [C]`
- `CoolingSetpoint [C]`

Dies sind vektoriell dargestellte Größen, die in Ausgangsdefinitionen referenziert werden müssen, z. B. mit: `HeatingSetpoint[id=3]` für den Heizsollwert in Zone #3.


## Modell für ideale thermische Konditionierung

Das Modell beschreibt ein ideles thermisches Konditionierungsmodell für eine ideale Raumluftkonditionierung.
Der Objektlisten-tag `ZoneObjectList` identifiziert die Zonen, in denen das Modell berücksichtigt werden sollen. Es darf nur ein Modell pro Zone existieren.

.Definitionsblock für Ideale thermische Konditionierung
====
[source,xml]
----
<ZoneIdealHeatingCooling id="200">
	<ZoneObjectList>Office zones</ZoneObjectList>
	<IBK:Parameter name="MaxHeatingPowerPerArea" unit="W/m2">50</IBK:Parameter>
	<IBK:Parameter name="MaxCoolingPowerPerArea" unit="W/m2">20</IBK:Parameter>
</ZoneIdealHeatingCooling>
----
====

Das `ZoneIdealHeatingCooling` muss mit den folgenden XML-Attributen definiert werden:

.Attribute
[.indent-me]
[options="header",cols="20%,60%,^ 10%,^ 10%",width="100%"]
|====================
| Attribut | Beschreibung | Format | Verwendung 
| `id` | Kennung des Modells | {nbsp}>{nbsp}0{nbsp} | _erforderlich_
|====================


Fließkommaparameter (siehe Abschnitt <<IBK_Parameter>> für eine Beschreibung des Tags `IBK:Parameter`):

[options="header",cols="20%,^ 15%,35%,^ 20%,^ 10%",width="100%"]
|====================
|Name|Vorgabeeinheit|Beschreibung|Wertebereich |Verwendung
| `MaxHeatingPowerPerArea` | W/m2 | maximale flächenbezogene Heizleistung | {nbsp}>={nbsp}0.0{nbsp} | _erforderlich_ 
| `MaxCoolingPowerPerArea` | W/m2 | maximale flächenbezogene Kühlleistung | {nbsp}>={nbsp}0.0{nbsp} | _erforderlich_ 
|====================

[NOTE]
====
Damit das Modell auf die jeweilige Zone angewendet wird, ist zwingend das <<ZoneControlThermostat>> nötig, welches für die gleichen Zone parametriert sein muss. Dieses liefert als Eingangsgrößen für das `ZoneIdealHeatingCooling` die Größen `HeatingSetpoint` und `CoolingSetpoint`.
====

#### Regelungsimplementierung

Standardmäßig verwendet das ideale Konditionierungsmodell einen P-Regler, nach dem Schema:

```
Heizlast = MaxHeatingPowerPerArea * clip( (T_soll - T_raum) / DeltaT )

// alternativ mit Mittelpunktsverschiebung
Heizlast = MaxHeatingPowerPerArea * clip( (T_soll - T_raum) / DeltaT + 0.5))
```

`clip` heißt: zwischen 0 und 1 begrenzen.

`T_raum` ist entweder die Lufttemperatur oder die operative Temperatur. Dafür ist die Information im ThermostatModell notwendig.


#### Ausgaben

Die zonenspezifischen Ausgangsgrößen heißen: 

- `IdealHeatingLoad [W]`
- `IdealCoolingLoad [W]`

Dies sind vektoriell dargestellte Größen, die in Ausgangsdefinitionen referenziert werden müssen, z. B. mit: `IdealHeatingLoad[id=3]` für die Heizlast in Zone #3.
