:imagesdir: ./images
[[climatic_loads]]
# Climatic loads

## Overview

Climatic loads in NANDRAD are provided by means of climate data files. For solar radiation calculation it needs information on the building location (usually provided in the climate file), and also the orientation and inclination of the various construction surfaces (defined for outside surfaces, see <<construction_instances,Geometry/Constructions>>).

## Specification

Information about location and climate data is stored in the `Location` section of the project file:

[source,xml]
----
<Location>
	<IBK:Parameter name="Latitude" unit="Deg">51</IBK:Parameter>
	<IBK:Parameter name="Longitude" unit="Deg">13</IBK:Parameter>
	<IBK:Parameter name="Albedo" unit="---">0.2</IBK:Parameter>
	<IBK:Parameter name="Altitude" unit="m">100</IBK:Parameter>
	<IBK:Flag name="PerezDiffuseRadiationModel">false</IBK:Flag>
	<ClimateFileName>${Project Directory}/climate/GER_Potsdam_2017.c6b</ClimateFileName>
</Location>
----

Parameters (see also section <<IBK_Parameter>> for a description of the `IBK:Parameter` tag):

[options="header",cols="15%,10%,45%,20%,10%",width="100%"]
|====================
|`name`|Default Unit|Description|Value Range |Usage
|*Albedo*|---|Used for diffuse solar radiation calculation (see <<loads_solar_radiation>>)|[0,1]|_required_
|*Altitude*|m|later needed for specific altitude-related parameters (**TODO**)| > 0 m)|_optional_
|*Longitude*|Deg|If specified, overrides the location parameter `Longitude` of the climate data file (see <<location_settings>>).|[-180,180] Deg|_optional_
|*Latitude*|Deg|If specified, they override the location parameter `Latitude` of the climate data file (see <<location_settings>>).|[-90,90] Deg|_optional_
|====================

Flags and options (see also section <<IBK_Flag>> for a description of the `IBK:Flag` tag):

[options="header",cols="15%,65%,10%,10%",width="100%"]
|====================
| `name` | Description | Default | Usage 
| *PerezDiffuseRadiationModel* |  Defines whether to use the Perez-Model for diffuse solar radiation calculation | _false_ | _optional_
|====================

Lastly, the `<ClimateFileName>` tag defines the path to the climate data file.

[[loads_climate_files]]
### Climate Data Files

Currently, `c6b`, `wac` and `epw` files are supported (see also help for the https://bauklimatik-dresden.de/ccmeditor/help[CCM-Editor] tool).

You need to specify the path to the climate data file in the `<ClimateFileName>` tag. Hereby, you can specify an absolute or relative path.

If a relative path is privided, it will be resolved using the current working directory as reference. For example, if you have specified 

[source,xml]
----
<ClimateFileName>GER_Potsdam_2017.c6b</ClimateFileName>
----

and the solver is run from the directory `/home/user/sim/Project1`, the climate data file will be searched in `/home/user/sim/Project1/GER_Potsdam_2017.c6b`. If the solver is run from a different directory, the referenced climate data file won't be found and an error message is raised.

To avoid this problem, you may specify directory placeholders to locate the climate data file _relative_ to the project file's location. The builtin path placeholder `${Project Directory}` will be replaced by the directory the project file is located in. Use the placeholder just as a regular directory part, for example:

[source,xml]
----
<ClimateFileName>${Project Directory}/climate/GER_Potsdam_2017.c6b</ClimateFileName>
----

It is possible to define custom placeholders in the project for all externally referenced files, see <<path_placeholders>>.


[[location_settings]]
### Building/Station location

Climate data files contain information on latitude and longitude of the weather station, which is also taken to be the location of the building. This ensures that simulated time and position of the sun matches.

It is also possible to define latitude/longitude in the project file. If these parameters are specified in the project file, always **both** parameters must be given (and be valid) and then the these parameters from the project file are used instead of the climate data file location parameters.
[CAUTION]
====
By specifying latitude different from the climatic station, the computed sun position may no longer correspond to the sun position at the weather station, thus yielding probably wrong solar radiation loads.
====

Valid value range for `Latitude` is [-90,90] degrees (positive values are northern hemisphere), for `Longitude` it is [-180,180] degrees (positive values are east of Greenwich).


### Cyclic (annual) and continuous (multi-year) climate data

The climate data file can either contain 8760 hourly values for an entire year. Anything else is considered as  arbitrary range of time values indicating a specific time interval, possibly also with varying time intervals between data points. The latter climate data files cannot be used for annual/cyclic calculation, but require a specific (matching) simulation time interval (see also section <<simulation_interval>>).


#### Cyclic annual climate


#### Continuous data

The climate data file contains data points (at least 2) 




### Additional radiation sensors

It is possible to specify additional planes (sensors) to generate solar radiation load outputs. This is done by specifying a `Sensor` definition.

[source,xml]
----
<Location>
    ....
    <Sensors>
		<!-- Flat roof -->
		<Sensor id="1">
			<IBK:Parameter name="Orientation" unit="Deg">0</IBK:Parameter>
			<IBK:Parameter name="Inclination" unit="Deg">0</IBK:Parameter>
		</Sensor>
		<!-- North Wall 90 -->
		<Sensor id="2">
			<IBK:Parameter name="Orientation" unit="Deg">0</IBK:Parameter>
			<IBK:Parameter name="Inclination" unit="Deg">90</IBK:Parameter>
		</Sensor>
        ...
    </Sensors>
</Location>
----

A sensor must be given a unique ID number and the mandatory parameters `Orientation` and `Inclination` (see section <<construction_interfaces>> for details on their definition).

For each sensor 4 output quantities are generated:
* `DirectSWRadOnPlane[<sensor id>]`  - direct solar radiation intensity on plane in [W/m2]
* `DiffuseSWRadOnPlane[<sensor id>]` - diffuse solar radiation intensity on plane in [W/m2]
* `GlobalSWRadOnPlane[<sensor id>]` - global radiation intensity on plane in [W/m2] (the sum of the former two)
* `IncidenceAngleOnPlane[<sensor id>]` - the incidence angle onto the plane in [Deg] (0° when sun ray is perpendicular to the plane, 90° when ray is parallel to the plane or when sun is below horizon)

Example for a sensor output (see also output description in section <<outputs>>).

[source,xml]
----
<OutputDefinitions>
    ...
    <!-- direct radiation intensive from sensor with id=2 -->
	<OutputDefinition>
		<Quantity>DirectSWRadOnPlane[2]</Quantity> 
		<ObjectListName>Location</ObjectListName>
		<GridName>minutely</GridName>
	</OutputDefinition>
	<!-- incidence angle from sensor with id=42 -->
	<OutputDefinition>
		<Quantity>IncidenceAngleOnPlane[42]</Quantity>
		<ObjectListName>Location</ObjectListName>
		<GridName>minutely</GridName>
	</OutputDefinition>
    ...
</OutputDefinitions>
----

[[loads_solar_radiation]]
## Solar Radiation Calculation

Solar radiation calculation follows the equations lists in section ... of the __Physical Model Reference__. The `Albedo` parameter is used in the diffuse radiation load calculation.


