:imagesdir: ./images

[[models]]
# Modellparametrisierung

In diesem Abschnitt werden die verschiedenen Modellparametrisierungsblöcke beschrieben.

## Natürliches Lüftungsmodell

Das Modell für natürliche Lüftung definiert den Luftaustausch mit der Außenluft und beiinhaltet Nutzerlüftung wie ungewollte Lüftung durch Leckagen. Die natürliche Lüftung wird für bestimmte Zonen aktiviert, indem ein Modellparametersatz `NaturalVentilationModel` definiert wird. Über die Objektliste werden die Zonen ausgewählt.

====
[source,xml]
----
<NaturalVentilationModel id="501" displayName="Zone vent" modelType="Constant">
	<ZoneObjectList>Office zones</ZoneObjectList>
	<IBK:Parameter name="VentilationRate" unit="1/h">0.5</IBK:Parameter>
</NaturalVentilationModel>
<NaturalVentilationModel id="502" displayName="Zone vent" modelType="Scheduled">
	<ZoneObjectList>Other zones</ZoneObjectList>
</NaturalVentilationModel>
----
====

[IMPORTANT]
====
Es darf nur ein Lüftungsmodellblock für eine Zone definiert werden. Es dürfen also nicht zwei Lüftungsmodellblöcke mit Objektlisten definiert werden, die beide die gleiche(n) Zone(n) enthalten.
====

Das `NaturalVentilationModel` muss mit den folgenden XML-Attributen definiert werden:

.Attribute
[.indent-me]
[options="header",cols="20%,60%,^ 10%,^ 10%",width="100%"]
|====================
| Attribut | Beschreibung | Format | Verwendung 
| `id` | Kennung des natürlichen Lüftungsmodells | {nbsp}>{nbsp}0{nbsp} | _erforderlich_

| `modelType` 
a| Setzt den Typ des Lüftungsmodells 

* `Constant` - Konstante Luftwechselrate
* `Scheduled` - Luftwechselrate ändert sich nach einem definierten Zeitplan
* `IncreasedDayVentilation` - Tagsüber kann die Lüftungsrate erhöht werden, wenn die Außenluft kleiner als die Raumluft ist und die Raumlufttemperatur einen Grenzwert übersteigt.

| key | _erforderlich_
|====================


Gleitkommazahlen-Parameter (siehe Abschnitt <<IBK_Parameter>> für eine Beschreibung des Tags `IBK:Parameter`):

[options="header",cols="20%,^ 15%,35%,^ 20%,^ 10%",width="100%"]
|====================
|Name|Vorgabeeinheit|Beschreibung|Wertebereich |Verwendung
| `VentilationRate` | 1/h | Konstante Luftwechselrate | {nbsp}>={nbsp}0.0{nbsp} | _erforderlich für Modelltyp_ `Constant`
|====================

Wenn der Modelltyp `Scheduled` verwendet wird, sind keine weiteren Parameter erforderlich, da die Luftwechselrate aus einem geplanten Parameter übernommen wird.

Damit das Modell funktioniert, muss der Parameter `VentilationRateSchedule` in einem Zeitplan definiert sein (siehe <<schedules>>).

Nachfolgend finden Sie ein Beispiel für einen Zeitplan, der den Parameter `VentilationRateSchedule` für ein solches Modell der geplanten natürlichen Lüftung bereitstellt:

Beispiel für einen Zeitplan, der den Parameter _VentilationRateSchedule_ bereitstellt
====
[source,xml]
----
<ScheduleGroup objectList="All zones">
	<!-- jeden Tag zwischen 8-10 -->
	<Schedule type="AllDays">
		<DailyCycles>
			<DailyCycle interpolation="Constant">
				<TimePoints>0 6 10</TimePoints>
				<Values>VentilationRateSchedule [1/h]:0 0.4 0</Values>
			</DailyCycle>
		</DailyCycles>
	</Schedule>
	<!-- Dienstag keine Lüftung -->
	<Schedule type="Tuesday">
		<DailyCycles>
			<DailyCycle interpolation="Constant">
				<TimePoints>0</TimePoints>
				<Values>VentilationRateSchedule [1/h]:0</Values>
			</DailyCycle>
		</DailyCycles>
	</Schedule>
	<!-- Wochenende nur am Nachmittag -->
	<Schedule type="WeekEnd">
		<DailyCycles>
			<DailyCycle interpolation="Constant">
				<TimePoints>0 14 16</TimePoints>
				<Values>VentilationRateSchedule [1/h]:0 0.1 0</Values>
			</DailyCycle>
		</DailyCycles>
	</Schedule>
</ScheduleGroup>
----
====


## Steuerungsmodell für Verschattung

Ein Verschattungregelungsmodell ist eine spezielle Art von Regelungsmodell, das einen Signalwert zwischen 0 (keine Verschattung) und 1 (volle Verschattung) zurückgibt. Das tatsächliche Ausmaß der Verschattung bzw. die Reduzierung der solaren Gewinne wird durch den Verschattungs-Parameterblock (`Shading`, siehe <<window_shading>>) bestimmt. Somit kann das gleiche Regelmodell für verschiedene Verschattungseinrichtungen verwendet werden.

.Parameterdefinition für Verschattungsregelungsmodell
[source,xml, indent=0]
====
----
<Models>
	<!-- ShadingControlModel liefert einen Wert zwischen 0 und 1 
		0 = keine Reduktion (Verschattung offen)
		1 = volle Reduktion (Verschattung geschlossen)
	-->
	<ShadingControlModel id="2000" displayName="Global horizontal sensor controller" sensorID="50000">
		<IBK:Parameter name="MaxIntensity" unit="W/m2">300</IBK:Parameter>
		<IBK:Parameter name="MinIntensity" unit="W/m2">150</IBK:Parameter>
	</ShadingControlModel> 
</Models>
----
====

Das Verschattungskontrollmodell verlangt 2 Parameter `MaxIntensity` und `MinIntensity` und implementiert eine digitale Regelung mit Hysterese. Zunächst muss die Globalstrahlungsintensität auf den Sensor den oberen Grenzwert überschreiten `MaxIntensity`, wonach die Verschattung geschlossen wird (Kontrollmodell liefert 1). Danach muss die Strahlungsintensität zunächst unter die untere Grenze sinken (`MinIntensity`), bevor die Verschattung wieder geöffnet wird (Kontrollmodell liefert 0).

Für die Auswertung wird eine Horizontalstrahlung benötigt. Dafür muss eine Oberfläche ausgewählt werden und als `sensorID` angegeben werden. Möglich sind hier 3 Optionen:

- allgemeiner Sensor auf einer Fläche (siehe <<location_sensors>>)
- ID eines Fensters (eigentlich ID des _embedded object_, welches das Fenster enthält); hier wird die Globalstrahlung durch das Fenster als Eingangsgröße verwendet, einschließlich eventueller externer Verschattung bzw. Eigenverschattung 
- ID einer opaquen Fläche; hier wird die Globalstrahlung auf eine opaque Fläche als Eingangsgröße verwendet, einschließlich eventueller externer Verschattung bzw. Eigenverschattung 

Damit diese IDs eindeutig auflösbar sind, müssen Sensoren, Fenster und Konstruktionen global eindeutige IDs tragen.


## Modell für interne Lasten

Das interne Lastenmodell wird verwendet, um die Wärmelasten von Geräten, Personen und Beleuchtung für Zonen zu definieren. Interne Lasten werden genauso definiert wie natürliche Lüftungsmodelle. Der Objektlisten-tag `ZoneObjectList` identifiziert die Zonen, in denen interne Lasten berücksichtigt werden sollen.
Es dürfen nicht zwei interne Lastmodelle existieren, die sich auf dieselben Zonen beziehen (nur eine interne Last pro Zone).

.Definitionsblock für interne Lasten
====
[source,xml]
----
<InternalLoadsModel id="200" modelType="Scheduled">
	<ZoneObjectList>Office zones</ZoneObjectList>
	<IBK:Parameter name="RadiantFraction" unit="---">0.5</IBK:Parameter>
</InternalLoadsModel>
----
====


Das `InternalLoadsModel` muss mit den folgenden XML-Attributen definiert werden:

.Attribute
[.indent-me]
[options="header",cols="20%,60%,^ 10%,^ 10%",width="100%"]
|====================
| Attribut | Beschreibung | Format | Verwendung 
| `id` | Kennung des Modells | {nbsp}>{nbsp}0{nbsp} | _erforderlich_

| `modelType` 
a| Gibt an, wie die internen Lasten angesetzt werden sollen

* `Constant` - Konstante Geräte-, Personen- und Beleuchtungsenergielasten
* `Scheduled` - Lasten werden über Zeitplanparameter bereitgestellt.

| key | _erforderlich_
|====================


Fließkommaparameter (siehe Abschnitt <<IBK_Parameter>> für eine Beschreibung des Tags `IBK:Parameter`):

[options="header",cols="20%,^ 15%,35%,^ 20%,^ 10%",width="100%"]
|====================
|Name|Vorgabeeinheit|Beschreibung|Wertebereich |Verwendung
| `EquipmentHeatLoadPerArea` | W/m2 | Komplette Gerätebelastung pro Zonennutzfläche | {nbsp}>={nbsp}0.0{nbsp} | _erforderlich für Konstantes Modell_
| `PersonHeatLoadPerArea` | W/m2 | Komplette Personenwärmelast pro Zonennutzfläche | {nbsp}>={nbsp}0.0{nbsp} | _erforderlich für Konstantes Modell_
| `LightingHeatLoadPerArea` | W/m2 | Komplette Wärmelast aus Beleuchtung pro Zonennutzfläche | {nbsp}>={nbsp}0.0{nbsp} | _erforderlich für Konstantes Modell_
| `EquipmentRadiationFraction` | --- | Prozentualer Anteil der Wärme der Geräte, der durch Strahlung emittiert wird | {nbsp}>={nbsp}0.0{nbsp} | _erforderlich_
| `PersonRadiationFraction` | --- | Prozentualer Anteil der Wärme der Personen, der durch Strahlung emittiert wird | {nbsp}>={nbsp}0.0{nbsp} | _erforderlich_
| `LightingRadiationFraction` | --- | Prozentualer Anteil der Wärme der Beleuchtung, der durch Strahlung emittiert wird | {nbsp}>={nbsp}0,0{nbsp} | _erforderlich_
|====================

[NOTE]
====
Die Zonennutzfläche ist nicht zwingend die Grundfläche einer Zone sondern wird aus dem Parameter _Area_ der Zonendefinition gewählt. Dadurch ist es möglich, z.B. im Dachgeschoss mit Schrägen die tatsächlich nutzbare Fläche zu definieren verwenden. Deshalb wird der _Area_ Parameter in allen Zonen benötigt, für die ein `InternalLoadsModel` angewendet werden soll.
====

Der Modelltyp `Constant` übernimmt die internen Lasten aus den Parametern (siehe oben).
Wenn der Modelltyp `Scheduled` verwendet wird, werden die tatsächlichen Lasten aus dem Zeitplan entnommen.

Die folgenden Zeitplanparameter sind erforderlich:

- `EquipmentHeatLoadPerAreaSchedule [W/m2]`
- `PersonHeatLoadPerAreaSchedule [W/m2]`
- `LightingHeatLoadPerAreaSchedule [W/m2]`

Die zonenspezifischen Ausgangsgrößen heißen: 

- `ConvectiveEquipmentHeatLoad [W]`
- `ConvectivePersonHeatLoad [W]`
- `ConvectiveLightingHeatLoad [W]`
- `RadiantEquipmentHeatLoad [W]`
- `RadiantPersonHeatLoad [W]`
- `RadiantLightingHeatLoad [W]`

Dies sind vektoriell dargestellte Größen, die in Ausgangsdefinitionen referenziert werden müssen, z. B. mit: `ConvectiveEquipmentHeatLoad[id=3]` für die konvektive Gerätelast in Zone #3.


Die Parameter `xxxRadiationFraction` geben an, welcher Prozentsatz der berechneten internen Lasten als Strahlungsfluss flächengewichtet auf opake Oberflächen, die die Zone umschließen, aufgebracht werden soll. 


[[ZoneControlThermostat]]
## Modell für Thermostate

Das Thermostatmodell beschreibt, auf welche Raumsollwerte konditioniert werden soll. Angegeben werden können Heiz- und/oder Kühlsolltemperaturen für die Raumluft oder operative Raumluft.
Der Objektlisten-tag `ZoneObjectList` identifiziert die Zonen, in denen Thermostate berücksichtigt werden sollen. Es darf nur ein Modell pro Zone existieren.

.Definitionsblock für Thermostate
====
[source,xml]
----
<ZoneControlThermostat id="200" modelType="Scheduled">
	<ZoneObjectList>Office zones</ZoneObjectList>
	<IBK:Parameter name="HeatingSetpoint" unit="C">20</IBK:Parameter>
	<IBK:Parameter name="CoolingSetpoint" unit="C">21</IBK:Parameter>
	<TemperatureType>AirTemperature</TemperatureType>
</ZoneControlThermostat>
----
====


Das `ZoneControlThermostat` muss mit den folgenden XML-Attributen definiert werden:

.Attribute
[.indent-me]
[options="header",cols="20%,60%,^ 10%,^ 10%",width="100%"]
|====================
| Attribut | Beschreibung | Format | Verwendung 
| `id` | Kennung des Modells | {nbsp}>{nbsp}0{nbsp} | _erforderlich_

| `modelType` 
a| Gibt an, wie die Thermostat-Parameter angesetzt werden sollen

* `Constant` - Konstante Sollwerte
* `Scheduled` - Sollwerte werden über Zeitplanparameter bereitgestellt.

| key | _erforderlich_
|====================


Fließkommaparameter (siehe Abschnitt <<IBK_Parameter>> für eine Beschreibung des Tags `IBK:Parameter`):

[options="header",cols="20%,^ 15%,35%,^ 20%,^ 10%",width="100%"]
|====================
|Name|Vorgabeeinheit|Beschreibung|Wertebereich |Verwendung
| `HeatingSetpoint` | C | konstanter Heizsollwert | {nbsp}<`CoolingSetpoint` | _erforderlich für Konstantes Modell_
| `CoolingSetpoint` | C | konstanter Kühlsollwert | {nbsp}>`HeatingSetpoint` | _erforderlich für Konstantes Modell_
|====================

### TemperatureType

Der XML-tag `TemperatureType` enthält eine Zeichenkette zur Auswahl eines bestimmten Typs (`AirTemperature` wird standardmäßig verwendet, wenn das tag fehlt).

.verfügbare TemperatureTypes
[options="header", cols="20%, 80%", width="100%"]
|====================
|Name|Beschreibung
|`AirTemperautre`| Als Referenztemperatur wird die Raumlufttempatur verwendet.
|`OperativeTemperature`| Als Referenztemperatur wird die operative Raumlufttempatur verwendet. Diese setzt sich aus der mittleren Oberflächentemperatur aller Innenoberflächen und aus der Raumlufttemperatur zusammen. Die Anteile betragen jeweils 50%.
|====================

[NOTE]
====
Ein Thermostat hält nur die Sollwerte für die Zone. Eine Konditionierung der Zone erfolgt erst wenn zusätzlich eine Heizungs- und/oder Kühlmodell für die Zone integriert ist. Auch bei den Zeitplänen ist immer darauf zu achten, dass der Heizsollwert < Kühlsollwert ist.
====

Der Modelltyp `Constant` übernimmt die Sollwerte aus den Parametern (siehe oben).
Wenn der Modelltyp `Scheduled` verwendet wird, werden die tatsächlichen Sollwerte aus dem Zeitplan entnommen.

Die folgenden Zeitplanparameter sind erforderlich:

- `HeatingSetpointSchedule [C]`
- `CoolingSetpointSchedule [C]`

Die zonenspezifischen Ausgangsgrößen heißen: 

- `HeatingSetpoint [C]`
- `CoolingSetpoint [C]`

Dies sind vektoriell dargestellte Größen, die in Ausgangsdefinitionen referenziert werden müssen, z. B. mit: `HeatingSetpoint[id=3]` für den Heizsollwert in Zone #3.

## Modell für Ideale thermische Konditionierung

Das Modell beschreibt ein ideles thermisches Konditionierungsmodell für eine ideale Raumluftkonditionierung.
Der Objektlisten-tag `ZoneObjectList` identifiziert die Zonen, in denen das Modell berücksichtigt werden sollen. Es darf nur ein Modell pro Zone existieren.

.Definitionsblock für Ideale thermische Konditionierung
====
[source,xml]
----
<ZoneIdealHeatingCooling id="200">
	<ZoneObjectList>Office zones</ZoneObjectList>
	<IBK:Parameter name="HeatingPowerPerArea" unit="W/m2">50</IBK:Parameter>
	<IBK:Parameter name="CoolingPowerPerArea" unit="W/m2">20</IBK:Parameter>
</ZoneIdealHeatingCooling>
----
====


Das `ZoneIdealHeatingCooling` muss mit den folgenden XML-Attributen definiert werden:

.Attribute
[.indent-me]
[options="header",cols="20%,60%,^ 10%,^ 10%",width="100%"]
|====================
| Attribut | Beschreibung | Format | Verwendung 
| `id` | Kennung des Modells | {nbsp}>{nbsp}0{nbsp} | _erforderlich_
|====================


Fließkommaparameter (siehe Abschnitt <<IBK_Parameter>> für eine Beschreibung des Tags `IBK:Parameter`):

[options="header",cols="20%,^ 15%,35%,^ 20%,^ 10%",width="100%"]
|====================
|Name|Vorgabeeinheit|Beschreibung|Wertebereich |Verwendung
| `HeatingPowerPerArea` | W/m2 | konstante max. Flächenheizlast | {nbsp}>={nbsp}0.0{nbsp} | _erforderlich für Konstantes Modell_
| `CoolingPowerPerArea` | W/m2 | konstante max. Flächenheizlast | {nbsp}>={nbsp}0.0{nbsp} | _erforderlich für Konstantes Modell_
|====================

[NOTE]
====
Damit das Modell auf die jeweilige Zone angewendet wird, ist zwingend das <<ZoneControlThermostat>> nötig.
====

Die zonenspezifischen Ausgangsgrößen heißen: 

- `IdealHeatingLoad [W]`
- `IdealCoolingLoad [W]`

Dies sind vektoriell dargestellte Größen, die in Ausgangsdefinitionen referenziert werden müssen, z. B. mit: `IdealHeatingLoad[id=3]` für die Heizlast in Zone #3.
