:imagesdir: ./images
[[schedules]]
# Schedules

## Overview

Schedules provide purely time-dependent quantities, similar to climatic loads. Different to other results-producing models, schedules generate variables for sets of dependent models. As such, a schedule is formulated for an object list, which selects a set of objects taking the values provided by the schedule.
For example they are used in the following objects or list of objects:

* **Occupancy rates**, **heat loads**, *clothing factors* in the person load model.
* *Heating/cooling set point temperatures* for thermostat controls
* *Mass flow rates* or temperature set points for plant components
* *electrical power rates* for lighting and electrical devices

For example, a schedule defines heating set points `HeatingSetPoint` for specific zones like living rooms. These are selected by an object list named "Living room", which selects objects with the type `Zone` and a certain ID range. Later you will find more about this in more detail.

Within the project file there are two possible ways to describe a schedule: 

* `ScheduleGroups` 
* `AnnualSchedules`. 

The two options are discussed in <<regularSchedules>> and <<annualSchedules>>. 

Furthermore `Schedules` consist of two different types of data handling:

* *Cyclic* data
* *Non-cyclic* data

Cyclic data means that schedule values will be repeated after the schedule period. That means for example that an annual schedule will be run twice if the simulation time will be set to two years.
Whereas non-cyclic data will always be used only once. This is useful if monitored data will be used to set up schedules and we the simulation time will be only valid fo the time the monitored data is existing.

Furthermore individual schedule can also hold a

[[regularSchedules]]
## Regular schedules (based on daily cycles)

Regular schedules are defined upon a daily cycle based scheme. As in <<ScheduleTypes>> showed, a priority list exists that defines on how to define a yearly schedule. At first priority the type `Alldays` will set a specified daily values to the whole year. After this the `type` named `WeekEnd` and `WeekDay` will overwrite the already defined values for only all weekdays or weekends. Furthermore the weekdays named `Monday`, `Tuesday`, etc define for which days the values will be overwritten again. This continues with the `type` `Holiday`. So that in the end a final schedule for the whole year will be defined. 

Regular schedules are defined within the XML tag `scheduleGroup` with an XML attribute named `objectList` that references an `ObjectList` with the specified name. Inside the object an XML tag named `Schedule` needs to be defined with an XML attribute `type`. This `type` can have several names.

.ScheduleGroup Definition
====
[source,xml,indent=0]
----
				<ScheduleGroup objectList="Zone">
					<!-- AllDays constant  -->
					<Schedule type="AllDays">
						<DailyCycles>
							<DailyCycle interpolation="Constant">
								<TimePoints>0</TimePoints>
								<Values>InfiltrationRateSchedule [1/h]:0</Values>
							</DailyCycle>
						</DailyCycles>
					</Schedule>
				</ScheduleGroup>
----

====

.ObjectList with an Zone linked
====
[source,xml,indent=0]
----
		<ObjectLists>
			<ObjectList name="Zone">
				<FilterID>*</FilterID>
				<ReferenceType>Zone</ReferenceType>
			</ObjectList>
		</ObjectLists>
----

====

[[ScheduleTypes]]
.Description of schedule group type
[options="header"]
[cols=" ^, ^ "]
[width="40%"]
|====================
| `type` | Priority
| AllDays {set:cellbgcolor:   #fef9e7  } 
| 0 
| WeekEnd {set:cellbgcolor: #fcf3cf  } 
| 1
| WeekDay | 1
| Monday {set:cellbgcolor: #f9e79f }  
| 2
| Tuesday | 2
| Wednesday | 2
| Thursday | 2
| Friday | 2
| Saturday | 2
| Sunday | 2
| Holiday {set:cellbgcolor: #f7dc6f } 
| 3
|====================

[[annualSchedules]]
## Annual schedules (as linearly interpolated splines)

Annual schedules are basically data tables with 


## Variable list

The variable list describes all names and the  units that can be used in the schedules. 

[options="header",cols="35%,^ 10%,55%"]
|====================
|Name {set:cellbgcolor:transparent}
|Unit|Description
|HeatingSetPointTemperature|C|Setpoint temperature for heating.
|CoolingSetPointTemperature|C|Setpoint temperature for cooling.
|AirConditionSetPointTemperature|C|Setpoint temperature for air conditioning.
|AirConditionSetPointRelativeHumidity|%|Setpoint relative humidity for air conditioning.
|AirConditionSetPointMassFlux|kg/s|Setpoint mass flux for air conditioning.
|HeatingLoad|W|Heating load.
|ThermalLoad|W|Thermal load (positive or negative).
|MoistureLoad|g/h|Moisture load.
|CoolingPower|W|Cooling power.
|LightingPower|W|Lighting power.
|DomesticWaterSetpointTemperature|C|Setpoint temperature for domestic water.
|DomesticWaterMassFlow|kg/s|Domestic water demand mass flow for the complete zone (hot water and equipment).
|ThermalEnergyLossPerPerson|W/Person|Energy of a single persons activities that is not available as thermal heat.
|TotalEnergyProductionPerPerson|W/Person|Total energy production of a single persons body at a certain activity.
|MoistureReleasePerPerson|kg/s|Moisture release of a single persons body at a certain activity.
|CO2EmissionPerPerson|kg/s|CO2 emission mass flux of a single person at a certain activity.
|MassFluxRate|---|Fraction of real mass flux to maximum  mass flux for different day times.
|PressureHead|Pa|Supply pressure head of a pump.
|OccupancyRate|---|Fraction of real occupancy to maximum  occupancy for different day times.
|EquipmentUtilizationRatio|---|Ratio of usage for existing electric equipment.
|LightingUtilizationRatio|---|Ratio of usage for lighting.
|MaximumSolarRadiationIntensity|W/m2|Maximum solar radiation intensity before shading is activated.
|UserVentilationAirChangeRate|1/h|Exchange rate for natural ventilation.
|UserVentilationComfortAirChangeRate|1/h|Maximum air change rate = offset for user comfort.
|UserVentilationMinimumRoomTemperature|C|`Temperature limit over which comfort ventilation is activated.`
|UserVentilationMaximumRoomTemperature|C|`Temperature limit below which comfort ventilation is activated.`
|InfiltrationAirChangeRate|1/h|Exchange rate for infiltration.
|ShadingFactor|---|Shading factor [0...1].

|====================

