:imagesdir: ./images

[[models]]
# Model Parametrization

This section describes the various model parametrization blocks.

## Natural Ventilation Model (Infiltration)

A natural ventilation/infiltration model defines air exchange with the outside air. Natural ventilation can be enabled for specific zones by defining a `NaturalVentilationModel` model parameter block. Via the object list, the zones with natural ventilation are selected.

====
[source,xml]
----
<NaturalVentilationModel id="501" displayName="Zone vent" modelType="Constant">
	<ZoneObjectList>Office zones</ZoneObjectList>
	<IBK:Parameter name="VentilationRate" unit="1/h">0.5</IBK:Parameter>
</NaturalVentilationModel>
<NaturalVentilationModel id="502" displayName="Zone vent" modelType="Scheduled">
	<ZoneObjectList>Other zones</ZoneObjectList>
</NaturalVentilationModel>
----
====

[IMPORTANT]
====
There must be only one natural ventilation model block defined for a zone. Hence, you must not define two ventilation model blocks with object lists that both contain the same zone(s).
====

The `NaturalVentilationModel` needs to be defined with the following XML attributes:

.Attributes
[.indent-me]
[options="header",cols="20%,60%,^ 10%,^ 10%",width="100%"]
|====================
| Attribute  | Description | Format | Usage 
| `id` |  Identifier of the natural ventilation model | {nbsp}>{nbsp}0{nbsp} | _required_

| `modelType` 
a|  Sets the type of the ventilation model 

* `Constant` - Constant air change rate
* `Scheduled` - Air change rate changes accoring to defined schedule

| key | _required_
|====================


Floating point parameters (see section <<IBK_Parameter>> for a description of the `IBK:Parameter` tag):

[options="header",cols="20%,^ 15%,35%,^ 20%,^ 10%",width="100%"]
|====================
|Name|Default Unit|Description|Value Range |Usage
| `VentilationRate` | 1/h | Constant air change rate | {nbsp}>={nbsp}0.0{nbsp} | _required for Constant model_
|====================

If the model type `Scheduled` is being used, no further parameters are required, since the air change rate is taken from a scheduled parameter.

For the model to work, the parameter `InfiltrationRateSchedule` must be defined in a schedule (see <<schedules>>).

Below is an example of a schedule that provides the `InfiltrationRateSchedule` for such a scheduled natural ventilation model:

.Example schedule that provides a InfiltrationRateSchedule parameter
====
[source,xml]
----
<ScheduleGroup objectList="All zones">
	<!-- every day between 8-10 -->
	<Schedule type="AllDays">
		<DailyCycles>
			<DailyCycle interpolation="Constant">
				<TimePoints>0 6 10</TimePoints>
				<Values>InfiltrationRateSchedule [1/h]:0 0.4 0</Values>
			</DailyCycle>
		</DailyCycles>
	</Schedule>
	<!-- Tuesday no ventilation -->
	<Schedule type="Tuesday">
		<DailyCycles>
			<DailyCycle interpolation="Constant">
				<TimePoints>0</TimePoints>
				<Values>InfiltrationRateSchedule [1/h]:0</Values>
			</DailyCycle>
		</DailyCycles>
	</Schedule>
	<!-- Weekend only on afternoon -->
	<Schedule type="WeekEnd">
		<DailyCycles>
			<DailyCycle interpolation="Constant">
				<TimePoints>0 14 16</TimePoints>
				<Values>InfiltrationRateSchedule [1/h]:0 0.1 0</Values>
			</DailyCycle>
		</DailyCycles>
	</Schedule>
</ScheduleGroup>
----
====


## Shading Control Model

A shading control model is a special type of control model, returning a signal value between 0 (no shading) and 1 (fully shaded). The actual amount of shading, or reduction of solar gains, is determined by the shading parameter block. Thus, you can use the same control model for different types of shadings.

.Parameter definition for shading control model
[source,xml, indent=0]
====
----
<Models>
	<!-- ShadingControlModel returns a value between 0 and 1 
		0 = no reduction (shading open)
		1 = full reduction (shading closed)
	-->
	<ShadingControlModel id="555" displayName="Roof sensor" modelType="SingleIntensityControlled">
		<!-- Retrieves global radiation on given sensor. -->
		<SensorID>21</SensorID>
		<IBK:Parameter name="MaxIntensity" unit="W/m2">200</IBK:Parameter>
		<IBK:Parameter name="MinIntensity" unit="W/m2">100</IBK:Parameter>
		<!-- Shading control model returns 1 for values below Min, and 0 for values above Max.
			Switching is only allowed if Max/Min has been passed (hysteretic control).
		-->
	</ShadingControlModel>
</Models>
----
====


## Internal Loads Model

The internal loads model is used to define equipment, person and lighting heat loads for zones. Internal loads are defined just as natural ventilation models. The object list tag `ZoneObjectList` identifies the zones, where internal loads shall be considered.
You must not have two internal load models which reference the same zones (only one internal load per zone).

.Example for a internal loads model
====
[source,xml]
----
<InternalLoadsModel id="200" modelType="Scheduled">
	<ZoneObjectList>Office zones</ZoneObjectList>
	<IBK:Parameter name="RadiantFraction" unit="---">0.5</IBK:Parameter>
</InternalLoadsModel>
----
====


The `InternalLoadsModel` needs to be defined with the following XML attributes:

.Attributes
[.indent-me]
[options="header",cols="20%,60%,^ 10%,^ 10%",width="100%"]
|====================
| Attribute  | Description | Format | Usage 
| `id` |  Identifier of the natural ventilation model | {nbsp}>{nbsp}0{nbsp} | _required_

| `modelType` 
a|  Indicates how internal loads are to be applied

* `Constant` - Constant equipment, person and lighting energy loads
* `Scheduled` - Loads are provided via schedule parameters.

| key | _required_
|====================


Floating point parameters (see section <<IBK_Parameter>> for a description of the `IBK:Parameter` tag):

[options="header",cols="20%,^ 15%,35%,^ 20%,^ 10%",width="100%"]
|====================
|Name|Default Unit|Description|Value Range |Usage
| `EquipmentHeatLoadPerArea` | W/m2 | Complete equipment load per zone floor area | {nbsp}>={nbsp}0.0{nbsp} | _required for Constant model_
| `PersonHeatLoadPerArea` | W/m2 | Complete equipment load per zone floor area | {nbsp}>={nbsp}0.0{nbsp} | _required for Constant model_
| `LightingHeatLoadPerArea` | W/m2 | Complete equipment load per zone floor area | {nbsp}>={nbsp}0.0{nbsp} | _required for Constant model_
| `EquipmentRadiationFraction` | --- | Percentage of equipment load that is radiant emitted | {nbsp}>={nbsp}0.0{nbsp} | _required_
| `PersonRadiationFraction` | --- | Percentage of equipment load that is radiant emitted | {nbsp}>={nbsp}0.0{nbsp} | _required_
| `LightingRadiationFraction` | --- | Percentage of equipment load that is radiant emitted | {nbsp}>={nbsp}0.0{nbsp} | _required_
|====================

The model type `Constant` takes the internal loads from the parameters (see above).
If the model type `Scheduled` is being used, the actual loads are taken from the schedule.

The following schedule parameters are required:

- `EquipmentHeatLoadPerAreaSchedule [W/m2]`
- `PersonHeatLoadPerAreaSchedule [W/m2]`
- `LightingHeatLoadPerAreaSchedule [W/m2]`

Both, scheduled and constant internal load parameteres are relative to the usage area, defined as zone parameter `Area`, which is required once an `InternalLoadsModel` has been defined. Hence, the computed internal loads are different if the zone's usage area differs. The zone-specific output quantities are named: 

- `ConvectiveEquipmentHeatLoad [W]`
- `ConvectivePersonHeatLoad [W]`
- `ConvectiveLightingHeatLoad [W]`
- `RadiantEquipmentHeatLoad [W]`
- `RadiantPersonHeatLoad [W]`
- `RadiantLightingHeatLoad [W]`

These are vector-valued quantities are need to be referenced in output definitions, for example, with: `ConvectiveEquipmentHeatLoad[id=3]` for the convective equipment load in zone #3.



The `xxxRadiationFraction` parameters indicate which percentage of the computed internal loads are to be imposed as radiative flux, area-weighted onto opaque surfaces that enclose the zone. 

