# Outputs: definitions, rules and implementation

## Output definitions

Outputs are defined via:

- Grid (defines when outputs are to be written)
- Variable/Quantity ID name
- Object List (selects object to retrieve data from)
- Time handling (how to handle time averaging/integration)
- (optional) target filename

Example:
[source,xml]
----
<!-- Definition of output grids -->
<Grids>
	<OutputGrid name="hourly">
		<Intervals>
			<Interval>
				<IBK:Parameter name="StepSize" unit="h">1</IBK:Parameter>
			</Interval>
		</Intervals>
	</OutputGrid>
</Grids>
<!-- Definition of outputs -->
<OutputDefinitions>
    <OutputDefinition>
    	<Quantity>Temperature</Quantity>
    	<ObjectListName>All zones</ObjectListName>
    	<GridName>hourly</GridName>
    </OutputDefinition>
    <OutputDefinition>
    	<Quantity>NaturalVentilationFlux</Quantity>
    	<ObjectListName>All zones</ObjectListName>
    	<GridName>hourly</GridName>
    	<TimeType>Integral</TimeType>
    </OutputDefinition>
</OutputDefinitions>


<!-- Referenced object list -->
<ObjectLists>
	<ObjectList name="All zones">
		<FilterID>*</FilterID>
		<ReferenceType>Zone</ReferenceType>
	</ObjectList>
</ObjectLists>
----

`TimeType` is optional, same as `None` by default.
`FileName` is optional (see below).

### Output Grids

Output grids define _when_ outputs are written. An output grid contains a list of intervals, with an output step size defined for each interval.

The intervals are expected to follow in consecutive order, optionally with a gap in-between.

Intervals can have up to 3 parameters:

* `Start` - the start time of the interval (see explanation below)
* `End`- the end time of the interval (see explanation below)
* `StepSize` - the distance between outputs within the interval

#### Time definitions

Time points in `Start` and `End` parameters are defined with respect to Midnight January 1st of the year in which the simulation starts.



#### Rules

- the `Start` parameter is optional, under the following conditions:
    * in the first interval, a missing `Start` parameter is automatically set to 0 (start of the year)
    * in all other intervals, the `End` time of the preceeding interval is taken (see next rule below)
- the end time of an interval is defined, either:
    * by defining the `End` parameter,
    * through definition of the `Start` parameter in next interval
    * through simulation end time in last 
das Intervall das letzte Intervall ist (in diesem Fall läuft das Interval bis zum Simulationsende)
das darauffolgende Interval hat ein Start-Wert hat.
Bei Angabe eines Start-Parameters muß der Zeitpunkt mindestens dem End-Zeitpunkt des vorangegangenen Intervalls entsprechen -> die Intervalle sind sequentiell geordnet und überschneiden nicht.
Die Angabe des Parameters StepSize ist zwingend.


### Examples

- Requesting fluxes across construction interfaces: object list must reference interfaces
- Requesting energy supplied to layer in construction instance (floor heating): object list must reference construction instance, variable name must reference heat source + index of heat source (if several in construction): `<Quantity>HeatSource[1]</Quantity>` (first heat source in layer, counting from side A in construction, see <<construction_heat_sources, Heat sources in constructions/layers>>).


## Variable lookup rules

Quantities in output definitions define the ID names of the output quantities, optionally including an index notation when a single element of a vectorial quantity is requested. Hereby the following notations are allowed:

- `HeatSource[1]` - index argument is interpreted as defined by the providing models, so when the model provides a vector-valued quantity with model ID indexing, then the argument is interpreted as object ID (otherwise as positional index)
- `HeatSource[index=1]` - index argument is explicitely interpreted as position index (will raise an error when model provides quantity with model ID indexing)
- `HeatSource[id=1]` - index argument is explicitely interpreted as object ID (will raise an error when model provides quantity with positional indexing)


## Output file generation rules

### When no filename is given

Target file name(s) are automatically defined.

All outputs a grouped by:

- grid and quantity type (Load, Schedule, State, Flux, Misc), quantity type is predefined for most quantity IDs (unknowns -> Misc)

- for each used grid:
  - states -> `states_<gridname>.tsv`
  - loads -> `loads_<gridname>.tsv`
  - fluxes -> `fluxes_<gridname>.tsv`
  - fluxes (integrated) -> `flux_integrals_<gridname>.tsv`

Special rule: when only one grid is used, and grid has hourly steps all year round, the suffix `_<gridname>` is omitted.

### When a filename is given

- check: all output definitions using this filename must use the *same* grid (same time points for all columns required!)

- all quantities (regardless of type) are written to this file


## Binary Format

First record: unsigned int - n (number of columns)
Next n records: binary strings, leading size (unsigned int) and termination character (sanity checking)

Next ?? records: unsigned int - n (for checking) and afterwards n doubles

