:imagesdir: ./images
[[ZoneDocumentation]]
# Zones

In order to model buildings, it is necessary to define the individual rooms with the relevant parameters. 
A zone defines a thermal zone/room with a single air temperature.

The class Zone stores all properties needed to compute zone temperature from energy density (the conserved quantity).

Needed for the calculation is either the floor area and the height, or the zone volume. If all parameters are given, the volume property is computed from floor area and height.
Zones can be either Constant or Active. 
For constant zones, the temperature is assumed to
be fixed/predefined whereas in Active zones the temperature is computed (i.e. included in
the model's unknowns). A constant zone only needs the temperature parameter. If an Active zone has a temperature parameter,
this is used as initial condition.

Inside the XML-Tag named `Zones` each zone starts with the XML-Tag `Zone`. The following XML-Attributes need to be defined:

* _id:_ `1` - defines the Identifier of the Zone, needs to be a unique positive Integer ( > 0 )
* _displayName:_ `Var01` - defines the Display Name of the Zone. Is needed to find the Zone in the Data Model and in Outputs more easily.

* _type:_ `Active` - defines whether zone is balanced and included in equation system.

** `Constant` _as zone with constant/predefined temperatures. (schedule)_
** `Active` _as zone described by a temperature node in space_
** `Ground` _as ground zone (calculates temperature based on standard)_

The following XML-Tags named `IBK:Parameters` with the XML-Attributes `name` and `unit` with the following entries can be defined:

* _name:_ `Area` - defines the net usage area of the ground floor (for area-related outputs and loads), _unit:_ per Default in `m²` 
* _name:_ `Volume` - defines the Zone air volume, _unit:_ per Default in `m³` 
* _name:_ `HeatCapacity` - defines the Extra heat capacity, _unit:_ per Default in `J/kg` 
* _name:_ `Temperature` - defines the Temperature of the zone if set constant, _unit:_ per Default in `°C` 
* _name:_ `RelativeHumidity` - defines the Relative humidity of the zone if set constant, _unit:_ per Default in `%` 
* _name:_ `CO2Concentration` - defines the CO2 concentration of the zone if set constant, _unit:_ per Default in `g/m³`

.Definition of zone
====
[source,xml]
----
<Zones>
	<Zone id="1" displayName="Var01" type="Active">
		<IBK:Parameter name="Area" unit="m2">10</IBK:Parameter>
		<IBK:Parameter name="Volume" unit="m3">30</IBK:Parameter>
	</Zone>
</Zones>
----
====

[[ConstructionInstancesDocumentation]]
# Constructioninstances

The construction instances define construction-specific parameters required by several models.

The construction instances are defined inside the Sections starting with an XML-Tag `ConstructionInstances`. Inside the Section each Construction instance starts with the XML-Tag named `ConstructionInstance` with the XML-Attributes `id` and `displayName`. 
Inside that it is necessary to specify the interfaces with the XML-Tag named `InterfaceA` and `InterfaceB`. Finally the Interfaces with the XML-Tag `InterfaceA` and `InterfaceB` need to be defined with the XML-Attributes `id` and `zoneId`.
In the following it is described in detail.

* _id:_ `1` - defines the Identifier of the Construction Instance, needs to be a unique positive Integer ( > 0 )
* _displayName:_ `All Surfaces Var01` - defines the Display Name of the Construction Instance. Is needed to find the Construction Instance in the Data Model and in Outputs more easily.

The construction instance has the following `required subtag`:

* `constructionTypeId` - unique Id that defines the construction type of the construction instance

Example:
[source,xml]
----
<ConstructionTypeId>10005</ConstructionTypeId>
----

The following XML-Tags named `IBK:Parameters` with the XML-Attributes `name` and `unit` with the following entries can be defined:

* _name:_ `Orientation` - defines the Orientation of the wall, _unit:_ per Default in `deg` 
* _name:_ `Inclination` - defines the Inclination of the wall, _unit:_ per Default in `deg` 
* _name:_ `Area` - defines the Gross area of the wall, _unit:_ per Default in `m²`

Example:
[source,xml]
----
        <ConstructionInstances>
			<!-- Surface Var 01 -->
			<ConstructionInstance id="1" displayName="All Surfaces Var01">
				<ConstructionTypeId>10005</ConstructionTypeId>
				<IBK:Parameter name="Area" unit="m2">62</IBK:Parameter>
				<InterfaceA id="10" zoneId="1">
					<!--Interface to 'Room'-->
					<InterfaceHeatConduction modelType="Constant">
						<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">2.5</IBK:Parameter>
					</InterfaceHeatConduction>
				</InterfaceA>
				<InterfaceB id="11" zoneId="0">
					<!--Interface to outside-->
					<InterfaceHeatConduction modelType="Constant">
						<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">8</IBK:Parameter>
					</InterfaceHeatConduction>
				</InterfaceB>
			</ConstructionInstance>
			
		</ConstructionInstances>
----
[[InterfacesDocumentation]]
## Interfaces (construction boundary conditions)

Interfaces are defining boundary conditions and parameters for the two surfaces of a constructions instance.

The Interfaces can have the following `subtags`:

* heatConduction
** The InterfaceHeatConduction needs to be defined with the XML-Attribute `modelType`.
*** `Constant` _as constant model._
** The XML-Tags named `IBK:Parameters` with the XML-Attributes `name` and `unit` with the following entries can be defined:
*** _name:_ `HeatTransferCoefficient` - defines the constant heat transfer coefficient, _unit:_ per Default in `W/m²K`

* solarAbsorption
** The InterfaceSolarAbsorption needs to be defined with the XML-Attribute `modelType`.
*** `Constant` _as constant model._
** The XML-Tags named `IBK:Parameters` with the XML-Attributes `name` and `unit` with the following entries can be defined:
*** _name:_ `AbsorptionCoefficient` - Constant Absorption coefficient [0,...,1], _unit:_ per Default in `[-]`

* longWaveEmission
** The InterfaceLongWaveEmission needs to be defined with the XML-Attribute `modelType`.
*** `Constant` _as constant model._
** The XML-Tags named `IBK:Parameters` with the XML-Attributes `name` and `unit` with the following entries can be defined:
*** _name:_ `Emissivity` - Constant Long wave emissivity, _unit:_ per Default in `[-]`

* vaporDiffusion
** The InterfaceVaporDiffusion needs to be defined with the XML-Attribute `modelType`.
*** `Constant` _as constant model._
** The XML-Tags named `IBK:Parameters` with the XML-Attributes `name` and `unit` with the following entries can be defined:
*** _name:_ `VaporTransferCoefficient` - Vapor Transfer Coefficient, _unit:_ per Default in `s/m`
* airFlow
** The InterfaceAirFlow needs to be defined with the XML-Attribute `modelType`.
*** `WindFlow` _for use of results from external wind flow calculation._
** The XML-Tags named `IBK:Parameters` with the XML-Attributes `name` and `unit` with the following entries can be defined:
*** _name:_ `PressureCoefficient` - Pressure Coefficient, _unit:_ per Default in `[-]`


# Interfaces (construction boundary conditions)

# Ambient climate boundary conditions

# Interface between constructions and zones (internal boundary conditions)

