:imagesdir: ./images
[[zones]]
# Zones

In order to model buildings, it is necessary to define the individual rooms with the relevant parameters. A zone defines a well-mixed thermal zone/room with a single/uniform air temperature.

Objects of type `Zone` store all properties needed to compute zone temperature from energy density (the conserved quantity).

.Zone Definition
====
[source,xml,indent=0]
----
<Zones>
	<Zone id="1" displayName="Var01" type="Active">
		<IBK:Parameter name="Area" unit="m2">10</IBK:Parameter>
		<IBK:Parameter name="Volume" unit="m3">30</IBK:Parameter>
	</Zone>
</Zones>
----
====

Inside the XML tag named `Zones` each zone starts with the XML tag `Zone`. The following XML attributes need to be defined:

[source,xml]
----
<Zone id="1" displayName="Var01" type="Active">
----

[options="header",cols="20%,60%,^ 10%,^ 10%",width="100%"]
|====================
| Attribute  | Description | Format | Usage 
| `id` |  Identifier of the Zone | ({nbsp}>{nbsp}0{nbsp})  | _required_
| `displayName`  |  Display name of the zone. Is needed to find the zone in the data model and in outputs more easily. | string | _optional_
| `type`  
a|  Defines whether zone is balanced and included in equation system.

* `Constant` as zone with constant/predefined temperatures. (schedule)
* `Active` as zone described by a temperature node in space
* `Ground` as ground zone (calculates temperature based on standard) | key | _required_

|====================

For _Constant_ zones, the temperature is assumed to
be fixed/predefined whereas in _Active_ zones the temperature is computed (i.e. included in
the model's unknowns). A _Constant_ zone only needs the temperature parameter.

Parameters (see section <<IBK_Parameter>> for a description of the `IBK:Parameter` tag):

[options="header",cols="18%,^ 15%,38%,^ 20%,^ 10%",width="100%"]
|====================
|Name|Unit|Description|Value Range |Usage
| `Volume` | m3 | Zone air volume | {nbsp}>{nbsp}0.0{nbsp} | _required_
| `Area` | m2 | Net usage area of the ground floor (for area-related outputs and loads) | {nbsp}>{nbsp}0.0{nbsp} | _optional_
| `HeatCapacity` | J/K | Additional heat capacity (furniture, etc.) | {nbsp}>={nbsp}0.0{nbsp} | _optional_
| `Temperature` | C | Temperature of the zone

only used if `Constant` | -70...120 | (_required_)

| `RelativeHumidity` | % | Relative humidity of the zone

only used if `Constant` | 0...100 | (_required_)

| `CO2Concentration` | g/m3 | CO2 concentration of the zone

only used if `Constant` | {nbsp}>{nbsp}0.0{nbsp} | (_required_)
|====================

[NOTE]
====
The parameters `RelativeHumidity` and `CO2Concentration` only need to be defined for _constant_ zones, when the respective balance equation is enabled.
====


[[construction_instances]]
# Construction Instances

Construction instances represent actually built one-dimensional parts of the building envelope, e.g. walls, floors, ceilings, roofs. The construction instance definition contains construction-specific parameters required by several models.

.Definition of an Outside Wall with only Heat Conduction Boundary Condition
====
[source,xml,indent=0]
----
<ConstructionInstances>
	<!-- Surface Var 01 -->
	<ConstructionInstance id="1" displayName="All Surfaces Var01">
		<ConstructionTypeId>10005</ConstructionTypeId>
		<IBK:Parameter name="Area" unit="m2">62</IBK:Parameter>
		<InterfaceA id="10" zoneId="1">
			<!--Interface to 'Room'-->
			<InterfaceHeatConduction modelType="Constant">
				<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">2.5</IBK:Parameter>
			</InterfaceHeatConduction>
		</InterfaceA>
		<InterfaceB id="11" zoneId="0">
			<!--Interface to outside-->
			<InterfaceHeatConduction modelType="Constant">
				<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">8</IBK:Parameter>
			</InterfaceHeatConduction>
		</InterfaceB>
	</ConstructionInstance>
</ConstructionInstances>
----
====


The construction instances are defined inside the XML tag `ConstructionInstances`. Inside the section each construction definition starts with the XML tag named `ConstructionInstance` with attributes `id` and `displayName`. 

[options="header",cols="20%,60%,^ 10%,^ 10%",width="100%"]
|====================
| Attribute  | Description | Format | Usage 
| `id` |  Identifier of the construction instance | {nbsp}>{nbsp}0{nbsp} | _required_
| `displayName`  |  Display name of the construction instance. Is needed to find the construction instance in the data model and in outputs more easily. | string | _optional_
|====================

The construction instance has the following _required_ child tag:

* `constructionTypeId` - unique Id that defines the construction type of the construction instance

Example:
[source,xml]
----
<ConstructionTypeId>10005</ConstructionTypeId>
----

The following XML tags named `IBK:Parameters` with the XML attributes `name` and `unit` with the following entries can be defined:

[options="header",cols="15%,^ 10%,45%,^ 20%,^ 10%",width="100%"]
|====================
| Name | Unit | Description | Value Range | Usage 
| `Orientation` | Deg | Orientation of the wall

if one interface has solar (short wave) radiation boundary condition it is _required_  | 0...360 | _required_ / _optional_
| `Inclination` | Deg 
a| Inclination of the wall

* 0 Deg - roof
* 90 Deg - vertical wall
* 180 Deg - facing downwards) 

if one interface has short and/or long wave radiation boundary condition it is _required_ | 0...180 | _required_ / _optional_
| `Area` | m2 | Gross area of the wall (including potentially existing windows, holes etc.) | > 0 m2 | _required_
|====================

Inside that it is necessary to specify the interfaces with the XML tag named `InterfaceA` and `InterfaceB`. Finally the Interfaces with the XML tag `InterfaceA` and `InterfaceB` need to be defined with the XML attributes `id` and `zoneId`.
In the following it is described in detail.

[[construction_discretization]]
## Spatial Discretization (Finite Volume Method)

During calculation, each of the constructions is spatially discretized using a grid generation algorithm. This algorithm uses three influential parameters, defined in the <<solver_parameters>> section:

- `DiscMinDx`
- `DiscDetailLevel`
- `DiscMaxElementsPerLayer`

TODO - Andreas - add sketch about different discretization results depending on parameters


[[construction_interfaces]]
# Interfaces (construction boundary conditions)

Interfaces are defining boundary conditions and parameters for the one or two surfaces `InterfaceA` and `InterfaceB` of a constructions instance. If the construction instance defines an adiabatic wall only one interface is needed. All other cases require two interfaces. The `InterfaceA` links the first material layer from the construction type with the assigned zone via the `zoneId`. The `InterfaceB` links the last material layer from the construction type with the `zoneId` of `InterfaceB`. 

.Interface Definitions for a Construction with Interfaces for either Side
====
[source,xml]
----
<ConstructionInstance id="1" displayName="All Surfaces Var01">
    ...
    <InterfaceA id="10" zoneId="1">
    	<InterfaceHeatConduction modelType="Constant">
    		<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">2.5</IBK:Parameter>
    	</InterfaceHeatConduction>
    </InterfaceA>
    <InterfaceB id="11" zoneId="0">
    	<InterfaceHeatConduction modelType="Constant">
    		<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">8</IBK:Parameter>
    	</InterfaceHeatConduction>
        <InterfaceSolarAbsorption model="Constant">
            <IBK:Parameter name="AbsorptionCoefficient" unit="---">0.6</IBK:Parameter>
        </InterfaceSolarAbsorption>
        <InterfaceLongWaveEmission model="Constant">
            <IBK:Parameter name="Emissivity" unit="---">0.9</IBK:Parameter>
        </InterfaceLongWaveEmission>
    </InterfaceB>
</ConstructionInstance>
----
====

`InterfaceA` and `InterfaceB` may have one or more child tags.

## Heat Conduction

The convective heat conduction over the interface is described by the XML tag `InterfaceHeatConduction`.

image::convection.svg[width=40%]

.Parameter Definition for Heat Conduction Boundary Condition
====
[source,xml]
----
<InterfaceHeatConduction modelType="Constant">
  <IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">2.5</IBK:Parameter>
</InterfaceHeatConduction>
----
====

The `InterfaceHeatConduction` needs to be defined with the following XML attribute `modelType`.

.Attributes
[.indent-me]
[options="header",cols="20%,60%,^ 10%,^ 10%",width="100%"]
|====================
| Attribute  | Description | Format | Usage 
| `modelType` 
a|  Sets the type of the heat conduction model 

* `Constant` - Constant model used (currently the only option)

| key | _required_
|====================


Floating point parameters (see section <<IBK_Parameter>> for a description of the `IBK:Parameter` tag):

[options="header",cols="20%,^ 15%,35%,^ 20%,^ 10%",width="100%"]
|====================
|Name|Default Unit|Description|Value Range |Usage
| `HeatTransferCoefficient` | W/m2K | Constant convective heat transfer coefficient | {nbsp}>{nbsp}0.0{nbsp} | _required_
|====================

## Solar Absorption

The solar absorption over the interface is described by the XML tag `InterfaceSolarAbsorption`. This coefficient describes the solar short wave radiation that is absorpt by the interface.

image::shortwave.svg[width=40%]

.Parameter Definition for Solar Absorption Boundary Condition
====
[source,xml]
----
<InterfaceSolarAbsorption modelType="Constant">
  <IBK:Parameter name="AbsorptionCoefficient" unit="---">0.6</IBK:Parameter>
</InterfaceHeatConduction>
----
====

The `InterfaceSolarAbsorption` needs to be defined with the following XML attribute `modelType`.

.Attributes
[options="header",cols="20%,60%,^ 10%,^ 10%",width="100%"]
|====================
| Attribute  | Description | Format | Usage 
| `modelType` 
a|  Sets the type of the heat conduction model 

* `Constant` - constant model used (currently the only option)

| key | _required_
|====================


The XML tags named `IBK:Parameters` with the XML attributes `name` and `unit` with the following entries can be defined:

.Zone Parameters that can be set as *IBK:Parameter* with the Attributes `name` and `unit`
[options="header"]
[cols="25%,^ 8%,42%,^ 10%,^ 10%"]
[width="100%"]
|====================
| Name | Unit | Description | Value Range | Usage 
| `AbsorptionCoefficient` | --- | Constant absorption coefficient | 0...1 | _required_
|====================

## Long Wave Emission

The long wave emission over the interface is described by the XML tag `InterfaceLongWaveEmission`. This coefficient describes the long wave absorption and emission by the interface.

image::longwave.svg[width=40%]

[source,xml, indent=0]
----
<InterfaceLongWaveEmission modelType="Constant">
	<IBK:Parameter name="Emissivity" unit="---">0.9</IBK:Parameter>
</InterfaceLongWaveEmission>
----

The `InterfaceLongWaveEmission` needs to be defined with the following XML attribute `modelType`.

.Parameters for the InterfaceLongWaveEmission-Tag
[options="header",cols="20%,60%,^ 10%,^ 10%",width="100%"]
|====================
| Attribute  | Description | Format | Usage 
| `modelType` 
a|  Sets the type of the heat conduction model 

* `Constant` - constant model used (currently the only option)

| key | _required_
|====================


The XML tags named `IBK:Parameters` with the XML attributes `name` and `unit` with the following entries can be defined:

.Zone Parameters that can be set as *IBK:Parameter* with the Attributes `name` and `unit`
[options="header"]
[cols="25%,^ 8%,42%,^ 10%,^ 10%"]
[width="100%"]
|====================
| Name | Unit | Description | Value Range | Usage 
| `Emissivity` | --- | Constant absorption coefficient | 0...1 | _required_
|====================

## Vapour Diffusion

[WARNING]
====
TO BE DEFINED LATER.
====

The vapour diffusion over the interface is described by the XML tag `InterfaceVaporDiffusion`.

[source,xml, indent=0]
----
<InterfaceVaporDiffusion modelType="Constant">
	<IBK:Parameter name="VaporTransferCoefficient" unit="s/m">1</IBK:Parameter>
</InterfaceVaporDiffusion>
----

The `InterfaceVaporDiffusion` needs to be defined with the following XML attribute `modelType`.

.Parameters for the InterfaceVaporDiffusion-Tag
[options="header",cols="20%,60%,^ 10%,^ 10%",width="100%"]
|====================
| Attribute  | Description | Format | Usage 
| `modelType` 
a|  Sets the type of the heat conduction model 

* `Constant` - constant model used (currently the only option)

| key  | _required_
|====================


The XML tags named `IBK:Parameters` with the XML attributes `name` and `unit` with the following entries can be defined:

.Zone Parameters that can be set as *IBK:Parameter* with the Attributes `name` and `unit`
[options="header"]
[cols="25%,^ 8%,42%,^ 10%,^ 10%"]
[width="100%"]
|====================
| Name | Unit | Description | Value Range | Usage 
| `VaporTransferCoefficient` | s/m | Vapor Transfer Coefficient | {nbsp}>{nbsp}0.0{nbsp} | _required_
|====================

## Air Flow

[WARNING]
====
TO BE DEFINED LATER.
====

The air flow over the interface is calculate with a pressure coefficient. It is described inside the XML tag `InterfaceAirFlow`.

[source,xml, indent=0]
----
<InterfaceAirFlow modelType="Constant">
	<IBK:Parameter name="PressureCoefficient" unit="---">0.6</IBK:Parameter>
</InterfaceAirFlow>
----

The `InterfaceAirFlow` needs to be defined with the following XML attribute `modelType`.

.Parameters for the InterfaceAirFlow-Tag
[options="header",cols="20%,60%,^ 10%,^ 10%",width="100%"]
|====================
| Attribute  | Description | Format | Usage 
| `modelType` 
a|  Sets the type of the air flow

* `Constant` - constant model used (currently the only option)

| key | _required_
|====================


The XML tags named `IBK:Parameters` with the XML attributes `name` and `unit` with the following entries can be defined:

.Pressure Coefficient Parameters that can be set as *IBK:Parameter* with the Attributes `name` and `unit`
[options="header"]
[cols="25%,^ 8%,42%,^ 10%,^ 10%"]
[width="100%"]
|====================
| Name | Unit | Description | Value Range | Usage 
| `PressureCoefficient` | --- | Pressure Coefficient | 0...1 | _required_
|====================


