# Climatic loads

## Overview

Climatic loads in NANDRAD are provided by means of climate data files. The climatic loads model is a purely time-dependent model without other input dependencies. For solar radiation calculation, it needs information on the building location, and also the orientation and inclination of the various surfaces.

## Specification

Information about location and climate data is stored in the `Location` section of the project file:

[source,xml]
----
<Location>
	<IBK:Parameter name="Latitude" unit="Deg">51</IBK:Parameter>
	<IBK:Parameter name="Longitude" unit="Deg">13</IBK:Parameter>
	<IBK:Parameter name="Albedo" unit="-">0.2</IBK:Parameter>
	<IBK:Parameter name="Altitude" unit="m">100</IBK:Parameter>
	<ClimateFileName>${Project Directory}/climate/GER_Potsdam_2017.c6b</ClimateFileName>
</Location>
----

The parameter `Albedo` is used for diffuse solar radiation calculation (see <<loads_solar_radiation>>).

Parameters `Latitude` and `Longitude` are optional if a climate data file is given, otherwise they override the location parameters stored therein (see <<location_settings>>).

`Altitude` is (later) needed for specific altitude-related parameters (**TODO**).

The `<ClimateFileName>` tag defines the path to the climate data file.

[[loads_climate_files]]
### Climate Data Files

Currently, `c6b`, `wac` and `epw` files are supported (see also help for the https://bauklimatik-dresden.de/ccmeditor/help[CCM-Editor] tool).

You need to specify the path to the climate data file in the `<ClimateFileName>` tag. Hereby, you can specify an absolute or relative path.

If a relative path is privided, it will be resolved using the current working directory as reference. For example, if you have specified 

[source,xml]
----
<ClimateFileName>GER_Potsdam_2017.c6b</ClimateFileName>
----

and the solver is run from the directory `/home/user/sim/Project1`, the climate data file will be searched in `/home/user/sim/Project1/GER_Potsdam_2017.c6b`. If the solver is run from a different directory, the referenced climate data file won't be found and an error message is raised.

To avoid this problem, you may specify directory placeholders to locate the climate data file _relative_ to the project file's location. The builtin path placeholder `${Project Directory}` will be replaced by the directory the project file is located in. Use the placeholder just as a regular directory part, for example:

[source,xml]
----
<ClimateFileName>${Project Directory}/climate/GER_Potsdam_2017.c6b</ClimateFileName>
----

It is possible to define custom placeholders in the project for all externally referenced files, see <<path_placeholders>>.




[[location_settings]]
### Building/Station location

Typically, climate data files contain information on latitude and longitude of the weather station. 

- If these parameters are not specified explicitely in the project file, the latitude/longitude from the climate data file are used.
- If parameters are specified in the project file, always **both** parameters must be given (and be valid) and then the these parameters from the project file are used instead of the climate data file location parameters.

Valid value range for `Latitude` is [-90,90] degrees (positive values are northern hemisphere), for `Longitude` it is [-180,180] degrees (positive values are east of Greenwich).


### Additional radiation sensors

It is possible to specify additional planes (sensors) to generate solar radiation load outputs.

This is done by specifying a `Sensor` definition.


[[loads_solar_radiation]]
### Solar Radiation Calculation

## Implementation

The `Loads` model is a pre-defined model that is always evaluated first whenever the time point has changed. It does not have any other dependencies.

It provides all resulting variables as `constant` (during iteration) result variables, which can be retrieved and utilized by any other model.

With respect to solar radiation calculation, during initialization it registers all surfaces (with different orientation/inclination) and provides an ID for each surface. Then, models can request direct and diffuse radiation data, as well as incidence angle for each of the registered surfaces.

### Registering surfaces

Each construction surface (interface) with outside radiation loads registers itself with the Loads object, hereby passing the interface object ID as argument and orientation/inclination of the surface. The loads object itself registers this surface with the climate calculation module (CCM) and retrieves a surface ID. This surface ID may be the same for many interface IDs.

The Loads object stores a mapping of all interface IDs to the respective surface IDs in the CCM. When requesting the result variable's memory location, this mapping is used to deliver the correct input variable reference/memory location to the interface-specific solar radiation calculation object.





