:imagesdir: ./images
[[project_file]]
# NANDRAD Project File Structure

The NANDRAD project specification is stored in an XML-file with the extension `nandrad`. The principle structure of the file looks like:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8" ?>
<NandradProject fileVersion="2.0">
	<!-- optional DirectoryPlaceholders section-->
	<DirectoryPlaceholders>
		<Placeholder name="MyDatabase">/home/sim/climate_DB</Placeholder>
	</DirectoryPlaceholders>

	<Project>
	    <!-- the actual project specification -->
   </Project>
</NandradProject>
----

The optional `DirectoryPlaceholders` can be used to define relative path placeholders to be used for externally referenced files (see section <<path_placeholders>>).

All project data is enclosed in the `<Project>` tag.

A project file may contain the following child tags:

* `Location` - Climatic data and location settings -> <<climatic_loads>>


[[basic_types]]
# Basic Data Types in NANDRAD Project File Specification

Within the various specificiation sections of the project file some basic data types / xml-tags are frequently used. The rules for specifying these parameters are defined below.

[[IBK_parameter]]
## IBK:Parameter

An xml tag with name `IBK:Parameter` defines a floating point value parameter, identified by a name and physical unit (XML-attributes `name` and `unit`). The value of the xml tag is the actual parameter value.

.Parameters with different units
====
[source,xml]
----
<IBK:Parameter name="Volume" unit="m3">30</IBK:Parameter>
<IBK:Parameter name="Temperature" unit="C">20</IBK:Parameter>
<IBK:Parameter name="Temperature" unit="K">293.15</IBK:Parameter>
<!-- unitless parameters take the --- unit -->
<IBK:Parameter name="RelTol" unit="---">0.7</IBK:Parameter>
----
====

The units must be selected from the global unit list, see section <<units>>.

## IBK:IntPara

## IBK:Flag

## IBK:LinearSpline


[[path_placeholders]]
# Path Placeholders

In some parts of the NANDRAD project file, external files are referenced (for example climate data files, see <<loads_climate_files>>).
To simplify exchange of projects or reference data files in common database directories, it is possible to use path placeholders in file paths.

For example, you can define `${MyDatabase}` to be `/home/sim/climate_DB` and then in your project reference a climate data file
via `${MyDatabase}/ClimateData.epw`.

These mapping of the placeholders is done early in the project file, so when exchanging project files between computers, you may
easily modify the placeholder paths to the directories on the local machine without any further changes in the project file.

The individual path placeholders are defined in the `DirectoryPlaceholders`, for example:

[source,xml]
----
<DirectoryPlaceholders>
	<Placeholder name="Climate DB">/home/sim/climate_DB</Placeholder>
	<Placeholder name="DataFiles">/home/sim/data</Placeholder>
</DirectoryPlaceholders>
----

There is one builtin-placeholder `${Project Directory}` that will be automatically defined with the path to the directory of the project file.
