:imagesdir: ./images
[[project_file]]
# Project File Structure

The NANDRAD project specification is stored in an XML-file with the extension `nandrad`. The principle structure of the file looks like:

.Definition of a NANDRAD Project File
====
[source,xml]
----
<?xml version="1.0" encoding="UTF-8" ?>
<NandradProject fileVersion="2.0">
	<!-- optional DirectoryPlaceholders section-->
	<DirectoryPlaceholders>...</DirectoryPlaceholders>

    <!-- the actual project specification -->
	<Project>
	    <ProjectInfo>...</ProjectInfo>
	    <Location>...</Location>
	    <SimulationParameter>...</SimulationParameter>
	    <SolverParameter>...</SolverParameter>
	    <Zones>...</Zones>
	    <ConstructionInstances>...</ConstructionInstances>
	    <ConstructionTypes>...</ConstructionTypes>
	    <Materials>...</Materials>
	    <Models>...</Models>
	    <Schedules>...</Schedules>
	    <Outputs>...</Outputs>
	    <ObjectLists>...</ObjectLists>
	</Project>
</NandradProject>
----
====

The optional `DirectoryPlaceholders` can be used to define relative path placeholders to be used for externally referenced files (see section <<path_placeholders>>).

All project data is enclosed in the `<Project>` tag.

A project file may contain the following child tags (order is arbitrary):

[width="100%",options="header", cols="15%,85%"]
|====================
| Child tag | Description
| `ProjectInfo` | General project meta information -> <<project_info>>
| `Location` | Climatic data and location settings -> <<climatic_loads>>
| `SimulationParameter` | Simulation model parameters -> <<simulation_parameters>>
| `SolverParameter` | Numerical solver settings and performance options -> <<solver_parameters>>
| `Zones` | Zone specifications -> <<zones>>
| `ConstructionInstances` | Building components and boundary conditions -> <<construction_instances>>
| `ConstructionTypes` | Definition of multi-layered constructions -> <<construction_types>>
| `Materials` | Material properties -> <<materials>>
| `Models` | Model parameter blocks -> <<models>>
| `Schedules` | Definition of scheduled parameters -> <<schedules>>
| `Outputs` | Output definitions -> <<outputs>>
| `ObjectLists` | Definition of object lists/object reference groups -> <<object_lists>>
|====================


[[basic_types]]
# Basic Data Types in NANDRAD Project File Specification

Within the various specificiation sections of the project file some basic data types / xml-tags are frequently used. The rules for specifying these parameters are defined below.

[[IBK_Parameter]]
## IBK:Parameter

An XML tag with name `IBK:Parameter` defines a floating point value parameter, identified by a name and physical unit (mandatory XML-attributes `name` and `unit`). The value of the xml tag is the actual parameter value.

.Parameters with Different Units
====
[source,xml]
----
<IBK:Parameter name="Volume" unit="m3">30</IBK:Parameter>
<IBK:Parameter name="Temperature" unit="C">20</IBK:Parameter>
<IBK:Parameter name="Temperature" unit="K">293.15</IBK:Parameter>
<!-- unitless parameters take the --- unit -->
<IBK:Parameter name="RelTol" unit="---">0.7</IBK:Parameter>
----
====

The units must be selected from the global unit list, see section <<units>>. Not defining a parameter will mark it as _missing_, which means that either a default value is used or - in case of mandatory user parameters - an error is raised.

[[IBK_IntPara]]
## IBK:IntPara

Used for whole number parameters. Mandatory attribute `name` identifies the parameter. XML tag value is the parameter value. Not defining a parameter will mark it as _missing_, which means that either a default value is used or - in case of mandatory user parameters - an error is raised.

.Whole Number (Integer) Parameter Definition
====
[source,xml]
----
<IBK:IntPara name="DiscMaxElementsPerLayer">30</IBK:IntPara>
----
====

[[IBK_Flag]]
## IBK:Flag

Used for flags. Mandatory attribute `name` identifies the flag. Not defining a flag will mark it as _missing_, which means that either a default value is used or - in case of mandatory user parameters - an error is raised.

.Flag Definition
====
[source,xml]
----
<IBK:Flag name="EnableCyclicSchedules">true</IBK:Flag>
----
====

Recognized values for flag parameters are `true` and `1`  or `false` and `0`.

[[IBK_LinearSpline]]
## IBK:LinearSpline

A linear spline is effectively a data table of x and y values, where x values are strictly monotonically increasing values. Mandatory attribute `name` identifies the linear spline. The child tags `X` and `Y` hold the actual values, always unitless. Number of x and y values must match.

.Linear Spline Definition
====
[source,xml]
----
<IBK:LinearSpline name="ThermalLoad">
  <X unit="-">0    6    8   10   17   18  19  20</X>
  <Y unit="-">0  0.5  0.8  1.0  0.7  0.6 0.5   0</Y>
</IBK:LinearSpline>
----
====

[[LinearSplineParameter]]
## LinearSplineParameter

A linear spline parameter is effectively an extended `IBK:LinearSpline` parameter with additional attributes.

.Linear Spline Parameter Definition
====
[source,xml]
----
<LinearSplineParameter name="ThermalLoad" interpolationMethod="linear">
  <X unit="h">0    6    8   10   17   18  19  20</X>
  <Y unit="W">0  0.5  0.8  1.0  0.7  0.6 0.5   0</Y>
</LinearSplineParameter>
----
====

.Attributes
[options="header",cols="20%,60%,^ 10%,^ 10%",width="100%"]
|====================
|Attribute {set:cellbgcolor:transparent} |Description|Format|Usage
| `name` | Specific name that references to the space type the annual schedule will be set for | string | _required_
| `interpolationMethod` 
a| Specifies the interpolation method between the defined y values.

* `constant` - constant interpolation (values constant during time step) 
* `linear` - linear interpolation (values linear interpolated between time steps)  

| key | _required_
| `WrapMethod` 
|====================

The child tags `X` and `Y` each hold a mandatory attribute `unit` with the respective value unit (see <<units>>).


[[path_placeholders]]
# Path Placeholders

In some parts of the NANDRAD project file, external files are referenced (for example climate data files, see <<loads_climate_files>>).
To simplify exchange of projects or reference data files in common database directories, it is possible to use path placeholders in file paths.

For example, you can define `${MyDatabase}` to be `/home/sim/climate_DB` and then in your project reference a climate data file
via `${MyDatabase}/ClimateData.epw`.

These mapping of the placeholders is done early in the project file, so when exchanging project files between computers, you may
easily modify the placeholder paths to the directories on the local machine without any further changes in the project file.

The individual path placeholders are defined in the `DirectoryPlaceholders`:

.Custom Directory Placeholders
====
[source,xml]
----
<DirectoryPlaceholders>
	<Placeholder name="Climate DB">/home/sim/climate_DB</Placeholder>
	<Placeholder name="DataFiles">/home/sim/data</Placeholder>
</DirectoryPlaceholders>
----
====

There is one builtin-placeholder `${Project Directory}` that will be automatically defined with the path to the directory of the project file.

[[project_info]]
# Project Information

This section contains change times/dates and a brief description of the project.

TODO
