# Tutorials

This section contains several tutorials for different use cases in NANDRAD2. It will start with a simple tutorial for a single room. 

[[Tutorial1]]
## Tutorial 1 - Simple Single Room

### Introduction

In this example a single thermal zone modelling is described. The main focus is put on the geometry, material and construction parametrization. The temperature of the freely oscillating room is given as the result output. The dimensions of the room are `l = 2.0 m` length, `b = 5.0 m` width and `h = 3.0 m` height. This leads to an air volume of `V = 30.0 m³`. All further characteristic values are specified in the following.

PICTURE

### Workflow

First all materials inside `Materials` and the used constructions inside `ConstructionTypes` are defined, which are needed for the test zone. Afterwards all enveloping surfaces inside `ConstructionInstances` are parametrized and the output parameters inside `Outputs` are set. Finally, the climate is specified inside `Location` and further simulation settings inside `SimulationParameter`.

### Materials and constructions

The building consists of a floor, a wall and a roof construction. The constructions are shown in the following table.

[width="100%", cols="<.^,^,^,^,^,^",options="header"]
|====================
| name | id | thickness [m] | &lambda; [W/mK] | &rho; [kg/m³] | ce [J/kgK] 
| *floor* |103 4+|
| concrete | 1001 | 0.20 | 2.3 | 2000 | 1000 
| Insulation | 1004 | 0.05 | 0.04 | 50 | 1500
6+|
| *roof* | 102 4+|
| Insulation | 1004 | 0.20 | 0.04 | 50 | 1500
| Wood | 1002 | 0.05 | 0.17 | 500 | 2100 
| | | | | |
| *wall* | 101 4+|
| concrete | 1001 | 0.20 | 2.3 | 2000 | 1000 
| Insulation | 1004 | 0.10 | 0.04 | 50 | 1500
|====================

[[MaterialsTutorial1]]
#### Materials

For the materials the thermal parameters such as `thermal conductivity` `&lambda;`, `density` `&rho;` and `heat capacity` `ce` are required. Furthermore a unique Id `id` and name `displayName` is needed. Exemplary the description for concrete and insulation is given below. The detailed documentation is described in <<MaterialsDocumentation,Materials>>.

Example:
[source,xml]
----
<Materials>
	<Material id="1001" displayName="Concrete">
		<IBK:Parameter name="Density" unit="kg/m3">2000</IBK:Parameter>
		<IBK:Parameter name="HeatCapacity" unit="J/kgK">1000</IBK:Parameter>
		<IBK:Parameter name="Conductivity" unit="W/mK">2.3</IBK:Parameter>
	</Material>
	<Material id="1004" displayName="Insulation">
		<IBK:Parameter name="Density" unit="kg/m3">50</IBK:Parameter>
		<IBK:Parameter name="HeatCapacity" unit="J/kgK">1500</IBK:Parameter>
		<IBK:Parameter name="Conductivity" unit="W/mK">0.04</IBK:Parameter>
	</Material>
</Materials>
----

[TIP]
====
Execute ToDo hygric parameters
====

[[ConstructionsTutorial1]]
#### constructions

Afterwards the <<ConstructionTypesDocumentation,Constructions>> in `ConstructionTypes` are assembled from the <<MaterialsDocumentation,Materials>> via the `Id` matching the `Id` in the `materials` and also the layer thickness `d`. As with the materials, a construction is always assigned a unique identifier `id` and optionally a name `displayName`. Transfer and other parameters are not part of the construction and are defined inside the <<ConstructionInstancesDocumentation,Constructions>> that represent an enveloping surface. For the later usage inside the `ConstructionInstance` the first material layer `MaterialLayer` inside the `MaterialLayers` List is linked to the `InterfaceA` and the last material layer to the `InterfaceB`. Thus, the inside or outside of the construction can be defined individually inside the <<ConstructionInstancesDocumentation,Constructions>>.

The wall construction is examplarily shown below. 

Example:
[source,xml]
----
<ConstructionTypes>
	<ConstructionType id="101" displayName="Wall Construction">
		<MaterialLayers>
			<MaterialLayer thickness="0.2" matId="1001" /> <!-- Linked to InterfaceA -->
			<MaterialLayer thickness="0.1" matId="1004" /> <!-- Linked to InterfaceB -->
		</MaterialLayers>
	</ConstructionType>
</ConstructionTypes>

----

#### Zone

In this section the Zone and its parameters are defined. Geometrically, the zone represents the volume of air inside the room. All further geometrical properties are defined inside the tag named `ConstructionInstances`. Besides the `Volume` an `Area` is specified, which is needed for the conversion of area specific loads to room loads. These space loads are not described in this tutorial. 
The uniqueness of the zone is guaranteed by an identifier `id`. Optionally a name `displayName` can be assigned again. The `type` of the zone sets the calculation mode for the zone. Three types are distinguished:

* `Active` The zone is calculated by the solver via the energy balance equations and the room air temperature results from the gains and losses of all energy flows.
* `Constant` The zone is defined by a given temperature. It can be defined by a schedule, which does not have to be constant.
* `Ground` The floor temperatures from the default climate file are used for the room air temperature. The zone thus represents the adjacent soil.

The volume and the area are defined via so-called <<IBK_ParameterDocumentation,`IBK:Parameter`>>. 
The zone volume is defined in the example room with `V = 30 m³`. The base area is described with `A = 10 m²`. 

Example:
[source,xml]
----
<Zones>
	<Zone id="1" displayName="Single room model" type="Active">
		<IBK:Parameter name="Area" unit="m2">10</IBK:Parameter>
		<IBK:Parameter name="Volume" unit="m3">30</IBK:Parameter>
	</Zone>
</Zones>
----

Further setting options can be found in the detailed <<NANDRAD-Geometry.adoc#ZoneDocumentation,zone>> documentation.

#### Envelope areas

The envelopes are described in the `ConstructionInstances`. Each envelope surface named `ConstructionInstance` is represented by an Id `id`, optionally a name `displayName`, a surface, a construction and the transition conditions represented by different models.
The surface is described by an `IBC:Parameter` with the attribute `Area`. The construction is linked to the construction from `ConstructionTypes` via the `ConstructionTypeId`. 
The boundary conditions are defined via the interfaces `InterfaceA` and `InterfaceB`. As boundary conditions transfer coefficients and solar as well as thermal absorption coefficients are defined. These are each described by a separate model.

In the example the wall envelope surface is shown. The selected wall is defined by an area `A = 15 m²`, a wall construction with the `id = 101` and an inside and outside boundary condition. The outside boundary condition is described with a constant transition coefficient of `h = 15 W/(m²K)`, a solar absorptance of `a = 0.6` and a long-wave absorption/emission of `&epsilon; = 0.9`. On the inside, only a transition coefficient `h = 10 W/(m²K)` is described.

Further setting options can be found in the detailed <<NANDRAD-Geometry.adoc#ZoneDocumentation, ConstructionInstance>> documentation.

Example:
[source,xml]
----
<ConstructionInstances>
	<ConstructionInstance id="1" displayName="West Wall">
		<ConstructionTypeId>101</ConstructionTypeId>
		<IBK:Parameter name="Area" unit="m2">15</IBK:Parameter>
		<InterfaceA id="10" zoneId="1">
			<!--Interface to `Room`-->
			<InterfaceHeatConduction modelType="Constant">
				<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">10</IBK:Parameter>
			</InterfaceHeatConduction>
		</InterfaceA>
		<InterfaceB id="11" zoneId="0">
			<!--Interface to outside-->
			<InterfaceHeatConduction modelType="Constant">
				<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">15</IBK:Parameter>
			</InterfaceHeatConduction>
			<InterfaceSolarAbsorption modelType="Constant">
				<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">0.6</IBK:Parameter>
			</InterfaceHeatConduction>
			<InterfaceLongWaveEmission modelType="Constant">
				<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">0.9</IBK:Parameter>
			</InterfaceHeatConduction>
		</InterfaceB>
	</ConstructionInstance>
</ConstructionInstances>
---- 