:imagesdir: ./images
[[zones]]
# Zones

In order to model buildings, it is necessary to define the individual rooms with the relevant parameters. A zone defines a well-mixed thermal zone/room with a single/uniform air temperature.

Objects of type `Zone` store all properties needed to compute zone temperature from energy density (the conserved quantity).

Zones can be either _Constant_ or __Active__.

For _Constant_ zones, the temperature is assumed to
be fixed/predefined whereas in _Active_ zones the temperature is computed (i.e. included in
the model's unknowns). A _Constant_ zone only needs the temperature parameter.

.Zone Definition
====
[source,xml,indent=0]
----
<Zones>
	<Zone id="1" displayName="Var01" type="Active">
		<IBK:Parameter name="Area" unit="m2">10</IBK:Parameter>
		<IBK:Parameter name="Volume" unit="m3">30</IBK:Parameter>
	</Zone>
</Zones>
----
====

Inside the XML tag named `Zones` each zone starts with the XML tag `Zone`. The following XML attributes need to be defined:

[source,xml]
----
<Zone id="1" displayName="Var01" type="Active">
----

[options="header",cols="20%,60%,^ 10%,^ 10%",width="100%"]
|====================
| Attribute  | Description | Format | Usage 
| *id* |  Identifier of the Zone | positive Integer ({nbsp}>{nbsp}0{nbsp})  | _required_
| *displayName*  |  Display Name of the Zone. Is needed to find the Zone in the Data Model and in Outputs more easily. | string | _optional_
| *type*  
a|  Defines whether zone is balanced and included in equation system.

* `Constant` _as zone with constant/predefined temperatures. (schedule)_
* `Active` _as zone described by a temperature node in space_
* `Ground` _as ground zone (calculates temperature based on standard)_ | string | _optional_

|====================

Parameters (see section <<IBK_Parameter>> for a description of the `IBK:Parameter` tag):

[options="header",cols="15%,10%,45%,20%,10%",width="100%"]
|====================
|`name`|Default Unit|Description|Value Range |Usage
| *Volume* | m3 | Zone air volume | positive double ({nbsp}>{nbsp}0.0{nbsp}) | _required_
| *Area* | m2 | Net usage area of the ground floor (for area-related outputs and loads) | positive double ({nbsp}>{nbsp}0.0{nbsp}) | _optional_
| *HeatCapacity* | J/K | Additional heat capacity (furniture, etc.) | 0...1 | _optional_
| *Temperature* | C | Temperature of the zone, if set `constant` | 0...1 | _optional_
| *CO2Concentration* | g/m3 | CO2 concentration of the zone, if set `constant` | 0...1 | _optional_
| *RelativeHumidity* | % | Temperature of the zone, if set `constant` | 0...1 | _optional_
|====================


[[construction_instances]]
# Construction Instances

The construction instances define construction-specific parameters required by several models.

.Construction Instances
====
[source,xml,indent=0]
----
<ConstructionInstances>
	<!-- Surface Var 01 -->
	<ConstructionInstance id="1" displayName="All Surfaces Var01">
		<ConstructionTypeId>10005</ConstructionTypeId>
		<IBK:Parameter name="Area" unit="m2">62</IBK:Parameter>
		<InterfaceA id="10" zoneId="1">
			<!--Interface to 'Room'-->
			<InterfaceHeatConduction modelType="Constant">
				<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">2.5</IBK:Parameter>
			</InterfaceHeatConduction>
		</InterfaceA>
		<InterfaceB id="11" zoneId="0">
			<!--Interface to outside-->
			<InterfaceHeatConduction modelType="Constant">
				<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">8</IBK:Parameter>
			</InterfaceHeatConduction>
		</InterfaceB>
	</ConstructionInstance>
</ConstructionInstances>
----
====


The construction instances are defined inside the Sections starting with an XML tag `ConstructionInstances`. Inside the Section each Construction instance starts with the XML tag named `ConstructionInstance` with the XML attributes `id` and `displayName`. 
Inside that it is necessary to specify the interfaces with the XML tag named `InterfaceA` and `InterfaceB`. Finally the Interfaces with the XML tag `InterfaceA` and `InterfaceB` need to be defined with the XML attributes `id` and `zoneId`.
In the following it is described in detail.

[options="header",cols="20%,60%,^ 10%,^ 10%",width="100%"]
|====================
| Attribute  | Description | Format | Usage 
| *id* |  Identifier of the Construction Instance | positive Integer ({nbsp}>{nbsp}0{nbsp})  | _required_
| *displayName*  |  Display Name of the Construction Instance. Is needed to find the Construction Instance in the Data Model and in Outputs more easily. | string | _optional_
|====================

The construction instance has the following `required subtag`:

* `constructionTypeId` - unique Id that defines the construction type of the construction instance

Example:
[source,xml]
----
<ConstructionTypeId>10005</ConstructionTypeId>
----

The following XML tags named `IBK:Parameters` with the XML attributes `name` and `unit` with the following entries can be defined:

.Zone Parameters that can be set as *IBK:Parameter* with the Attributes `name` and `unit`
[options="header"]
[cols="25%,^ 8%,42%,^ 10%,^ 10%"]
[width="100%"]
|====================
| `name` | `unit`| Description | Format | Usage 
| *Orientation* | m2 | Orientation of the wall | positive double ({nbsp}>{nbsp}0.0{nbsp}) | _required_
| *Inclination* | m3 | Inclination of the wall | positive double ({nbsp}>{nbsp}0.0{nbsp}) | _required_
| *Area* | C | Gross area of the wall | 0...1 | _required_
|====================




[[InterfacesDocumentation]]
# Interfaces (construction boundary conditions)

.Interfaces
====
[source,xml,indent=0]
----
<InterfaceA id="10" zoneId="1">
	<InterfaceHeatConduction modelType="Constant">
		<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">2.5</IBK:Parameter>
	</InterfaceHeatConduction>
</InterfaceA>
<InterfaceB id="11" zoneId="0">
	<InterfaceHeatConduction modelType="Constant">
		<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">8</IBK:Parameter>
	</InterfaceHeatConduction>
    <InterfaceSolarAbsorption model="Constant">
        <IBK:Parameter name="AbsorptionCoefficient" unit="---">0.6</IBK:Parameter>
    </InterfaceSolarAbsorption>
    <InterfaceLongWaveEmission model="Constant">
        <IBK:Parameter name="Emissivity" unit="---">0.9</IBK:Parameter>
    </InterfaceLongWaveEmission>
</InterfaceB>
----
====


Interfaces are defining boundary conditions and parameters for the two surfaces `InterfaceA` and `InterfaceB` of a constructions instance. There can be only constructions with two interfaces or less. 

`InterfaceA` and `InterfaceB` can have the following `subtags`:

## Heat Conduction

The Heat Conduction over the Interface is described by the XML tag `InterfaceHeatConduction`.

[.indent-me]
[source,xml, indent=0]
----
<InterfaceHeatConduction modelType="Constant">
	<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">2.5</IBK:Parameter>
</InterfaceHeatConduction>
----

The `InterfaceHeatConduction` needs to be defined with the following XML attribute `modelType`.
.Parameters for the InterfaceHeatConduction-Tag
[.indent-me]
[options="header",cols="20%,60%,^ 10%,^ 10%",width="100%"]
|====================
| Attribute  | Description | Format | Usage 
| *modelType* 
a|  Sets the type of the heat conduction model 

* `Constant` - Constant model used (currently the only option)

| positive Integer ({nbsp}>{nbsp}0{nbsp})  | _required_
|====================


The XML tags named `IBK:Parameters` with the XML attributes `name` and `unit` with the following entries can be defined:

.Zone Parameters that can be set as *IBK:Parameter* with the Attributes `name` and `unit`
[options="header"]
[cols="25%,^ 8%,42%,^ 10%,^ 10%"]
[width="100%"]
|====================
| `name` | `unit`| Description | Format | Usage 
| *HeatTransferCoefficient* | W/m2 | Constant heat transfer coefficient | positive double ({nbsp}>{nbsp}0.0{nbsp}) | _required_
|====================

## Solar Absorption

The Solar Absorption over the Interface is described by the XML tag `InterfaceSolarAbsorption`.

[source,xml, indent=0]
----
<InterfaceSolarAbsorption modelType="Constant">
	<IBK:Parameter name="AbsorptionCoefficient" unit="---">0.6</IBK:Parameter>
</InterfaceHeatConduction>
----

The `InterfaceSolarAbsorption` needs to be defined with the following XML attribute `modelType`.

.Parameters for the InterfaceSolarAbsorption-Tag
[options="header",cols="20%,60%,^ 10%,^ 10%",width="100%"]
|====================
| Attribute  | Description | Format | Usage 
| *modelType* 
a|  Sets the type of the heat conduction model 

* `Constant` - constant model used (currently the only option)

| positive Integer ({nbsp}>{nbsp}0{nbsp})  | _required_
|====================


The XML tags named `IBK:Parameters` with the XML attributes `name` and `unit` with the following entries can be defined:

.Zone Parameters that can be set as *IBK:Parameter* with the Attributes `name` and `unit`
[options="header"]
[cols="25%,^ 8%,42%,^ 10%,^ 10%"]
[width="100%"]
|====================
| `name` | `unit`| Description | Format | Usage 
| *AbsorptionCoefficient* | m2 | Constant Absorption coefficient | 0...1 | _required_
|====================

## Long Wave Emission

The long wave emission over the interface is described by the XML tag `InterfaceLongWaveEmission`.

[source,xml, indent=0]
----
<InterfaceLongWaveEmission modelType="Constant">
	<IBK:Parameter name="Emissivity" unit="---">0.9</IBK:Parameter>
</InterfaceLongWaveEmission>
----

The `InterfaceLongWaveEmission` needs to be defined with the following XML attribute `modelType`.

.Parameters for the InterfaceLongWaveEmission-Tag
[options="header",cols="20%,60%,^ 10%,^ 10%",width="100%"]
|====================
| Attribute  | Description | Format | Usage 
| *modelType* 
a|  Sets the type of the heat conduction model 

* `Constant` - constant model used (currently the only option)

| positive Integer ({nbsp}>{nbsp}0{nbsp})  | _required_
|====================


The XML tags named `IBK:Parameters` with the XML attributes `name` and `unit` with the following entries can be defined:

.Zone Parameters that can be set as *IBK:Parameter* with the Attributes `name` and `unit`
[options="header"]
[cols="25%,^ 8%,42%,^ 10%,^ 10%"]
[width="100%"]
|====================
| `name` | `unit`| Description | Format | Usage 
| *Emissivity* | m2 | Constant Absorption coefficient | 0...1 | _required_
|====================

## Vapour Diffusion

The vapour diffusion over the interface is described by the XML tag `InterfaceVaporDiffusion`.

[source,xml, indent=0]
----
<InterfaceVaporDiffusion modelType="Constant">
	<IBK:Parameter name="VaporTransferCoefficient" unit="s/m">1</IBK:Parameter>
</InterfaceVaporDiffusion>
----

The `InterfaceVaporDiffusion` needs to be defined with the following XML attribute `modelType`.

.Parameters for the InterfaceVaporDiffusion-Tag
[options="header",cols="20%,60%,^ 10%,^ 10%",width="100%"]
|====================
| Attribute  | Description | Format | Usage 
| *modelType* 
a|  Sets the type of the heat conduction model 

* `Constant` - constant model used (currently the only option)

| positive Integer ({nbsp}>{nbsp}0{nbsp})  | _required_
|====================


The XML tags named `IBK:Parameters` with the XML attributes `name` and `unit` with the following entries can be defined:

.Zone Parameters that can be set as *IBK:Parameter* with the Attributes `name` and `unit`
[options="header"]
[cols="25%,^ 8%,42%,^ 10%,^ 10%"]
[width="100%"]
|====================
| `name` | `unit`| Description | Format | Usage 
| *VaporTransferCoefficient* | s/m | Vapor Transfer Coefficient | positive Double ({nbsp}>{nbsp}0.0{nbsp}) | _required_
|====================

## Air Flow

The air flow over the interface is described by the XML tag `InterfaceAirFlow`.

[source,xml, indent=0]
----
<InterfaceAirFlow modelType="Constant">
	<IBK:Parameter name="PressureCoefficient" unit="---">0.6</IBK:Parameter>
</InterfaceAirFlow>
----

The `InterfaceAirFlow` needs to be defined with the following XML attribute `modelType`.

.Parameters for the InterfaceAirFlow-Tag
[options="header",cols="20%,60%,^ 10%,^ 10%",width="100%"]
|====================
| Attribute  | Description | Format | Usage 
| *modelType* 
a|  Sets the type of the air flow

* `Constant` - constant model used (currently the only option)

| positive Integer ({nbsp}>{nbsp}0{nbsp})  | _required_
|====================


The XML tags named `IBK:Parameters` with the XML attributes `name` and `unit` with the following entries can be defined:

.Pressure Coefficient Parameters that can be set as *IBK:Parameter* with the Attributes `name` and `unit`
[options="header"]
[cols="25%,^ 8%,42%,^ 10%,^ 10%"]
[width="100%"]
|====================
| `name` | `unit`| Description | Format | Usage 
| *PressureCoefficient* | --- | Pressure Coefficient | 0...1 | _required_
|====================


# Ambient climate boundary conditions

# Interface between constructions and zones (internal boundary conditions)

