:imagesdir: ./images
# Zustand der Benutzeroberfläche (View State)

Die Benutzeroberfläche hat verschiedene Zustände, wobei ein Zustand beschreibt:

- welche Ansicht ein Widget zeigt, z.B. welches Property-Widget gerade aktiv/sichtbar ist
- welche Maus-/Tastaturinteraktionsmöglichkeiten bestehen, z.B. was die linke
  Maustaste bewirkt oder welche Snap-Funktionen eingeschaltet sind
- was die Szene anzeigt (z.B. lokales Koordinatensystem sichtbar oder nicht)

Da das Verändern eines Zustands mehrere Teile der Oberfläche (und damit mehrere Objekte)
betrifft, wird das Ändern des Oberflächenzustands zentralisiert über einen
Zustandsmanager (`SVViewStateHandler`) erledigt. 
Beim Setzen eines neuen Zustands sendet dieser ein Signal aus.

Alle Widgets/Objekte, die sich in Abhängigkeit des
Zustands verändern müssen, sollten auf dieses Signal reagieren und sich
entsprechend anpassen.

Eine Veränderung des Zustands kann überall in der Programmoberfläche ausgelöst werden und
erfolgt in folgenden Schritten:

- holen des aktuellen Zustands (Objekt `ViewState`)
- anpassen des Zustandsbeschreibungsobjekts
- setzen des neuen Zustands


[source,c++]
----
// aktuellen ViewState holen
ViewState vs = SVViewStateHandler::instance().viewState();
// anpassen
vs.m_sceneOperationMode = OM_SelectedGeometry;
vs.m_propertyWidgetMode = PM_EditGeometry;
// setzen
SVViewStateHandler::instance().setViewState(vs);
----


## `ViewMode`

Umschalten erfolgt durch Modusauswahl-Schaltflächen in der linken Toolbar

- `VM_GeometryEditMode` - wenn Geometrie bearbeitet wird; Geometrie wird mit definierten Oberflächen/Materialfarben dargestellt
- `VM_PropertyEditMode` - beim Eigenschaften ansehen/bearbeiten; Geometrie wird mit Falschfarben je nach Modus dargestellt

Beim Umschalten zwischen den Modi wird die Geometrie neu eingefärbt und gezeichnet.

Im `VM_PropertyEditMode`: `NUM_OM` + `NUM_L` und `PropertyWidgetMode` wird je nach Auswahl im `SVPropModeSelectionWidget` gesetzt, genau wie
`ObjectColorMode`.



(ACHTUNG: Shortcuts zum Ändern des SceneOperationMode deaktivieren!)

Beim Einschalten des `VM_GeometryEditMode` wird unterschieden:

- Es gibt eine Auswahl von Flächen, dann: `OM_SelectedGeometry` + `PM_EditGeometry`
- 


