# Output definitions, conventions/rules and implementation aspects

## Output definitions

Outputs are defined via:

- Grid (when outputs are to be written)
- Variable/Quantity ID name
- Object List (selects object to retrieve data from)
- Time handling (how to handle time averaging/integration)
- (optional) target filename

Example:
[source,xml]
----
<!-- Definition of output grids -->
<Grids>
	<OutputGrid name="hourly">
		<Intervals>
			<Interval>
				<IBK:Parameter name="StepSize" unit="h">1</IBK:Parameter>
			</Interval>
		</Intervals>
	</OutputGrid>
</Grids>
<!-- Definition of outputs -->
<OutputDefinitions>
    <OutputDefinition>
    	<Quantity>Temperature</Quantity>
    	<ObjectListName>All zones</ObjectListName>
    	<GridName>hourly</GridName>
    </OutputDefinition>
    <OutputDefinition>
    	<Quantity>NaturalVentilationFlux</Quantity>
    	<ObjectListName>All zones</ObjectListName>
    	<GridName>hourly</GridName>
    	<TimeType>Integral</TimeType>
    </OutputDefinition>
</OutputDefinitions>


<!-- Referenced object list -->
<ObjectLists>
	<ObjectList name="All zones">
		<FilterID>*</FilterID>
		<ReferenceType>Zone</ReferenceType>
	</ObjectList>
</ObjectLists>
----

`TimeType` is optional, same as `None` by default.
`FileName` is optional (see below).

### Examples

- Requesting fluxes across construction interfaces: object list must reference interfaces
- Requesting energy supplied to layer in construction instance (floor heating): object list must reference construction instance, variable name must reference heat source + index of heat source (if several in construction): `<Quantity>HeatSource[1]</Quantity>` (first heat source in layer, counting from side A in construction, see <<construction_heat_sources, Heat sources in constructions/layers>>).





## Rules

### When no filename is given

Target file name(s) are automatically defined.

All outputs a grouped by:

- grid and quantity type (Load, Schedule, State, Flux, Misc), quantity type is predefined for most quantity IDs (unknowns -> Misc)

- for each used grid:
  - states -> `states_<gridname>.tsv`
  - loads -> `loads_<gridname>.tsv`
  - fluxes -> `fluxes_<gridname>.tsv`
  - fluxes (integrated) -> `flux_integrals_<gridname>.tsv`

Special rule: when only one grid is used, and grid has hourly steps all year round, the suffix `_<gridname>` is omitted.

### When a filename is given

- check: all output definitions using this filename must use the *same* grid (same time points for all columns required!)

- all quantities (regardless of type) are written to this file


## Binary Format

First record: unsigned int - n (number of columns)
Next n records: binary strings, leading size (unsigned int) and termination character (sanity checking)

Next ?? records: unsigned int - n (for checking) and afterwards n doubles

